- lib/file/utils.h
This should fix issue #169 
Haven't had a chance to test it yet, which is why I'm creating this pull request (on the train). If anybody is in a hurry, feel free to test - otherwise I'll look into later this evening.
> fix file overwrite checks

- configure
This should fix issue #176 ...
> configure: add linker flags necessary for multi-threading in static build

- src/gui/mrview/tool/fixel.cpp
- src/gui/mrview/tool/fixel.h
- src/gui/mrview/tool/vector.cpp
- src/gui/mrview/tool/vector.h
@jdtournier I know we're in the midst of qopenglwidget changes, so didn't want to crowbar this into master unless it's ok with you.
* Supports off-grid rendering
* Other small cosmetic changes
> Off-grid rendering of vector plot tool

- src/gui/mrview/tool/overlay.cpp
- src/gui/mrview/tool/overlay.h
Would someone like to try to break this before I merge?
> Overlay tool: Enable volume navigation

- src/gui/mrview/mode/volume.cpp
- src/gui/mrview/mode/volume.h
- src/gui/mrview/tool/view.cpp
- src/gui/mrview/tool/view.h
See #290 for prior discussion.
I do think there's some useful features in there. Even just disabling clip plane highlighting is actually quite handy - it's true the highlight can obscure features otherwise. The intersection mode is interesting - not sure how often I'd use it in practice, but it's very unobtrusive and easily supported, so we should keep it. Only question is whether we use one of the newer options for the highlighting, or stick with the status quo...
> Clipplane interaction

- scripts/revpe_distcorr
- src/gui/mrview/tool/fixel.cpp
Wanted someone to test before merging.
... Whoops, pushed something that was supposed to go somewhere else. Oh well.
> Fixel tool threshold fix

- cmd/mrpad.cpp
(after accidentally adding it to the root directory a while back)
> Moved mrpad to cmd folder 

- src/gui/mrview/tool/fixel.cpp
Didn't actually come across an issue in the viewer; just saw this in the code and it looked wrong...
> Minor fix to fixel overlay

- lib/image/format/mrtrix_utils.cpp
> mih format: handle cases where the file is specified as an absolute path

- src/gui/mrview/tool/tractography/tractogram.cpp
> MRView: fix missing vertex from streamlines

- configure
- scripts/act_anat_prepare_freesurfer
- scripts/act_anat_prepare_fsl
- scripts/dwibiascorrect
- scripts/fs_parc_replace_sgm_first
- scripts/lib/app.py
- scripts/lib/citations.py
- scripts/revpe_distcorr
- scripts/revpe_dwicombine
Adding citation details to MRtrix scripts; particularly as many make use of non-MRtrix commands, and these need to be cited appropriately.
Examples:
If a script is run that uses external software, this appears at the start of the terminal output:
```
$ ~/src/MRtrix3/scripts/act_anat_prepare_fsl t1_reg.nii del.mif
act_anat_prepare_fsl:
act_anat_prepare_fsl: Note that this script makes use of commands / algorithms that have relevant articles for citation, INCLUDING FROM EXTERNAL SOFTWARE PACKAGES. Please consult the help page (-help option) for more information.
act_anat_prepare_fsl:
```
Help page:
```
$ ~/src/MRtrix3/scripts/act_anat_prepare_fsl
Error: the following arguments are required: input, output
usage: act_anat_prepare_fsl [-h] [-continue <TempDir> <LastFile>] [-nocleanup] …
```
> Script citations

- cmd/5ttgen.cpp
- src/dwi/tractography/ACT/act.cpp
Clarify the expectations for a 5TT image, and how to add the pathology
mask to the 5TT image.
> ACT: minor changes to documentation

- scripts/act_anat_prepare_freesurfer
- scripts/act_anat_prepare_fsl
- scripts/dwibiascorrect
- scripts/fs_parc_replace_sgm_first
- scripts/lib/app.py
- scripts/lib/printUsageMarkdown.py
- scripts/revpe_distcorr
- scripts/revpe_dwicombine
- update_doc
> Enable auto-documentation of scripts

- cmd/fod2fixel.cpp
- src/dwi/tractography/SIFT/model_base.h
Hopefully this fixes the issue raised in #255.
> FOD segmentation: Prevent hangs on Windows

- src/gui/gui.h
Avoids issues with decimal separators
> Set default locale to "C"

- cmd/dwi2tensor.cpp
I've added an option to `dwi2tensor` to output the predicted dwi signal; as per the user request and accompanying issue at #481 .
Another command `tensor2dwi` can always be added later on as well.  This is just a simple solution that will help the user; and in most use cases avoid juggling around a b=0 image, tensor image, and a gradient table (all required otherwise as input); and sometimes a kurtosis tensor image as well.
> dwi2tensor: added option to output predicted dwi signal

- cmd/5tt2gmwmi.cpp
These otherwise cause an exception if used in tckgen.
> 5tt2gmwmi: Prevent negative values

- scripts/labelsgmfix
This should have been included as part of #437.
> labelsgmfix: -sgm_amyg_hipp option

- src/dwi/bootstrap.h
- src/dwi/tractography/algorithms/tensor_prob.h
- src/dwi/tractography/tracking/exec.h
This code required updating to reflect changes to the linear image interpolator.
> tckgen -algorithm tensor_prob fix

- cmd/mrcalc.cpp
This arose from the same image being input multiple times to the one operation, which would make use of the list of already-opened images. However, in this case, `StackEntry::image_is_complex()` would remain uninitialized, which could by chance be non-zero; this in turn would make the output image complex, which could cause subsequent operations to fail if not compatible with complex data.
Closes #518.
> mrcalc: Fix 'operation not permitted' error

- lib/math/versor.h
- src/gui/dwi/render_frame.cpp
- src/gui/mrview/mode/base.cpp
- src/gui/mrview/mode/base.h
- src/gui/mrview/mode/lightbox.cpp
- src/gui/mrview/mode/slice.cpp
- src/gui/mrview/mode/slice.h
- src/gui/mrview/mode/volume.cpp
- src/gui/mrview/tool/connectome/edge.cpp
- src/gui/mrview/tool/odf/odf.cpp
- src/gui/mrview/tool/odf/odf.h
- src/gui/mrview/tool/screen_capture.cpp
- src/gui/opengl/transformation.h
> Fix lag in ODF preview

- cmd/sh2power.cpp
- testing/tests/sh2power
> Compute total SH power by default

- src/gui/dwi/renderer.cpp
- src/gui/mrview/tool/odf/item.cpp
- src/gui/mrview/tool/odf/odf.cpp
- src/gui/mrview/tool/odf/odf.h
- src/gui/mrview/tool/odf/preview.cpp
- src/gui/mrview/tool/odf/preview.h
> MRView: fix segfault when loading ODF image in ODF tool

- src/gui/mrview/tool/roi_editor/item.cpp
- src/gui/mrview/tool/roi_editor/roi.cpp
Reverts multi ROI selection (issue #162). See #372 for discussion. Also fixes assert failure due to not set min max values and changes ROI save dialogue box message and adds option to cancel closing of ROI.
> Mrview roi revert162

- src/gui/mrview/tool/roi_editor/roi.cpp
Closes #372.
Looks like that's all it was...
> mrview ROI tool: Fix hanging when commencing draw heavily off-axis

- cmd/mrtransform.cpp
> mrtransform: default output datatype is now float

- cmd/afdconnectivity.cpp
- cmd/tcksift2.cpp
- docs/getting_started/FAQ.rst
- docs/getting_started/commands/tcksift2.rst
- src/dwi/fixel_map.h
- src/dwi/tractography/SIFT/model.h
- src/dwi/tractography/SIFT/model_base.h
- src/dwi/tractography/SIFT/output.h
- src/dwi/tractography/SIFT/proc_mask.cpp
- src/dwi/tractography/SIFT2/tckfactor.cpp
- Update reference from doi to publication details.
- Throw exception if user tried to write the result to a .tck file.
- Add SIFT2 instructions to docs FAQ
> tcksift2: Tweaks

- docs/getting_started/FAQ.rst
- lib/apply.h
- scripts/lib/runCommand.py
- src/dwi/tractography/connectome/matrix.cpp
> Rob random fixes

- src/gui/dwi/renderer.cpp
Now display the tensor itself rather than mean particle displacement.
Closes #593.
> mrview: Altered tensor glyph rendering

- docs/getting_started/commands_list.rst
- docs/getting_started/scripts/dwiintensitynorm.rst
- docs/getting_started/scripts/population_template.rst
- scripts/dwiintensitynorm
- scripts/lib/runCommand.py
- scripts/population_template
Removed unnecessary commands in registration scripts to clean up docs. Fixed bug introduced in runCommand.
> Scripts fix run command

- src/dwi/tractography/algorithms/fact.h
> tckgen -algo fact: Fix angular constraint when set manually

- cmd/mrmetric.cpp
- lib/algo/threaded_loop.h
- lib/header.cpp
- lib/image.h
- lib/image_io/fetch_store.h
- lib/registration/nonlinear.h
- lib/registration/transform/search.h
- src/gui/mrview/gui_image.cpp
As discussed here: http://community.mrtrix.org/t/build-errors/210
There's also a couple of fixes to silence some of the warnings on clang.
> Fix push back headers in registration

- scripts/src/dwi2response/manual.py
- scripts/src/dwi2response/msmt_5tt.py
> dwi2response manual: Fix manual lmax setting

- lib/image_io/scratch.cpp
- lib/math/least_squares.h
- src/dwi/tractography/SIFT/model.h
- src/dwi/tractography/SIFT/sifter.cpp
- src/dwi/tractography/SIFT2/tckfactor.cpp
- src/dwi/tractography/mapping/writer.h
- src/stats/cfe.h
Promoting this so that hopefully it can attract a comment or two, if it just sits in #586 it'll go stale.
> Various checks during memory allocation

- build
- testing/cmd/testing_diff_data.cpp
- testing/cmd/testing_diff_dir.cpp
- testing/cmd/testing_diff_fixel.cpp
- testing/cmd/testing_diff_matrix.cpp
- testing/cmd/testing_diff_mesh.cpp
- testing/cmd/testing_diff_peaks.cpp
- testing/cmd/testing_diff_tck.cpp
- testing/cmd/testing_gen_data.cpp
Basically, this removes all the code that we had in the testing commands to allow testing against the old syntax. Hopefully this won't be required any more...?
> remove old syntax code from testing commands

- scripts/lib/app.py
- scripts/population_template
> Population template wildcard fix

- cmd/mrresize.cpp
@draffelt: does this look OK...?
> mrresize: remove redundant lines

- configure
Closes #655.
Unfortunately `mrregister` still doesn't compile in debug mode on Windows, but I don't think we're going to get around that one.
> Configure changes

- docs/generate_user_docs.sh
- docs/reference/scripts_list.rst
Hopefully this fixes the currently empty page for the scripts listing...
> Fix scripts list documentation

- docs/generate_user_docs.sh
- docs/reference/scripts/5ttgen.rst
- docs/reference/scripts/dwi2response.rst
- docs/reference/scripts/dwibiascorrect.rst
- docs/reference/scripts/dwiintensitynorm.rst
- docs/reference/scripts/dwipreproc.rst
- docs/reference/scripts/labelsgmfix.rst
- docs/reference/scripts/population_template.rst
- scripts/lib/cmdlineParser.py
More doc fixes: Need to stop sub-headings from appearing in the table of contents, and duplicate headers
> Further fixes to script documentation

- scripts/lib/cmdlineParser.py
Needed further clarification between those options that are purely flags, and those that receive some input argument (but no metavar is explicitly defined)
> Hopefully last tweaks to new script help pages

- testing/tests/dwi2fod
- testing/tests/dwidenoise
- reduce tolerance for dwidenoise
- add rudimentary tests for MSMT-CSD
> Testing additions

- scripts/lib/getUserPath.py
As reported [here](http://community.mrtrix.org/t/dwi2response-error/355/20).
> Scripts: Fix for working directory containing whitespace

- scripts/lib/getUserPath.py
> Scripts: Fix critical bug in getUserPath()

- docs/installation/mac_install.rst
As it is not or no more in the dependencies of qt5 or eigen.
> pkg-config added to brew install

- docs/reference/commands/mrclusterstats.rst
- src/dwi/gradient.cpp
Inspired by discussion [here](http://community.mrtrix.org/t/error-mrconvert-cannot-import-diffusion-gradient-table/363/2).
> bvecs/bvals import: Better error messages

- docs/tutorials/hcp_connectome.rst
Following report [here](http://community.mrtrix.org/t/problem-in-perfoming-msmt-constrained-spherical-deconvolution/376/1).
> Docs: Fix and update for HCP connectome tutorial

- scripts/dwipreproc
reverts dee7304 as mentioned in #753
> dwipreproc: check output gradient files

- scripts/lib/app.py
- scripts/lib/cmdlineParser.py
- scripts/lib/errorMessage.py
- scripts/lib/getHeaderInfo.py
- scripts/lib/runCommand.py
> Scripts keeponerror #752

- cmd/dwi2mask.cpp
- cmd/maskfilter.cpp
- docs/reference/commands/dwi2mask.rst
- docs/reference/commands/maskfilter.rst
- lib/filter/mask_clean.h
Implementation of a strategy akin to that shown in #615 .
> New mask cleaning filter

- lib/header.cpp
- lib/image.h
Following comment [here](http://community.mrtrix.org/t/mrconvert-error-unknown-format-for-image-home-output-template-wm-mask/424/3).
Any complaints?
> More verbose error for unknown image format on creation

- scripts/average_response
Not very pythonic I'm sure. But does the job without requiring numpy
> updated averageresponse script to handle multishell response functions

- cmd/mrconvert.cpp
check if maximum coordinate position is within range
> mrconvert: fix segfault for out of range coord

- cmd/mrconvert.cpp
non-negativeity test for mrconvert -coord: (related to #789)
> Mrconvert coord non-negativity test

- cmd/mrmath.cpp
> mrmath: fix bug in handling of cross-image operations

- scripts/lib/getAlgorithmList.py
http://community.mrtrix.org/t/5ttgen-error-on-mac/540
> Allow 5ttgen to resolve symbolic links necessary for homebrew

- lib/stride.cpp
- lib/stride.h
> Fix stride sanitisation when image contains singleton axes

- configure
> configure: add '-mno-avx' option to default CFLAGS

- cmd/mrtransform.cpp
- scripts/src/dwi2response/tax.py
Rotate "directions" key/value entry just as is already done for the diffusion gradient table.
Handles 2 column (az/el) and 3 column (x/y/z) data.
Just need to finish generating my test data.
> Mrtransform directions

- package_mrtrix
Updated package_mrtrix to the new release/bin folder structure. Discussion in #834
> Package mrtrix update #834

- testing/tests/fod2dec
It was about time I looked into this. :v:
> fod2dec tests

- testing/README.md
As discussed in #841, and addressing #693.
> testing README: updated to clarify the process of adding data

- cmd/mrcalc.cpp
> Update docs for mrcalc.

- src/gui/mrview/window.cpp
- src/gui/mrview/window.h
Added "go to volume..." entry in the image menu. issue: #848
> mrview: go to volume slot #848

- lib/header.cpp
Give info message if specified stride order is not supported by output file as discussed in #803.
> Info on stride mismatch

- docs/getting_started/image_data.rst
> docs: fix error in strides explanation

- scripts/gen_scheme
As requested in e.g. [this thread](http://community.mrtrix.org/t/troubles-with-tractography-on-7t-diffusion-data/616/12?u=jdtournier)
> add gen_scheme script

- cmd/labelconvert.cpp
> labelconvert: Fix segfault on negative value input

- lib/file/nifti1.h
> remove MRtrix3 copyright notice from lib/file/nifti1.h

- cmd/mrview.cpp
- src/gui/dialog/dicom.cpp
- src/gui/dialog/file.cpp
- src/gui/dialog/progress.cpp
- src/gui/gui.cpp
- src/gui/gui.h
- src/gui/mrview/window.cpp
- src/gui/mrview/window.h
> MRView: process command-line options after loading images

- scripts/labelsgmfix
> labelsgmfix: Fix -force option

- src/gui/mrview/window.cpp
issue #905
allows multiple occurrences `mrview 1.mif -image 1 -image 0`
> mrview: boolean -imagevisible option 

- lib/file/mmap.cpp
As discussed on the community forum:
http://community.mrtrix.org/t/mrtrix-mmap-gpfs-issue/710?u=jdtournier
> File::MMap: add GPFS to the list of network filesystems

- cmd/mrconvert.cpp
This has been a while coming... Should help with issues such as [anonymisation](http://community.mrtrix.org/t/anonymise-nifti/773?u=jdtournier).
> mrconvert: add options to modify generic header entries

- docs/getting_started/troubleshooting.rst
related to http://community.mrtrix.org/t/trouble-with-mrtrix3-and-mrtrix2/790/4
> troubleshooting: dirty page handling

- docs/getting_started/troubleshooting.rst
Warn about nonpersistent changes
> troubleshoot_dirty_pages_nonpersistent

- cmd/mrinfo.cpp
printing multiple header entries via `-property` can be confusing as to which line belongs to which entry. So I've changed mrinfo to write the key to stderr and indent according to the length of the key. The downside is that when stdout is redirected but not stderr, this writes whitespaces and newlines to stderr. Printing to stderr  can be deactivated with `-quiet`.
I found it useful but not sure if you like it. Feel free to ditch it!
```
mrinfo dwi.mif -property prior_dw_scheme  -property normalisation_scale_factor
prior_dw_scheme: 0.01986599705,0.4115229389,0.9111828647,0
-0.3703421358,-0.3132067544,0.8744988459,2600
-0.7907743375,0.3971774229,0.4657531985,1000
0.2141400482,0.9015290358,0.3760178684,400
...
-0.2827501725,-0.4725152915,-0.8347344723,2600 …
```
> mrinfo: -property: print key and indentation to stderr unless -quiet

- bin/dwigradcheck
Changed 'number' to 'select' to make script compatible with new tckgen-command.
> Update to new tckgen option select

- cmd/tckconvert.cpp
- docs/reference/commands/dwinormalise.rst
- docs/reference/commands/mrconvert.rst
- docs/reference/commands/mrview.rst
- docs/reference/commands/tckconvert.rst
- docs/reference/commands/tcksift2.rst
- docs/reference/commands_list.rst
> tckconvert: update documentation for ascii handling, and add checks for output file

- bin/dwipreproc
To address http://community.mrtrix.org/t/issue-with-epi-correction/887
> Allow custom topup options as well

- core/file/dicom/element.cpp
- core/file/dicom/element.h
- core/file/dicom/image.h
- core/file/dicom/mapper.cpp
- core/file/dicom/quick_scan.cpp
- core/file/dicom/quick_scan.h
- core/file/dicom/tree.cpp
- docs/constrained_spherical_deconvolution/lmax.rst
- docs/dwi_preprocessing/dwipreproc.rst
- docs/fixel_based_analysis/common_fba_steps/dwipreproc.rst
- docs/fixel_based_analysis/common_fba_steps/population_template2.rst
- docs/fixel_based_analysis/mt_fibre_density_cross-section.rst
- docs/fixel_based_analysis/ss_fibre_density_cross-section.rst
- docs/getting_started/beginner_dwi_tutorial.rst
- docs/getting_started/image_data.rst
- docs/index.rst
- docs/installation/before_install.rst
- docs/installation/hpc_clusters_install.rst
- docs/installation/windows_install.rst
- docs/quantitative_structural_connectivity/act.rst
- docs/quantitative_structural_connectivity/connectome_tool.rst
- docs/tips_and_tricks/batch_processing_with_foreach.rst
- docs/tips_and_tricks/dicom_handling.rst
- docs/troubleshooting/FAQ.rst
- docs/troubleshooting/dicom_handling.rst
- docs/troubleshooting/hanging_or_crashing.rst
> Better reporting for unsupported dicom transfer syntax

- src/registration/nonlinear.cpp
minor tweak to argument description of default values
> mrregister: clarify smoothing default values

- docs/reference/commands/mrregister.rst
- docs/reference/commands/tckglobal.rst
Keeping things up to date.  mtbin changes one of these days may introduce a series of other changes, including to the FBA workflows.
> docs update

- cmd/mtbin.cpp
- docs/fixel_based_analysis/mt_fibre_density_cross-section.rst
- docs/reference/commands/mtbin.rst
- docs/reference/commands/tckglobal.rst
A series of fixes to deal with most foreseeable issues related to #1000.  The `-mask` option is now also mandatory for `mtbin`.
> Mtbin fixes

- bin/dwipreproc
> dwipreproc: Fix variable naming error

- cmd/mrconvert.cpp
> mrconvert: -axes option now also swaps voxel sizes as expected

- cmd/amp2response.cpp
- cmd/tckconvert.cpp
- docs/dwi_preprocessing/dwipreproc.rst
- docs/reference/commands/amp2response.rst
- docs/reference/commands/tckconvert.rst
Little addition to `app.debug()` in the Python libraries to give better localisation of where the information is coming from. Came in handy during my own debugging so thought I'd push it.
Needs testing across OS's and Python versions.
> app.debug(): Enhance

- cmd/fixelcrop.cpp
- lib/mrtrix3/app.py
As reported [here](http://community.mrtrix.org/t/how-to-restrict-fixelcfestats-to-subset-of-tracts/845/7).
> Fixelcrop fix

- cmd/tckconvert.cpp
- docs/reference/commands/tckconvert.rst
> tckconvert: add Daniel Blezek to the authors list

- matlab/write_mrtrix.m
as discussed on #1005. 
Just thought I'd polish that off...
> write_mrtrix: update to output generic fields

- src/dwi/sdeconv/msmt_csd.h
This should address issue #1081
> Handle shell selection when using msmt_csd

- cmd/mrview.cpp
- docs/reference/commands/mrview.rst
Just noticed this burning injustice, and had to do something about it...
> mrview: add Rami Tabbara in AUTHOR entry

- src/gui/mrview/tool/roi_editor/roi.cpp
This fixes #1109. Replaces PR #1111 to merge to master instead of dev.
> mrview: roi save QMessageBox: overwrite standard buttons for qt4 compatibility master

- core/image_diff.h
As discussed in #1107.
This is take 2 - see original in #1114.
> fix const-qualifier issue in image_diff.h

- .travis.yml
- Doxyfile
- core/file/config.cpp
- core/image_diff.h
- lib/mrtrix3/app.py
- src/gui/mrview/tool/roi_editor/roi.cpp
This will need to be done from time to time - see discussion on #1120...
> Update dev from master

- core/file/utils.h
- docs/reference/config_file_options.rst
As raised on forum [here](http://community.mrtrix.org/t/mrcalc-error-error-converting-string/506/5).
> TmpFileDir: Fix description of behaviour

- build
This can lead to strangeness in testing otherwise.
> build: switch to core active config if module config differs

- core/file/dicom/csa_entry.h
- core/file/dicom/element.cpp
- core/file/dicom/element.h
- core/file/dicom/image.cpp
- core/file/dicom/image.h
- core/file/dicom/quick_scan.cpp
To fix [this issue](http://community.mrtrix.org/t/segmentation-fault/1321?u=jdtournier), mentioned on the forum.
> DICOM: better handling of empty fields

- core/file/dicom/image.cpp
Just noticed a minor screw up - better fix it ASAP. All checks out on testing.
> DICOM: fix bug introduced in previous commits

- .travis.yml
- bin/population_template
I can't remember why I had the python version dependent write mode in there...
Fixes http://community.mrtrix.org/t/error-when-run-the-dwiintensitynorm/1340
> population_template: python 3 & no numpy fix

- .travis.yml
- cmd/mrcalc.cpp
- core/file/nifti1_utils.cpp
- core/file/nifti2_utils.cpp
- core/image_diff.h
- core/image_helpers.h
> mrcalc: increase tolerance on transform match test

- cmd/sh2power.cpp
- cmd/shbasis.cpp
- core/math/SH.h
- src/dwi/sdeconv/csd.h
- src/gui/dwi/renderer.cpp
As discussed in #1206 - opinions welcome.
> remove support for the non-orthonormal SH basis

- src/gui/mrview/tool/roi_editor/item.h
Partially addresses #1202. Thanks @LeeReidCSIRO for the report.
> mrview ROI tool: Fix near-black colour selection

- cmd/amp2response.cpp
- docs/reference/commands/amp2response.rst
Can no longer find the discussion where this was raised though :-/
> amp2response: Move reference from 'description' section

- cmd/sh2peaks.cpp
- core/math/SH.h
- docs/reference/commands/sh2peaks.rst
- testing/tests/sh2peaks
Reverts MRtrix3/mrtrix3#1206
Happy holidays all.  Just quickly chipping in to mention we had not agreed on merging this: there are several outstanding issues in this one, raised a couple of times by me, that have to be addressed first.  I've said I'll look into those thresholds when I'm back, next week that is.  We've delayed pull requests for much longer, and for much lesser reasons in the past too; I reckon this can wait until addressed properly.  I personally insist on it.  Thanks.
> Revert "fix SH precomputer"

- src/connectome/lut.cpp
Encouraged most recently by [this forum thread](http://community.mrtrix.org/t/labelconvert-and-connectome-visualisation/1408), though others have encountered similar difficulties in the past.
> Connectome LUT: Better error message on read failure

- configure
- core/file/dicom/mapper.cpp
- src/dwi/tractography/mapping/mapper_plugins.cpp
> Configure remove linker optimisation flags

- core/axes.cpp
- core/axes.h
- core/file/json_utils.cpp
- core/header.cpp
Arose from [review](https://github.com/MRtrix3/mrtrix3/pull/1244#pullrequestreview-93962779) in #1244. I think this should be more correct...
> Slightly alter image transform to RAS

- .travis.yml
- build
- configure
This adds an option to `build` to keep re-trying a build upon failure, until no new jobs succeed. This is to try to speed up the build on TravisCI whilst making it resilient to out of memory errors. Please treat this as an experiment at this stage...
> Persistent build mode

- .travis.yml
Just like #1181, this will likely require a lot of tinkering, and requires a PR to figure out what works and what doesn't.
While they give some [documentation](https://docs.travis-ci.com/user/multi-os/) describing how to branch for conditional installation / execution, I haven't found anything describing how to branch in the `addons:` section. So I'm expecting that to fail spectacularly at first try for OSX. But maybe it'll give me some hints on how to fix it...
Trying to avoid issues like #1246. Idea of OSX testing initially raised in #1181.
> TravisCI: Try to add OSX test

- lib/mrtrix3/app.py
- lib/mrtrix3/run.py
Don't use this functionality all too often these days (hopefully because the scripts are crashing halfway through less often...), so didn't encounter this until now.
> Scripts: Fix -continue option

- src/connectome/lut.cpp
Related to #1279, and a bunch of other communications with people trying to define their own lookup tables.
> Connectome LUT: Better parsing

- docs/reference/commands/mrview.rst
- src/gui/mrview/colourmap_button.cpp
- src/gui/mrview/colourmap_button.h
- src/gui/mrview/tool/overlay.cpp
- src/gui/mrview/tool/roi_editor/roi.cpp
- src/gui/mrview/tool/tractography/tractography.cpp
- src/gui/mrview/window.cpp
Needed to implement a couple of these to achieve what I wanted in #1228 (examining tractography thresholds), so decided to cover off a few outstanding requests from #1132 (`mrview` command-line options) while I was at it.
> mrview: Add some more command-line options

- cmd/mrcalc.cpp
- core/types.h
- src/dwi/tractography/seeding/dynamic.h
- src/gui/mrview/mode/volume.cpp
- src/gui/mrview/tool/overlay.cpp
- src/gui/opengl/gl.h
Details & links in commit message.
Closes #1247.
> Fix compiler warnings

- .travis.yml
- cmd/tckconvert.cpp
- lib/mrtrix3/run.py
- src/dwi/tractography/mapping/writer.h
- testing/tests/tckconvert
In addition to resolving merge conflicts, the merge commit also includes updating `cmd/tckconvert.cpp` according to the changes introduced in #984: Track format writer classes are forbidden from throwing exceptions within their destructors.
> Final master -> dev update for 3.0_RC3

- cmd/tckstats.cpp
- src/dwi/tractography/editing/receiver.cpp
As reported in #1322.
Also fixes an issue with #1259 that I came across along the way...
> tckstats: Fix for empty track file

- src/dwi/tractography/ACT/gmwmi.cpp
- src/dwi/tractography/ACT/gmwmi.h
- src/gui/mrview/tool/connectome/connectome.cpp
- src/gui/mrview/tool/connectome/connectome.h
- src/gui/mrview/tool/connectome/types.h
See commit message for f0ef4d6.
Also cherry-picked commit 3b93cf20 from branch `mrview_connectome_tool_ui_fix` so that it can be cleared & deleted; that fix is to do with a pretty esoteric feature, so no surprise that nobody has come across it.
> mrview Connectome tool: Edge visibility by nodes change

- cmd/mrview.cpp
- core/app.cpp
- src/gui/gui.cpp
- src/gui/gui.h
> fix locale handling in GUI applications

- build
- testing/tests/mrhistmatch
Address issues with buffering of stdout contents as described in #1345.
> build: Only use stderr

- docs/fixel_based_analysis/common_fba_steps/sift.rst
Thanks to a collaborator with a keen eye for details. :smile: :relieved:
> FBA docs typo fix

- core/algo/random_threaded_loop.h
- core/algo/stochastic_threaded_loop.h
- core/algo/threaded_loop.h
- core/file/nifti1_utils.cpp
- core/file/nifti2_utils.cpp
- core/header.cpp
- core/image_diff.h
- core/thread.h
Follows on from discussion on #1318
> Nifti cleanup

- bin/dwipreproc
- lib/mrtrix3/file.py
Had this floating in a feature branch. Should also check to see whether it can simplify the use of this function in existing scripts.
> mrtrix3.file.delTemporary(): Compatibility with list input

- bin/dwiintensitynorm
- docs/reference/scripts/dwiintensitynorm.rst
addresses #1408 (raised via PM by a user in the forum)
> dwiintensitynorm description: requires grad scheme

- core/file/dicom/definitions.h
- core/file/dicom/element.cpp
- core/file/utils.h
- core/mrtrix.h
- docs/format_config_options
- docs/quantitative_structural_connectivity/labelconvert_tutorial.rst
- docs/reference/config_file_options.rst
- docs/troubleshooting/display_issues.rst
- docs/troubleshooting/performance_and_crashes.rst
- src/gui/mrview/volume.h
Clean version cherry-picked from #1395, based on current `master`.
> Links to config options take 2

- cmd/mrconvert.cpp
- docs/getting_started/command_line.rst
- docs/reference/commands/mrconvert.rst
> mrconvert update doc

- cmd/mrdegibbs.cpp
- docs/reference/commands/mrdegibbs.rst
- docs/reference/config_file_options.rst
popped up here: http://community.mrtrix.org/t/mrtrix-tutorial-available-on-osf/1942/3
> mrdegibbs: disambiguate pronoun

- lib/mrtrix3/image.py
Addendum to #1423 to fix a typo.
> Fix bug json.load() -> json.loads()

- .travis.yml
- bin/dwipreproc
- core/file/dicom/mapper.cpp
- lib/mrtrix3/_5ttgen/gif.py
- lib/mrtrix3/fsl.py
- lib/mrtrix3/image.py
- run_pylint
- src/dwi/tractography/streamline.h
- src/gui/mrview/tool/screen_capture.cpp
In particular need to bring the change in commit d2c27797 made within #1509 into `dev` in order for CI to pass.
> Hotfix to dev

- bin/5ttgen
Fix bug introduced in #1344 (see commit message).
> 5ttgen: 5ttcheck fix

- matlab/read_mrtrix_tsf.m
- matlab/write_mrtrix_tsf.m
@Lestropie, I finally got around to sharing the .m files I wrote for reading and writing the mrtrix .tsf files in matlab. They have already come in handy! 
Thanks, 
Emilie
> read and write tsf .m files

- core/file/dicom/element.cpp
- core/file/dicom/element.h
> DICOM: Downgrade message on invalid conversion to string

- core/math/math.h
> Revise exceptions in matrix data import

- src/gui/mrview/tool/tractography/tractogram.cpp
Discovered in testing of #1566.
Not consequential over and above leading to erroneous failures when compiled with assertions enabled.
> mrview Tractography tool: Fix assertion on TSF load

- core/file/dicom/mapper.cpp
Playing with a project involving T2 relaxometry, and it was annoying me that I couldn't just see the echo times using `mrinfo`. This just concatenates unique values across frames for echo time, flip angle & repetition time.
Technically I think this should also work if such values vary not just between volumes but also between slices (as long as such is reflected in the DICOM headers).
> DICOM: Variable parameters

- cmd/amp2sh.cpp
- core/header.h
- core/image_io/default.h
- core/image_io/variable_scaling.h
- core/transform.h
- docs/reference/commands/amp2sh.rst
As discussed on http://community.mrtrix.org/t/question-about-amp2sh/2398
> amp2sh: allow cartesian directions

- cmd/connectome2tck.cpp
- cmd/mrcat.cpp
- cmd/mrtransform.cpp
- core/bitset.cpp
- core/command.h
- core/formats/mrtrix_utils.h
- core/header.cpp
- core/image_io/default.cpp
- src/gui/mrview/mode/lightbox.cpp
- src/gui/mrview/mode/lightbox.h
- src/gui/mrview/tool/tractography/tractogram.cpp
- testing/tests/mrconvert
In particular need #1619 in order to further test #1618.
> Master to dev

- cmd/mrmetric.cpp
- core/adapter/permute_axes.h
- docs/reference/commands/mrmetric.rst
- src/gui/mrview/tool/view.cpp
- src/gui/mrview/tool/view.h
- src/gui/mrview/window.cpp
- src/gui/mrview/window.h
- src/gui/opengl/font.cpp
- src/gui/projection.h
- src/registration/metric/thread_kernel.h
- testing/tests/mrconvert
> mrview fix volume group navigation

- .travis.yml
- configure
- core/file/nifti2_utils.cpp
- src/gui/crosshair.cpp
- src/gui/crosshair.h
- src/gui/dwi/renderer.h
- src/gui/mrview/colourmap.h
- src/gui/mrview/displayable.h
- src/gui/opengl/font.h
- src/gui/opengl/shader.h
- src/gui/opengl/transformation.h
- src/gui/projection.cpp
- src/gui/projection.h
- src/surface/mesh.cpp
Cherry-picking commits from #1642.
Given TravisCI failures will preclude any bug fixes from being merged to `master`, I think the preferable approach in such a circumstance is:
1. Get CI working on `master`;
2. Merge latest updates on `master` into `dev`;
3. Pull requests merging into `dev` remain focused on the issue at hand and don't get conflated with CI experimentation / fixes.
4. Add a "`CI`" label in GitHub so that issues / PRs specific to continuous integration are flagged as such, and e.g. can be ignored when generating changelogs.
> Resolve with latest TravisCI updates

- src/gui/mrview/tool/view.cpp
- src/gui/mrview/tool/view.h
> mrview: fix bug introduced in #1638

- core/file/utils.h
Addresses #842. 
Turns out it's a simple matter of deleting the file rather than opening with `O_TRUNC`. If the file is already opened, the kernel ensures it remains usable by processes that hold its file descriptor.
This may not work on Windows since it tends not to allow deletion of open files (I've yet to test this). But while this doesn't allow writing to one of the inputs, it should at least catch and prevent users from doing so inadvertently, so that should still be a good thing...
> Allow command inputs to be overwritten safely

- cmd/tcksample.cpp
The diff of #1586 contained some changes in `tcksample` that appear to be unrelated to the proposed changes to the `ProgressBar`. So I've split the relevant commit in two such that each can be assessed independently.
This appears to just be removing some unnecessary class inheritance & `MR::copy_ptr` usage.
> tcksample: TDI data handling

- cmd/transformcalc.cpp
- docs/reference/commands/transformcalc.rst
- src/gui/mrview/tool/view.cpp
* fixed transformcalc align_vertices_rigid
* added align_vertices_rigid_scale
* modified output of `mrview --> view tool --> copy` to match format of plain text matrices
> linear transformation from sets of scanner coordinates

- bin/dwicat
Error in resolving divergence between #1626 and #1449.
> dwicat: Fix for updated Python API

- cmd/mrcalc.cpp
- docs/reference/commands/mrcalc.rst
Mostly needed to add the `-polar` option to support some local data manipulation; but tweaked a few other things while I was in there (description in 0cadc52).
> mrcalc: Updates to complex data handling

- bin/foreach
> foreach: Use threading rather than multiprocessing module

- cmd/connectome2tck.cpp
- src/dwi/tractography/connectome/matrix.cpp
- src/dwi/tractography/file.h
Couple of gotchas after #1603, particularly necessary to get SIFT2 working.
> Updates for compatibility with #1603

- build
> build: fix Python decode error on Windows

- src/dwi/gradient.cpp
> dwi2mask: Fix segfault with -fslgrad

- cmd/mrtransform.cpp
- docs/reference/commands/mrtransform.rst
As [discussed on forum](https://community.mrtrix.org/t/transform-gradients/2899/2?u=jdtournier).
> mrtransform export grad

- lib/mrtrix3/matrix.py
Spotted glitchy header & footer in [this comment](https://github.com/MRtrix3/mrtrix3/issues/1773#issuecomment-544888447) in #1773, so took a closer look and polished the behaviour up a little.
> matrix.save_numeric(): Improve header/footer formatting

- lib/mrtrix3/matrix.py
Took a lot more effort to diagnose than it should have; very indirect way of eventually leading to the empirical observations I made. 
Divergence traces back to #1603.
Closes #1786.
> matrix.save_transform(): Boost precision

- docs/generate_user_docs.sh
> generate_user_docs.sh macOS compatible 

- configure
remove miniconda from PATH to avoid issues like #1577
> configure: also remove miniconda from path

- src/gui/mrview/window.cpp
> Mrview: insert images after current

- configure
> configure: update flags for static linking

- cmd/dirflip.cpp
- cmd/dirsplit.cpp
Details in af51eef.
#1794 has multiple implications, as it turns out...
> dirflip and dirsplit: Fix command-line option parsing

- lib/mrtrix3/app.py
Silly mistake in Python progress bar.
> mrtrix3.app.ProgressBar: Fix line wrapping on construction

- lib/mrtrix3/app.py
Another minor issue with the new Python API arising in rare circumstances.
> app.execute() Fix erroneous error message

- set_path
Fixes setting path on default Catalina install
> Support setting the path on a default Catalina install

- core/version.h
since tags don't get pushed by default...
> update instructions for pushing out version changes

- configure
as discussed on #1851 
Required a bit more work than previously to be completely safe in a conda environment...
> configure: add -conda flag

- src/gui/lighting_dock.cpp
Fixing:
https://github.com/MRtrix3/mrtrix3/runs/362175568
> Fix unused variable compiler warning

- core/dwi/gradient.cpp
- core/dwi/gradient.h
- core/header.cpp
- core/phase_encoding.cpp
> Header::create(): Don't read 4D schemes from cmdline options

- src/gui/mrview/adjust_button.h
- src/gui/mrview/tool/base.h
- src/gui/mrview/tool/overlay.cpp
- src/gui/mrview/window.cpp
- fixes opening a tool deactivating keyboard shortcuts on macos #1641 
- merge latest updates on master
> mrview keyboard shortcut fix

- src/gui/dialog/file.cpp
- src/gui/dialog/file.h
- src/gui/mrview/tool/base.h
- src/gui/mrview/tool/connectome/connectome.cpp
- src/gui/mrview/tool/fixel/fixel.cpp
- src/gui/mrview/tool/list_model_base.h
- src/gui/mrview/tool/odf/odf.cpp
- src/gui/mrview/tool/overlay.cpp
- src/gui/mrview/tool/roi_editor/roi.cpp
- src/gui/mrview/tool/screen_capture.cpp
- src/gui/mrview/tool/screen_capture.h
- src/gui/mrview/tool/tractography/track_scalar_file.cpp
- src/gui/mrview/tool/tractography/track_scalar_file.h
- src/gui/mrview/tool/tractography/tractography.cpp
- src/gui/mrview/tool/tractography/tractography.h
- src/gui/mrview/window.cpp
- src/gui/mrview/window.h
> MRView: better filename elision in List Views

- cmd/tckedit.cpp
- cmd/tckgen.cpp
- cmd/tckresample.cpp
- cmd/tckstats.cpp
- src/dwi/tractography/connectome/extract.cpp
- src/dwi/tractography/editing/worker.cpp
- src/dwi/tractography/mapping/mapping.cpp
- src/dwi/tractography/properties.cpp
- src/dwi/tractography/properties.h
- src/dwi/tractography/roi.h
- src/gui/mrview/tool/tractography/tractogram.cpp
Detail in commit message of 920b4270.
Closes #1855.
Solutions beyond issuing a warning will be directed to a new Issue.
**EDIT**: Such an issue already exists (#1450).
> tckgen & tckedit: Warn if streamlines may skip ROIs

- .github/workflows/package-macos-native.yml
- .github/workflows/package-windows-msys2.yml
- core/version.h
Adds the final GitHub workflow for @bjeurissen's native macOS package. 
Seems to check out OK on my personal fork, but we'll need to wait until we create a release to double-check that everything works properly. :crossed_fingers:
> Macos native build workflow

- lib/mrtrix3/fsl.py
> fsl.check_first(): Disable cleanup on failure

- cmd/mtnormalise.cpp
> mtnormalise: Check mask dimensionality

- cmd/connectomeedit.cpp
Just reducing some of the code in #1725.
> connectomeedit: Compress code

- cmd/5ttcheck.cpp
- docs/reference/commands/5ttcheck.rst
> 5ttcheck: Alter PVF check

- lib/mrtrix3/app.py
- lib/mrtrix3/fsl.py
- lib/mrtrix3/run.py
Explanations in commit messages.
> Python API minor fixes

- configure
> configure: fix Makefile.release not found error

- lib/mrtrix3/matrix.py
- lib/mrtrix3/phaseencoding.py
- lib/mrtrix3/run.py
Just a couple of very minor tweaks to the Python API.
> Script tweaks

- src/gui/dialog/dicom.cpp
- src/gui/dialog/file.cpp
- src/gui/dialog/list.h
- src/gui/dialog/progress.cpp
- src/gui/dialog/report_exception.cpp
- src/gui/dwi/render_frame.cpp
- src/gui/gui.h
- src/gui/lighting_dock.cpp
- src/gui/mrview/colourmap_button.cpp
- src/gui/mrview/colourmap_menu.cpp
- src/gui/mrview/tool/connectome/file_data_vector.cpp
- src/gui/mrview/tool/connectome/file_data_vector.h
- src/gui/mrview/tool/connectome/matrix_list.h
- src/gui/mrview/tool/connectome/node_list.cpp
- src/gui/mrview/tool/connectome/selection.cpp
- src/gui/mrview/tool/fixel/base_fixel.h
- src/gui/mrview/tool/list_model_base.h
- src/gui/mrview/tool/odf/model.h
- src/gui/mrview/tool/overlay.cpp
- src/gui/mrview/tool/roi_editor/roi.cpp
- src/gui/mrview/tool/screen_capture.cpp
- src/gui/mrview/tool/tractography/track_scalar_file.cpp
- src/gui/mrview/tool/view.cpp
- src/gui/mrview/window.cpp
- src/gui/mrview/window.h
- src/gui/projection.h
- src/gui/shview/render_window.cpp
Should fix issues identified while trying to use mrview on Brazilian systems...
> mrview: better handling of UTF-8 encodings

- cmd/mrregister.cpp
- core/math/average_space.cpp
- core/math/gradient_descent_bb.h
- src/registration/linear.cpp
- src/registration/linear.h
- fix to mrregister's command line interface of linear stage settings
- fix invalid transformation for BB gradient descent for identical images (zero gradient, no iterations)
- average_space calculation: check for NaN in transformations
> mrregister linear registration-related bugfixes

- core/file/json_utils.cpp
Seems in the joyous exercise of #1843 (specifically a2c3ba1) I managed to forget what the purpose of the BIDS field "`IntendedFor`" actually is...
> JSON: Do not read / write "IntendedFor field

- bin/population_template
- bin/responsemean
- lib/mrtrix3/matrix.py
Closes #1967.
Used solution from [here](https://bugs.python.org/issue29214#msg285046).
> matrix.save_numeric(): Fix enforcement of -force option

- bin/population_template
- lib/mrtrix3/run.py
Couple of very minor fixes to terminal feedback in scripts.
Minor fixes to #1902 and #1957.
> Scripts terminal fixes

- core/file/dicom/mapper.cpp
Old JSON:
```
"SliceTiming": "0 1.30499995 0.129999995 1.43499994 0.25999999 1.5675 0.392500013 1.69749999 0.522499979 1.82749999 0.652499974 1.95749998 0.782500029 2.0875001 0.915000021 2.22000003 1.04499996 2.3499999 1.17499995 0 1.30499995 0.129999995 1.43499994 0.25999999 1.5675 0.392500013 1.69749999 0.522499979 1.82749999 0.652499974 1.95749998 0.782500029 2.0875001 0.915000021 2.22000003 1.04499996 2.3499999 1.17499995 0 1.30499995 0.129999995 1.43499994 0.25999999 1.5675 0.392500013 1.69749999 0.522499979 1.82749999 0.652499974 1.95749998 0.782500029 2.0875001 0.915000021 2.22000003 1.04499996 2.3499999 1.17499995 0 1.30499995 0.129999995 1.43499994 0.25999999 1.5675 0.392500013 1.69749999 0.522499979 1.82749999 0.652499974 1.95749998 0.782500029 2.0875001 0.915000021 2.22000003 …
```
> Improved slice timing on Siemens

- configure
as [reported on the forum](https://community.mrtrix.org/t/configure-error-seems-qt-problem/3306/6?u=jdtournier).
> Fix configure qt error on msys2

- bin/dwifslpreproc
Erroneous merge in #1937 failed to account for parallel changes in Python API (#1449).
> dwifslpreproc merge fix

- cmd/dcminfo.cpp
- core/file/dicom/csa_entry.h
- core/file/dicom/image.cpp
- core/file/dicom/image.h
- core/file/dicom/mapper.cpp
- core/file/dicom/quick_scan.cpp
- core/file/dicom/quick_scan.h
- core/phase_encoding.cpp
- core/phase_encoding.h
- docs/reference/commands/dcminfo.rst
Back-end changes necessary to support some work I'm doing locally. Details in 3a9ff73 commit message.
@jdtournier: Please make sure this doesn't bork your DICOM test suite.
> DICOM import & dcminfo: Enhancements

- core/file/dicom/element.cpp
> DICOM: don't substitute caret symbols with spaces

- cmd/mrinfo.cpp
- core/exception.h
- core/file/dicom/select_cmdline.cpp
- core/header.cpp
- src/gui/dialog/dicom.cpp
- src/gui/mrview/window.cpp
> DICOM selector quit aborts cleanly

- cmd/tckconvert.cpp
- cmd/tcksample.cpp
- core/file/dicom/select_cmdline.cpp
- core/formats/mrtrix_utils.h
- src/dwi/tractography/file_base.h
- src/surface/algo/mesh2image.cpp
see individual commits for details.
> Minor fixes

- core/dwi/gradient.cpp
Whoops... explanation in af7c979. Fix to #2015.
> dw_scheme: Fix command-line import

- matlab/read_mrtrix.m
- matlab/write_mrtrix.m
This should fix #2126. See commit message in 71696f3e for details.
> Fix matlab write mrtrix

- core/file/nifti_utils.cpp
Fairly obvious error missed in code review.
> NIfTI2: Fix read following #1540

- bin/convert_bruker
> convert_bruker: fix DW scheme handling

- cmd/mrhistmatch.cpp
Proposing to squeeze into `3.0.2` given that the `dwicat` script fails on the BATMAN tutorial data.
> mrhistmatch: Use normal equation

- core/version.h
- docs/reference/commands/amp2sh.rst
- docs/reference/commands/dwi2fod.rst
- docs/reference/commands/fixel2sh.rst
- docs/reference/commands/sh2amp.rst
- docs/reference/commands/sh2peaks.rst
- docs/reference/commands/sh2power.rst
- docs/reference/commands/sh2response.rst
- docs/reference/commands/shbasis.rst
- docs/reference/commands/shconv.rst
- run_tests
**Not for manual merging**
Note that this includes one final minor fix to `./run_tests` in c60cd26b1
@Lestropie: let me know when you're ready to push this out!
> 3.0.2 release for final CI testing

- .github/workflows/checks.yml
Need to fix CI for macOS - see discussion on #2208
> GitHub workflow: fix homebrew setup in macOS checks

- cmd/mrtransform.cpp
As [suggested on forum](https://community.mrtrix.org/t/feature-request-mrtransform/4198).
Need to make sure that fix is compatible with the logic flow and doesn't bork any possible use cases I'm not seeing.
> mrtransform: Throw exception on no operation

- cmd/dwidenoise.cpp
Just the changes I made locally testing to see if there was an Eigen memory leak.
Probably doesn't actually make any difference the way memory allocation occurs, but is perhaps nevertheless neater given that these variables are of the same size every functor invocation.
> dwidenoise: Avoid memory reallocation

- .github/workflows/checks.yml
- docs/concepts/dw_scheme.rst
- docs/getting_started/config.rst
- docs/quantitative_structural_connectivity/connectome_tool.rst
As prompted by [forum question](https://community.mrtrix.org/t/question-about-b-values-and-its-fitness-to-the-software/4156).
Given the centrality of the shell interpretation of DW volumes, I think it warrants a reasonable amount of explanation.
> Docs: DW handling: Describe shells

- core/file/dicom/image.cpp
Tweaks based on assessing data provided as a consequence of [this forum thread](https://community.mrtrix.org/t/dwifslpreproc-error-b-value-must-be-non-negative/4308).
Details in cf83f19.
While the negative *b*-value one is reasonably trivial, I'm not 100% on the sequence numbering change. In the case of these data, the frame (?) named "`ep_b-16383`" was being allocated as sequence number +16383, while "`ep_b1000#1`" - "`ep_b1000#12`" were allocated the expected sequence numbers. My guess is that the relevant code was *intended* to parse the sequence numbers in this way but was not made sufficiently robust to the absence of the "`#`", but I don't have the breadth of experience with DICOM to know if there are other cases for which the original code was intended to handle and that may be …
> DICOM: Tweaks to import

- docs/dwi_preprocessing/masking.rst
Follows #2197. Looks correct on local compilation, but will double-check online before merging.
> Docs: DWI masking: FIxes to formatting

- core/version.h
- docs/reference/commands/afdconnectivity.rst
- docs/reference/commands/amp2sh.rst
- docs/reference/commands/dwi2fod.rst
- docs/reference/commands/fixel2sh.rst
- docs/reference/commands/sh2amp.rst
- docs/reference/commands/sh2peaks.rst
- docs/reference/commands/sh2power.rst
- docs/reference/commands/sh2response.rst
- docs/reference/commands/shbasis.rst
- docs/reference/commands/shconv.rst
Final PR before release, just to make sure all CI tests run clean. 
DO NOT MERGE. This will need to be pushed as a fast-forward from the command-line...
> Release 3.0.3

- build
To fix pylint warnings which currently cause CI to fail
> build: fix pylint warnings

- core/math/math.h
- src/registration/metric/params.h
Eigen::DenseBase functions hasNaN() and allFinite() should instead be used.
Closes #2439.
> Remove Eigen helper functions is_finite() and is_nan()

- src/fixel/matrix.cpp
Hopefully results in better behaviour in the scenario reported on the [forum](https://community.mrtrix.org/t/fixelfilter-error/5469); also removes a lot of unnecessary custom code.
> fixelconnectivity: Normal image handling

- cmd/labelconvert.cpp
- testing/binaries/tests/labelconvert
Triggered by [forum post](https://community.mrtrix.org/t/about-how-to-use-the-template-to-create-the-connectome/5028), though it's hardly the first time it has happened.
> labelconvert: Throw exception on empty mapping

- cmd/mrtransform.cpp
This one caught me out in my own experiment.
> mrtransform: DWI grad export on linear

- cmd/mrclusterstats.cpp
> Write separate std_dev for each variance group

- src/gui/mrview/tool/odf/odf.cpp
> mrview: Permit SH lmax=0

- configure
Fix detection of parameters for compiling with Qt on macOS. Requires testing on other platforms...
> configure: fix Qt parameter parsing for MacOS

- .github/workflows/checks.yml
- build
- cmd/tckedit.cpp
- cmd/warp2metric.cpp
- src/dwi/tractography/SIFT2/tckfactor.cpp
- src/gui/mrview/tool/connectome/connectome.cpp
Since we specify 'ubuntu-latest' for the runner on GitHub Actions, we will occasionally run into problems like this...
> GitHub Actions: fix dependencies on Ubuntu 22.04

- lib/mrtrix3/__init__.py
Duplicate of #2475 to `master` as requested in #2540.
> python library: tweak execute to work with VS Code #2472

- docs/reference/commands/mrview.rst
- src/gui/mrview/window.cpp
See [discussion on forum](https://community.mrtrix.org/t/mrview-orientation/6329?u=jdtournier).
> mrview: change option name -orientationlabel to avoid conflict with -orientation

- docs/reference/commands/mrview.rst
- src/gui/mrview/window.cpp
This reverts PR #2569
See [associated discussion on forum](https://community.mrtrix.org/t/mrview-orientation/6329/7?u=jdtournier) for context.
> Revert "mrview: change option name -orientationlabel to avoid conflict with -orientation"

- docs/reference/commands/dwi2mask.rst
- lib/mrtrix3/dwi2mask/hdbet.py
This was a proposed solution to an issue I was having in achieving #2529. In the end it wasn't necessary, but it's still nevertheless a simple addition.
> dwi2mask hdbet: New option -nogpu

- bin/population_template
- docs/reference/commands/population_template.rst
Couple of minor issues I had while using this myself recently; more description in https://github.com/MRtrix3/mrtrix3/commit/0e0224f96aa55945bb77e78095727dbbb503bfb7.
> Population_template: Terminal tweaks

- .github/workflows/checks.yml
- configure
> configure: revert to -isystem rather than -idirafter

- .github/workflows/checks.yml
Updates the sccache-action by Mozilla to version 0.0.4.
> Update sccache action to version 0.0.4

- testing/scripts/tests/dwigradcheck
- testing/scripts/tests/for_each
Manually extracted from 05febcfc1e727eb3de65267096c17cbedee7659f as part of #2154.
Presumably was found to be necessary at the time.
Separating this out from the rest of #2154, as that will conflict heavily with the latest `dev` so I will likely instead re-implement those changes from scratch.
> Script tests: add -force where necessary

- core/command.h
- src/gui/gui.h
Was mistakenly removed in #2871
> Add missing #define for mrview

- .github/workflows/weekly_sanitizers.yml
Sanitizers workflow needs to be updated after #2865
> Update sanitizers workflow following testing changes

- CMakeLists.txt
> Fix compilation of big object files in MINGW debug builds

- cmd/mrdegibbs.cpp
- docs/reference/commands/mrdegibbs.rst
As discussed on forum some time ago:
https://community.mrtrix.org/t/mrdegibbs-in-partial-fourier/2457/2?u=jdtournier
> mrdegibbs: update doc to soften warning about partial Fourier

- bin/for_each
- bin/population_template
- bin/responsemean
- lib/mrtrix3/_5ttgen/hsvs.py
- lib/mrtrix3/fsl.py
- lib/mrtrix3/matrix.py
Fixes `pylint` issues produced on my own system (pylint 2.15.10, astroid 2.13.3, Python 3.10.12) that aren't currently caught by CI.
Seems to be Python2 safe, so OK to put on `master`?
> Python: Pylint fix consider-using-generator

- docs/reference/commands/5ttgen.rst
- lib/mrtrix3/_5ttgen/hsvs.py
Manual extraction of the original proposal for which the title of #2330 was written.
> Added info about consequences of using -white_stem in 5ttgen hsvs

- bin/dwifslpreproc
This provides a workaround for #3122
> Generate correct applytopup_config.txt

- docs/reference/commands/mrview.rst
- src/gui/mrview/tool/tractography/tractography.cpp
Flushing my local `master` clone.
> mrview: Fix typo in help page

- cmd/tck2connectome.cpp
- docs/reference/commands/tck2connectome.rst
- src/dwi/tractography/connectome/connectome.cpp
- src/dwi/tractography/connectome/connectome.h
As [requested on forum](https://community.mrtrix.org/t/tck2connctome-default-settings/8542).
> tck2connectome: Add default assignment mechanism to docs
