MRtrix3/mrtrix3

lib/image/threaded_loop.h
lib/thread.h
lib/thread_queue.h

Changes to handle exceptions thrown from threads more gracefully, as discussed in issue #167. Are we happy to merge this branch...?

C++11 thread exception handling

---

src/dwi/shells.cpp
src/dwi/shells.h

The bzero_threshold variable used in the DWI::Shells class was declared as a global variable, and initialised from File::Config. Problem is that initialisation for a global variable happens before entering main(), and hence before Config::init() (in App::parse()). So there is no way that the Config::get() call could return anything other than the default supplied, since the Config would appear empty at that point...
Solution proposed here is to  return a static member variable in a function, which defers initialisation until the first time it's called. Hopefully that function will never be called before Config::init()...

DWI::Shells: bzero_threshold no longer a global variable

---

cmd/mrconvert.cpp
lib/image/adapter/permute_axes.h

mrconvert now performs copy operation using the data type of the output image.
On a straight copy of a floating-point image, this provides a speedup of about 30%.
It also means that image values will not lose precision due to being cast to a complex float during copy.
Discussed in #196.
Closes #3.

mrconvert: Operate using native data type

---

icons/odf_preview.svg
src/gui/dwi/renderer.cpp
src/gui/mrview/tool/base.cpp
src/gui/mrview/tool/base.h
src/gui/mrview/tool/odf.cpp
src/gui/mrview/tool/odf.h
src/gui/mrview/tool/odf_preview.cpp
src/gui/mrview/tool/odf_preview.h

This remove the ODF display pane from the ODF tool, as discussed in issue #194.
Feedback welcome.

MRView: remove single ODF display from ODF tool

---

src/gui/dialog/opengl.cpp
src/gui/dialog/opengl.h
src/gui/dwi/render_frame.cpp
src/gui/dwi/render_frame.h
src/gui/gui.h
src/gui/mrview/tool/base.cpp
src/gui/mrview/tool/base.h
src/gui/mrview/tool/odf.cpp
src/gui/mrview/tool/odf.h
src/gui/mrview/tool/odf_preview.cpp
src/gui/mrview/tool/odf_preview.h
src/gui/mrview/window.cpp
src/gui/mrview/window.h
src/gui/opengl/gl.cpp
src/gui/opengl/gl.h
src/gui/projection.h

This branch introduces a few changes to the OpenGL backend. I've tried to test most use cases on my system, but I'd prefer to have as many people try it out before I commit something that might very well screw up - especially now that we've publicised it at the ISMRM...
I'd like confirmation that this works on all platforms and for all common combinations (especially Windows, I'll test MacOSX tomorrow), for both Qt4.8, 5.2/3 & 5.4 (where applicable), on as many different hardware combinations as possible. So far, I've only tested on Arch Linux 64-bit with the nvidia drivers, for Qt 4.8.6 and 5.4.2. Feedback appreciated before a merge to master.
As to the changes themselves, in a nutshell: 
- This branch replaces the `QGLWidget` (deprecated with Qt 5.4) with its replacement `QOpenGLWidget` …

QOpenGLWidget and other OpenGL related issues

---

cmd/tckedit.cpp
cmd/tckstats.cpp
src/dwi/tractography/connectomics/edge_metrics.h
src/dwi/tractography/editing/worker.cpp
src/dwi/tractography/editing/worker.h
src/dwi/tractography/mapping/mapper.cpp
src/dwi/tractography/streamline.h

Would like some independent eyes on this one. See commit message of 6fc76f5 for particular details.
Main point of contention is src/dwi/tractography/editing/worker.cpp, line 190ish: Because streamline lengths are now dealt with in floating-point lengths rather than point counts, it introduces a floating-point comparison problem. Ie. You don't want the user to request streamlines with a maximum length of 25mm, only to have it reject streamlines with a length calculated as 25.01mm. So I've thrown a bit of a fudge factor in there.
Also: `tckgen` code is _unchanged_. Mostly these changes are to deal with the down-sampling that occurs by default with iFOD2, so aren't applicable while the streamlines are being generated. Disadvantage of not changing the `tckgen` code is the rare use case where …

Streamline length

---

cmd/tensor2metric.cpp

and replicate 588851e4 since this causes failure at testing due to
dimension mismatch.

tensor2metric: fix assertion failure

---

configure
src/gui/dwi/render_frame.cpp
src/gui/mrview/tool/connectome/connectome.cpp
src/gui/mrview/tool/roi_editor/roi.cpp
src/gui/mrview/tool/roi_editor/undoentry.cpp
src/gui/mrview/window.cpp

Fix OS being reported as mingw_* instead of windows on msys2.
Fix configure to handle include paths relative to tmp.
Replace GL_ with gl:: to make OpenGL related stuff compile with Qt 4.

Fix configure to support building with msys2 on windows.

---

cmd/mrconvert.cpp

As discussed on [this MRtrix3 forum post](https://plus.google.com/102850892380704369664/posts/JjvrqdwRCts), the header entries specifying the intensity scaling were not being preserved by mrconvert, when they were in version 0.2.x. This fixes this to preserve these values by default.
It also introduces an option to manually specify these values if needed. For example, `-scaling 0,1` would give the same answer as it does currently.
Note that this did not affect the values read - only how they were stored. And these values would be correct given the scaling parameters that were actually used (i.e. 0,1) - within the precision of the data type. Where this would be problematic is for e.g. an FA map stored using an integer type and rescaled between 0 and 1 using these header parameters: this …

mrconvert scaling issue

---

src/gui/mrview/mode/ortho.cpp
src/gui/mrview/tool/base.h
src/gui/mrview/tool/odf.cpp
src/gui/mrview/window.cpp
src/gui/mrview/window.h
src/gui/opengl/gl.h

An attempt at addressing #299 and potentially #21. This introduces more thorough checks in debug mode to verify that the original OpenGL context is current when resources are deleted. These were used to ensure that all deallocation happen in the right order, and under the right context. It seems to fix most issues, but there is still a problem with the ODF tool failing an assert at exit if used, I'll investigate further before merging.

Fix opengl dealloc

---

src/gui/mrview/tool/connectome/connectome.cpp
src/gui/mrview/tool/connectome/connectome.h
src/gui/mrview/tool/connectome/file_data_vector.cpp
src/gui/mrview/tool/connectome/file_data_vector.h
src/gui/mrview/tool/connectome/matrix_list.cpp
src/gui/mrview/tool/connectome/matrix_list.h
src/gui/mrview/tool/connectome/types.h

Enhancing the connectome tool to hopefully make the initial entry point a bit easier for users: Initialise using the parcellation image, load a connectome, and you can see the connectome (with somewhat sensible defaults). Also gives the possibility of scrolling through a set of connectomes (though I still need to enable use of the keyboard arrows in the QListView).
But throwing it up here now in case someone wants to take up the challenge of breaking it, or has any other comments about the UI design, e.g. in #320.
Closes #320.

Connectome tool list

---

src/dwi/tractography/connectome/edge_metrics.h
src/dwi/tractography/mapping/mapper.h
src/dwi/tractography/seeding/basic.cpp

This was fixed in 2cbfa942 but re-introduced in 7f70bbfc.

tck2connectome: Fix length quantification

---

scripts/dwibiascorrect

- Try to identify the suffix that FAST will use for its output, so that the subsequent command can find it.
- Test input image to make sure it is a valid DWI, rather than relying on dwi2mask.

Fixes to dwibiascorrect script

---

lib/file/dicom/element.cpp

Just got sent some GE data were the DICOM import wasn't working. This was due to some private tags in the data being written with undefined lengths, which immediately caused MRtrix3 to (rightly IMO) throw out an Exception. This change modifies this behaviour to issue an info-level warning and assume undefined length means zero length. This fixes the import of the problematic data, and clearly won't affect import of other data since these can't have triggered the issue given that they were successfully imported...

DICOM: don't fail on undefined length tags - assume zero size

---

cmd/mrconvert.cpp
lib/datatype.h
lib/image/format/mri.cpp
lib/image/header.h

As discussed in #346.
Turned out to be a bit more complicated than anticipated due to the need to update the intensity scaling on datatype changes, which required `Header::datatype()` to return a proxy object. All seems to work OK, but I would really like someone to put this through its paces to see if I've missed something...

Header: preserve intensity scaling for integer types

---

src/dwi/tractography/tracking/exec.h

Make use of Thread::batch() to reduce the load on multi-threading queues, which can hang in heavy processing on Windows.
Related to #255.

Prevent tckmap hang on Windows

---

src/gui/mrview/window.cpp
src/gui/mrview/window.h
src/gui/opengl/gl.cpp

As discussed on #397, this fixes issues with rendering on MacOSX, fixes mouse scroll support for the Apple magic mouse, and adds keyboard shortcuts for zooming.
As always, any attempts to try to break this are appreciated...

MRView: a few fixes mostly for MacOSX

---

src/gui/mrview/tool/overlay.cpp

The trilinear and nearest neighbour interpolation were swapped for the overlay value display in mrview.

mrview overlay interpolation was swapped for the overlay value

---

lib/file/dicom/dict.cpp
lib/file/dicom/element.cpp

Allow integer tags to be read as floating-point (provides more tolerance to variations in the inputs), and correct typo in DICOM dictionary.
I wouldn't expect either of these changes to be particularly controversial...

DICOM: minor fixes to Siemens private DW tags

---

matlab/read_mrtrix.m
matlab/read_mrtrix_tracks.m
matlab/write_mrtrix.m
matlab/write_mrtrix_tracks.m

Using read_mrtrix_tracks.m, I have noticed a very minor problem with the error handling.
For example, when fopen() fails because the filename was not correctly specified, this is currently handled by printing an error message and then returning. This leads to the wrong type of error.
```
>> t = read_mrtrix_tracks('wrong_filename.tck');
error opening wrong_filename.tck
Error in read_mrtrix_tracks (line 10)
image.comments = {};
Output argument "tracks" (and maybe others) not assigned during call to
"read_mrtrix_tracks.m>read_mrtrix_tracks".
```
I changed the error handling in read_mrtrix_tracks.m and the other functions so that the functions assert() and error() are used instead of disp()/return().

Improve error handling in matlab functions

---

docs/installation/mac_install.rst

Minor fix to link in mac setup page as reported here: http://community.mrtrix.org/t/setup-git-environment-mac/120

fixed link to git setup page

---

lib/mrtrix.h

This prevents the precision from being set to zero for class types, as
discussed in #458.

fix precision handling in str() method

---

cmd/warpinit.cpp

Otherwise commands like this crash out:
$ warpinit in.mif warp-[].mif
The `.row()` method can only be used under very specific circumstances...

warpinit: don't use Image::row() method on non-direct-IO images

---

lib/image.h

This causes crashes on write-back for the rare cases where an _output_
image is accessed using .with_direct_io() (see e.g. #489).

Image::with_direct_io(): don't modify datatype of internal Buffer

---

scripts/src/_5ttgen/fsl.py

- Ensure that masked T1 image always has the correct file extension, regardless of how the mask was derived.
- Change template image used for mesh2pve call, so that it is present regardless of the masking mechanism used.

5ttgen fsl: Fixes

---

src/dwi/tractography/editing/editing.cpp
src/dwi/tractography/seeding/seeding.cpp
src/dwi/tractography/seeding/seeding.h
src/dwi/tractography/tracking/tractography.cpp
src/dwi/tractography/tracking/tractography.h

Directly copying the option value to the `Tractography::Properties` class does not implicitly cast the command-line contents to an integer, which is where the postfix detection occurs.

Tckgen integer postfix fix

---

lib/file/mmap.cpp
lib/file/mmap.h
lib/image_io/default.cpp

As discussed recently in #513.
This detects the filesystem that the file is held on using [statfs()](http://man7.org/linux/man-pages/man2/statfs.2.html), and uses memory-mapping for RW files if the FS isn't reported as NFS, CIFS or FUSE (which should also catch SSHFS & GlusterFS). Otherwise the current delayed write-back approach is used. This also checks whether the FS is mounted with the synchronous flag, and switches to delayed write-back in this case too, since that would also be expected to kill performance (and hammer the drive...).
This also applies to temporary (piped) images, so this will use direct memory-mapping for these data too if the temp folder is local (which it _really_ ought to be). So this should avoid double RAM allocations when using pipelines on `tmpfs`, for …

Use memory-mapping for output images if held on local FS

---

src/gui/mrview/gui_image.cpp
src/gui/mrview/gui_image.h
src/gui/mrview/tool/connectome/node_overlay.cpp
src/gui/mrview/tool/overlay.cpp
src/gui/mrview/tool/roi_editor/item.cpp
src/gui/mrview/volume.h
src/gui/mrview/window.cpp

Anybody want to test this?
When the user requests an intensity windowing reset, this will now be based on the min/max of the current slice if locked to axes, or the min/max of the volume if not.
In addition, if the current intensity windowing is invalid, the first non-empty slice encountered will force a windowing reset, as discussed in: http://community.mrtrix.org/t/trouble-with-nibabel-generated-nii-file/102/12.
Closes #405.

MRview: Windowing reset fixes

---

lib/file/gz.h

This fixes a bug that caused errors when loading an compressed `mif.gz` image when one of the lines in the header was exactly 63 bytes long...

File::GZ: fix getline() when line is exactly 63 bytes

---

src/gui/mrview/tool/odf/odf.cpp
src/gui/mrview/tool/odf/odf.h
src/gui/mrview/tool/odf/preview.h

Amplitude data sent to the preview renderer was not being filtered based on the selected shell, resulting in noisy ODF shapes as the wrong amplitude would be read for each direction.
Also enable / disable the level of detail control in the preview window according to whether the data is dixel-based (and hence whether this control has any meaning).
Closes #500.
Also modified so that b=0 shells no longer appear in the list of available shells to display.
@thijsdhollander Have a quick go at breaking it?

mrview ODF tool: Fix preview in dixel mode

---

cmd/dwiextract.cpp
scripts/dwibiascorrect
scripts/src/dwi2response/msmt_5tt.py

This means that e.g. the resulting image can be fed to mrmath -axis 3 to get the mean image, regardless of whether only a single volume was present.
Closes #552.
Reported a number of times in the past, but eventually reached [breaking point](http://community.mrtrix.org/t/error-cannot-perform-operation-along-axis-3-image-only-has-3-axes/164/2).

dwiextract: Always output 4D image

---

scripts/dwipreproc

Compare topup input and output image transforms using an absolute rather than a fractional threshold.
As reported [here](http://community.mrtrix.org/t/problem-with-dwipreproc-output/160/14).

dwipreproc: Fix divide-by-zero error

---

lib/stride.h

When converting to volume-contiguous format, we want to be able to
preserve the order of the spatial strides as much as possible, so that
conversion back to e.g. NIfTI preserves the strides of the original. For
example:
$ mrconvert 4D_image.nii -stride 0,0,0,1 4D_image.mif
would produce a volume-contiguous output image, but its strides were
previously set to `[ 2 3 4 1 ]` regardless of the input image. This might
cause downstream issues and/or confusion if these images are
subsequently used in other packages, if the strides of the original
4D_image.nii weren't `[ 1 2 3 4 ]` (which they often won't be).
This change means that the strides of the input image are preserved
relative to each other for the first 3 (spatial) axes, so that if
4D_image.nii had strides `[ -1 -2 3 4 ]`, the output …

better handling of undefined strides

---

lib/stride.cpp
lib/stride.h

fixes #570.
Note that this also add support for constructs such as:
$ mrconvert in.mif -stride 0,0,0,4 out.mif
Those strides specified will be used as is, those left as zero will be populated with the corresponding strides from the original. This can be used to force spatially-contiguous strides without affecting their relative order or sign. In other words:
$ mrconvert in.nii -stride 0,0,0,1 - | mrconvert - -stride 0,0,0,4 out.mif
should now result in out.mif having the same strides as in.nii, regardless of what these were (as long as its last stride was indeed 4, which will always be the case for NIfTI).
This also implies that the strides are interpreted as being strictly symbolic: whereas before a stride of 3,6,-7,2 would have been interpreted as 2,3,-4,1 (i.e. the order of the …

strides handling: fix issue with ignoring stride flips

---

cmd/fixel2tsf.cpp
cmd/fixelcfestats.cpp
lib/mrtrix.h
src/dwi/tractography/GT/externalenergy.cpp
src/dwi/tractography/GT/externalenergy.h
src/dwi/tractography/GT/gt.h
src/stats/cfe.h

Awaiting testing on Ubuntu 16.04, which fails compilation on current master: see [here](http://community.mrtrix.org/t/compile-error-on-ubuntu-16-04/183).

str() function: Fix for unsupported types

---

scripts/dwipreproc
scripts/lib/imagesMatch.py
scripts/src/_5ttgen/fsl.py

Provide a T2-weighted image to accompany the default T1-weighted image input.
This will be used as a second input channel to FSL FAST; it will not influence any other steps.
Notes:
* _Think_ I've tested every combination....
* Originally did this in a privately distributed script: `act_anat_prepare_hcp`. Re-implemented here so that anyone using that script doesn't have to manage an older MRtrix3 install to keep it working. 
* Not convinced that it's beneficial; and may be detrimental in some instances.

5ttgen fsl: -t2 option

---

scripts/dwipreproc

As reported [here](http://community.mrtrix.org/t/problem-with-dwipreproc-output/160).

dwipreproc -rpe_all: Fix erroneous gradient table output

---

scripts/foreach

Can be handy depending on how users like to organise their data. From the help:
```
UNI:  the unique prefix of the matching pattern after removing the common suffix
For example, if the target list contains files:
"folder/001dwi.mif", "folder/002dwi.mif", "folder/003dwi.mif" 
any occurrence of "UNI" will be substituted with "001", "002", "003".
```

foreach script: Added UNI keyword to substitute with the unique part of the prefix

---

matlab/write_mrtrix.m

Simple fix to make sure a 2D array gets promoted to a 3D array when writing the image - otherwise MRtrix3 will reject the image...

write_mrtrix: handle 2D images properly

---

src/gui/mrview/colourmap.cpp

The previous colour mapping for complex numbers was a bit of a hack, and looked pretty bad on a colourwheel. Mapping is now a proper phase->hue, mod->value, full saturation mapping.
More explicitly, complex number Z maps to HSV [ phase(Z) 1 abs(Z) ].
The difference can be seen on the colourwheel below: left is current, right is proposed. This shows the final colour for complex numbers with zero at centre, real along y axis (positive at top), and imaginary along x axis (positive on the right).

MRView: proper HSV mapping for complex numbers

---

cmd/mrcat.cpp

Useful when PE direction is stored in DW scheme, for instance.

mrcat: allow DW gradient tables wider than 4 columns

---

cmd/label2mesh.cpp
lib/adapter/base.h
src/dwi/tractography/seeding/base.h

I'm trying to compile MRtrix 0.3.14 with the Intel compilers (I tried with both versions 2016.1.150 and 2016.3.210).
719e416 fixes this problem:
```
In file included from ./lib/adapter/subset.h(20),
from src/gui/mrview/tool/connectome/connectome.cpp(21):
./lib/adapter/base.h(28): error: a template template parameter cannot have the same name as one of its template parameters
template <template <class AdapterType> class AdapterType, class ImageType, typename... Args>
^
```
I'm still running into another problem I haven't figured out though (I'm not exactly a C++ expert), suggestions welcome:
```
src/dwi/tractography/seeding/base.h(65): error: expression must have class type
ThreadedLoop (data).run ([&] (decltype(data)& v) { if (v.value()) count.fetch_add (1, std::memory_order_relaxed); }, …
```

fix compilation issues with Intel compiler

---

lib/math/Sn_scale_estimator.h
src/dwi/noise_estimator.h

@jdtournier This file placement struck me as odd, even though it's only used in DWI-related code. Merge if you're happy with it.

Moved Sn_scale_estimator from src/dwi/ to lib/math/

---

cmd/dwi2tensor.cpp
docs/getting_started/commands/dwi2tensor.rst
src/dwi/tensor.h

- Add output image encoding description to command help page and documentation.
- Get the number of shells in the gradient table, and throw an exception if the user inputs an image that does not contain an adequate number of shells for tensor estimation.
- Enforce floating-point multiplication and division when scaling individual rows of the b-matrix.
Initial discussion in #606, replaces #623.

dwi2tensor: Few changes

---

cmd/sh2response.cpp

As originally suggested [here](http://community.mrtrix.org/t/msdwi2response-returns-only-nan/209/3).

sh2response: Check validity of provided directions

---

src/gui/mrview/tool/screen_capture.cpp

Make sure that the output directory path is always valid, by aborting the function immediately if the user cancels in the file dialog.
Closes #393.

mrview Screenshot tool: Fix dir path handling

---

src/dwi/tractography/file.h
src/dwi/tractography/file_base.h
src/dwi/tractography/scalar_file.h

Error due to `File::OFstream` being unable to open an output image for writing, but class destructors then trying to write to the same file during stack unwinding.
Closes #585.

Tractography writer classes: Prevent segfault

---

scripts/lib/runCommand.py

Use a hack alternative for os.path.samefile() function when that function is not available.
As reported [here](http://community.mrtrix.org/t/error-in-5ttgen-fsl-t1w-acpc-dc-restore-brain-nii-gz-5tt-mif-premasked/273/1).

Scripts: Fix runCommand() for Windows, Python < 3.2

---

configure

configure now uses `QMAKE_MACOSX_DEPLOYMENT_TARGET` or `MACOSX_DEPLOYMENT_TARGET` or the actual OS X version to set `mmacosx-version-min` in `cpp_flags`, `ld_flags` and `ld_lib_flags`.
@jdtournier Can you double check whether that is what you had in mind?

Configure script: set flags for correct OS X version

---

cmd/transformcalc.cpp
cmd/transformconvert.cpp
testing/tests/transformcalc
testing/tests/transformconvert

#602 
- transformconvert: ITK (ANTS, Slicer) linear transform conversion to mrtrix format
- moved FSL linear transform conversion to mrtrix format from transformcalc to transformconvert
TODO: is the coordinate sign [flip](https://github.com/MRtrix3/mrtrix3/commit/cc405f44018c5e7bfa086fdb028f4c2b43e3aafd#diff-3c75e88716145025c395ac182dd6d0f8R213) robust towards large rotations?
Testdata generated with old transformcalc and verified with ITK's [RegisterTransform](https://itk.org/Wiki/ITK/Examples/IO/RegisterTransform) assuming `offset` in ITK is translation in mrtrix:
cat ~/mrtrix3/testing/data/transformconvert/affine_ants.txt
#Insight Transform File V1.0
#Transform 0
Transform: MatrixOffsetTransformBase_double_3_3
Parameters: 1.0572473616430247 -0.006601364847695607 -0.0070867633345200794 …

transformconvert

---

docs/installation/linux_install.rst
docs/installation/mac_install.rst
docs/installation/windows_install.rst

These don't work without escaping the '$', instead causing the full PATH
to be included again, which is not the expected outcome. For some reason, this also caused problems on a fresh Windows install - syntax error on shell startup, and commands not found. What we want to end up with is something like this written to the `~/.bashrc`:
export PATH=/path/to/mrtrix3/release/bin:/path/to/mrtrix3/scripts:$PATH
rather than having the full PATH as it was when the command was issued substituted in there verbatim...

install docs: fix update PATH command

---

scripts/src/dwi2response/tournier.py

This should do the job.  Unlikely to affect scenarios where `-mask` option was not supplied (but still possible, in principle).

dwi2response tournier fix to address #673

---

src/gui/mrview/tool/base.cpp
src/gui/mrview/tool/base.h
src/gui/mrview/tool/list_model_base.h
src/gui/mrview/tool/overlay.cpp
src/gui/mrview/tool/overlay.h
src/gui/mrview/tool/roi_editor/roi.cpp
src/gui/mrview/tool/roi_editor/roi.h
src/gui/mrview/tool/tractography/tractography.cpp
src/gui/mrview/tool/tractography/tractography.h
src/gui/mrview/tool/vector.cpp
src/gui/mrview/tool/vector.h

Feature request #560
* Support to load files via drag and drop (Overlay, ROI, Tractography and Vector for now)
* Support to reorder loaded files within the list view (Overlay and ROI)
I avoided supporting reordering of files for the Tractography and Vector tools as both use depth-testing when rendering.

Adding drag-drop to tools

---

src/gui/mrview/mode/base.cpp
src/gui/mrview/mode/base.h
src/gui/mrview/mode/ortho.cpp
src/gui/mrview/mode/ortho.h
src/gui/mrview/mode/volume.cpp
src/gui/mrview/mode/volume.h
src/gui/mrview/window.cpp

This fixes up the touchpad scrolling issue on MacOSX (although there is residual weirdness due to the way MacOSX emulates scroll acceleration with a regular mouse). It also fixes up pinch-to-zoom (this had been implemented previously, but never tested), and adds handling of panning using the touchpad - as far as I can tell, this is triggered by a long motionless single touch (not press) and drag. 
Calling all Macbook users to test these changes!

Macosx touchpad fixes

---

src/dwi/tractography/mapping/mapper.cpp
src/gui/mrview/tool/base.h
src/gui/mrview/tool/list_model_base.h
src/gui/mrview/tool/roi_editor/roi.h

To get rid of override warnings with clang due to unmarked overridden virtual functions.
1 unrelated warning is remaining:
release/src/dwi/tractography/seeding/seeding.o
clang++ -c -std=c++11 -DMRTRIX_MACOSX -fPIC -mmacosx-version-min=10.11 -DMRTRIX_WORD64 -DMRTRIX_NO_NON_POD_VLA -isystem /usr/local/Cellar/eigen/3.2.8/include/eigen3 -Wall -O2 -DNDEBUG -Isrc -Icmd -I./lib -Icmd -isystem /usr/local/Cellar/eigen/3.2.8/include/eigen3 src/dwi/tractography/mapping/mapper.cpp -o release/src/dwi/tractography/mapping/mapper.o:
src/dwi/tractography/mapping/mapper.cpp:196:43: warning: moving a temporary object prevents copy elision [-Wpessimizing-move]
vector_data.reset (new Eigen::VectorXf (std::move (load_vector<float> (path))));
^
src/dwi/tractography/mapping/mapper.cpp:196:43: note: remove …

marking of override of virtual functions

---

cmd/fod2fixel.cpp
src/dwi/fmls.cpp
src/dwi/fmls.h

In the case where the FMLS 'peak ratio to merge' parameter is less than 1.0, peaks that do not have an adequately deep trough between them will be merged into a single lobe.
This change allows the 'FOD_lobe' class to track the orientations of multiple FOD peaks when this occurs.
This will not affect default behaviour in any way, since 1.0 is the default value for this parameter; but it may be useful in other applications making use of this method.
Calculation of appropriate weights for numerical integration of FODs has also been moved to a discrete class in order to enable external access.

FOD FMLS segmenter: Store multiple peaks per lobe

---

src/dwi/fmls.cpp
src/dwi/fmls.h

Testing showed that for calculating the FOD numerical integration weights, the HouseholderQR solve() method ran fastest and had the minimal error.

FOD FMLS segmenter: Change decomposition

---

src/dwi/gradient.cpp

As reported in
http://community.mrtrix.org/t/mrinfo-delimiter-in-encoding-b/354?u=jdtournier

fix mrinfo -export_grad_mrtrix output

---

lib/app.cpp
lib/exception.h

When the user provides the incorrect number of arguments to a command (that does not have any arguments that are optional or allow multiple), the terminal error output will now provide the expected input and contrast it with the user's input (with options stripped); this will hopefully assist users in identifying precisely what has not been provided correctly.
Elevated due to [this discussion](http://community.mrtrix.org/t/dwi2response-error/355/7).
Closes #536.

More info on argument count mismatch

---

lib/math/math.h
scripts/dwipreproc

math.h: `load_transform` also accepts 3x4 matrix (i.e. from output of mrinfo)

dwipreproc: fsl fieldmap fix writes 4x4 transformation matrix

---

docs/index.rst

Presumably lost at 0.3.15 tag.

Docs: Restore labelconvert page

---

scripts/labelsgmfix

Reported [here](http://community.mrtrix.org/t/problem-in-perfoming-msmt-constrained-spherical-deconvolution/376).

labelsgmfix: Enforce output image to be uint32

---

scripts/dwipreproc

`-export_grad_mrtrix` and `-export_grad_fsl` output locations are unchecked and script fails if they exist

dwipreproc: check gradient output files

---

src/gui/dialog/dialog.cpp
src/gui/dialog/dialog.h
src/gui/gui.h
src/gui/mrview/window.cpp
src/gui/shview/render_window.cpp

Delays modification of dialog function pointers from terminal to GUI versions until the relevant GUI initialization has taken place.
Following discussion in #764.
Closes #323.

GUI apps: Prevent segfault on failed cmdline parsing

---

cmd/mrmath.cpp
testing/tests/mrmath

Currently computing the vector norm along an axis requires two steps: computing the rms and then multiplying this volume with the square root of the number of (not-nan) entries along that axis. I reckon this is common enough to justify a separate operation in `mrmath`.

mrmath: added vector norm operation

---

src/dwi/tractography/connectome/tck2nodes.cpp

Better fix for radial search. The premature exit from the radial search wasn't doing what it was supposed to. This fixes it, so the premature exit can still be used to improve execution speed with a larger search radius.
As reported [here](http://community.mrtrix.org/t/assignment-radial-search-choice/448/4).

tck2connectome: Small fix to radial search

---

scripts/blend
scripts/dwiintensitynorm

Changed copy commands for `dwiintensitynorm` and `blend` from cp to cp -L as copying symbolic relative links breaks them.

derefence symbolic links in script input

---

cmd/dwi2mask.cpp
cmd/fixelcfestats.cpp
cmd/fixelcorrespondence.cpp
src/stats/cfe.h

Fix a small bug in fixel correspondence. Cater for non-normalised direction vectors. And add check to dwi2mask.

Fix fixel correspondence

---

docs/reference/commands/dwi2mask.rst
docs/reference/commands/dwidenoise.rst
docs/reference/commands/fixelcfestats.rst
docs/reference/commands/fixelcorrespondence.rst
lib/app.cpp
lib/cmdline_option.h

Because MR::Argument::limits its a union, setting the min/max values permitted for an integer / float argument type then subsequently zeroing the choices field would in fact zero the minimum value.
Also updated some docs based on most up-to-date code.

Command-line parsing: Honour min values for ints and floats

---

docs/installation/windows_install.rst
lib/stats.h

If `mrstats` is run using the `-output` option with an empty mask (e.g. using `getImageStat()` in a Python script), throw an exception rather than returning with no error code and an empty `stdout`.

Stats field exception

---

configure

See my complaint in #805, this is a workaround.

no march flag if ARCH is empty string

---

scripts/average_response

Hopefully fixes [this issue](http://community.mrtrix.org/t/average-response-python2-error/553)

average_response is now python 2 and 3 compatible

---

scripts/dwiintensitynorm

for osx compatibility of recursive copying and dereferencing symlinks (http://community.mrtrix.org/t/dwintensitynorm-error/557/4)

dwiintensitynorm: cp -r --> cp -R 

---

cmd/dwidenoise.cpp

This addresses the huge drop in performance observed with Eigen 3.3, as
discussed in #833.

dwidenoise: add brackets to final recombine step

---

cmd/mrtransform.cpp

As discussed on the [community forum](
http://community.mrtrix.org/t/gradient-orientation-after-alignment-of-nifti-dwi-data-to-structural-data/584/1).
I think this should fix the issue, but I haven't a chance to test. I'd really like people to had a good look at it to make sure it's actually doing what it's supposed to, so please give it a crack if you have a minute...

mrtransform: apply the inverse transformation to DW gradients

---

docs/reference/commands/maskdump.rst
docs/reference/commands/mredit.rst
docs/reference/commands/mrinfo.rst
docs/reference/commands/mrview.rst
docs/reference/config_file_options.rst
docs/reference/scripts/dwipreproc.rst
src/dwi/tractography/tracking/early_exit.cpp
src/dwi/tractography/tracking/early_exit.h
src/dwi/tractography/tracking/write_kernel.cpp
src/dwi/tractography/tracking/write_kernel.h

OK @jdtournier, this is what I've ended up with for #828. I'm pretty sure my conditional probability is right but my priors were wrong, so I've simplified and am just testing that conditional directly.
Logic is as follows:
Requested maximum number of streamlines _N_, maximum number of attempts _A_ (whether set by default to _100N_ or set manually). Hypothesis _H_ is that the fixed probability of any generated streamline being accepted is greater than _N/A_, so we should reach the requested number of streamlines before we reach the maximum number of attempts.
If _H_ is true: what is the probability that, after _a_ streamline attempts, you will observe no more than _n_ streamlines (where _n_ and _a_ are the running values for streamline number and attempts respectively)?
If _n_ is so low …

tckgen: Premature exit mechanism

---

testing/tests/tckconvert

Test difference between `.vtk` files:
- extract point coordinates with `awk` and compare with `testing_diff_matrix`
- extract lines (list of integer references) and compare with `diff`
Testing a single file is split up in 2 separate testing commands for convenience.

Improved testing of VTK output in tckconvert.

---

scripts/mathpershell

This simple script applies `mrmath` to each shell in the input image. The output is concatenated in a 4-D image, where the 4th axis contains e.g. the per-shell mean in order of increasing b-value.
Example usage:
```
mathpershell dwi.mif mean dc.mif
```

New script for per-shell mean, rms, etc.

---

src/mesh/vox2mesh.h

Noticed while testing for response to [this post](http://community.mrtrix.org/t/mrmesh-validity-of-output/596).

mrmesh: Fix marching cubes algorithm on float images

---

cmd/amp2sh.cpp
cmd/dwi2adc.cpp
cmd/dwi2fod.cpp
cmd/dwi2noise.cpp
cmd/dwi2tensor.cpp
lib/filter/dwi_brain_mask.h
src/dwi/gradient.h

Finishing off #375 
Took the liberty of ensuring that it's the gradient table _used_ in processing that gets captured in the header, not just what was stored in the header (which could have been either absent or over-ruled by providing such information at the command-line).
Alternative function / keyval naming suggestions welcome.

New function DWI::stash_DW_scheme()

---

lib/thread.cpp

This now also checks whether the MRTRIX_NTHREADS environment variable is
set, and if so will use that value instead of reading it from the config
file. However, the -nthreads option still take precedence.
Discussed on the forum:
http://community.mrtrix.org/t/control-multi-threading-on-a-cluster/632?u=jdtournier

allow setting of number of threads from environment variable

---

docs/reference/commands/mrcalc.rst
docs/reference/commands/tckgen.rst
src/dwi/tractography/seeding/basic.cpp
src/dwi/tractography/seeding/seeding.cpp

- Prevent segfault when initialising a rejection seeder using a 4D image.
- Clarify usage of -seed_gmwmi option.
Fixes #867.

tckgen: Rejection and GMWMI seeding fixes

---

cmd/amp2response.cpp
cmd/amp2sh.cpp
cmd/dwi2noise.cpp
cmd/dwiextract.cpp
scripts/dwi2response
scripts/src/dwi2response/dhollander.py
scripts/src/dwi2response/fa.py
scripts/src/dwi2response/manual.py
scripts/src/dwi2response/msmt_5tt.py
scripts/src/dwi2response/tax.py
scripts/src/dwi2response/tournier.py
src/dwi/sdeconv/csd.h
src/dwi/shells.cpp
src/dwi/shells.h

Additionally, default lmax=10 for anisotropic responses. Follows some discussion in #786.

Integrating amp2response in dwi2response scripts

---

cmd/shview.cpp
src/gui/shview/render_window.cpp

This ended up actually being a removal of an old feature, which supposedly intentionally allowed a column vector.  In the single-shell days, the only reasonable interpretation was to treat the column vector as a row.  The fix introduces a segfault upon loading a multi-shell isotropic response (so not ready to merge yet); I'll quickly check if I can spot why...
(for reference: this is about one of the issues mentioned in #619)

shview fixes for multi-shell isotropic case

---

src/gui/mrview/window.cpp

Problem was introduced by 05e3e6542 to handle scrolling with touchpads,
but resulted in ~4x the step when using regular mouse wheel. This
affected scrolling through slices and zooming.

mrview: fix mouse wheel event handling

---

cmd/mrview.cpp
src/gui/mrview/tool/connectome/connectome.cpp
src/gui/mrview/tool/overlay.cpp
src/gui/mrview/tool/screen_capture.cpp
src/gui/mrview/tool/vector.cpp
src/gui/mrview/window.cpp

This implements the changes I'd [suggested here](https://github.com/MRtrix3/mrtrix3/pull/875#issuecomment-271538907), in response to a discussion with @ansk. Basically, images provided as regular arguments will now be opened as if they had been supplied with the `-load` option, meaning any following options apply to the expected image, etc. 
One thing this does change is that the image initially displayed when the command is issued is the _last_ one specified, whereas currently this would be the first one. Not sure whether this is a big deal, but I don't think there's any way to avoid this given how we want this to work.
Also, to make something like this actually work:
mrview a.mif -interp off b.mif -interp off
I needed to add `.allow_multiple()` to the `-interpolation` option. So I've …

Mrview cmdline parsing

---

cmd/dwiextract.cpp
src/dwi/gradient.cpp
src/dwi/gradient.h

As discussed in #878. Basically, get a processed version of the DW info to allow the shell selection to work as expected, but write back the unmodified version of the relevant DW info to the output.

dwiextract: preserve DW scheme information exactly as per input

---

testing/tests/mrcalc

Due to issues with handling of complex numbers on MacOSX - see #430. Just reported to me by a user, might as well fix it...

mrcalc: use 0+1j notation rather than 0+1i

---

src/dwi/tractography/connectome/connectome.cpp

In response to [this thread](http://community.mrtrix.org/t/tck2connectome-option-not-working-scale-invnodevol/680).
Will add more test data for `tck2connectome` after 0.3.16 is merged to master, since it appears that due to my ongoing battles with git submodules, the `master` branch on `test_data` is no longer pointing to the same commit as `master` in the main repo.

tck2connectome: Fix -scale_invnodevol option

---

cmd/mrview.cpp
src/gui/mrview/window.cpp
src/gui/mrview/window.h

This fixes issues when trying to run a complex set of operations in MRView from the command-line, and adds a new option `-volume` to set the volume currently shown. The main problem was that screen updates were not guaranteed to happen after each option was processed, leading to funny issues for later options, outdated/blank screenshots, etc. 
This came about because I was trying to do this:
```ShellSession
mrview -capture.folder . -capture.prefix screenshot- image.mif -size 256,256 -noannot -fov 120 \
-vol 0 -autoscale -capture.grab \
-vol 1 -autoscale -capture.grab \
-vol 2 -autoscale -capture.grab \
-vol 3 -autoscale -capture.grab \
-vol 4 -autoscale -capture.grab \
-vol 5 -autoscale -capture.grab \
-exit
```
which now works with these changes. :grin:
One outstanding issue though is …

Fix mrview cmdline processing

---

configure
core/types.h

allocator alignment: use std::max_align_t rather than configure test

---

bin/dwi2response
lib/mrtrix3/dwi2response/dhollander.py
lib/mrtrix3/dwi2response/fa.py
lib/mrtrix3/dwi2response/manual.py
lib/mrtrix3/dwi2response/msmt_5tt.py
lib/mrtrix3/dwi2response/tax.py
lib/mrtrix3/dwi2response/tournier.py
lib/mrtrix3/run.py

Some discussion already in #785.
Needed some gymnastics to get it working on Windows on Python2. Basically, even once you find the shebang, neither `/usr/bin/env` nor `/usr/bin/env.exe` works, and determining the MSYS2 root directory is not as easy as one would think (`os.path.abspath()` just inserts the *current* drive letter to the start of the string). So instead I just bypass `env`, and use `distutils.spawn.find_executable()` as is already used elsewhere.
Needs testing across OS's and Python2/3.

Scripts: Better handling of scripts invoking other scripts

---

lib/mrtrix3/_5ttgen/fsl.py
lib/mrtrix3/file.py
lib/mrtrix3/run.py

Following on from discussion in #920.
I thought that perhaps there was some sort of network file system race condition that was causing the annoying `standard_space_roi` missing file issue in `5ttgen fsl` (hence function `file.waitFor()`). It now appears as though it's `sh` not finding the script, yet giving a 0 return code. Differences in `subprocess` between Python versions may have contributed to the prior confusion in diagnosing - on top of the `sh` error message not being found until the `-debug` option was used.
Independently of the `standard_space_roi` issue, this function can also be used to wait for the `run_first_all` output rather than globally disabling SGE.
Need to confirm that this still works on Windows.

More fixes for scripts run.command() in 0.3.16

---

cmd/fixel2voxel.cpp
scripts/src/dwi2response/tournier.py

Alternative solution to #900.
Forgot I did this at one point; figured I'd list it to remind myself to have another look, check my laptop and make sure there weren't any other commits. Also whether `LoopFixelsInVoxelWithMax` should remain here or move into the headers.

fixel2voxel: New option -number

---

src/gui/mrview/tool/view.cpp
src/gui/mrview/tool/view.h

Added two buttons to the view tool that allow to copy x,y,z voxel or scanner coordinates to the clipboard and write them to stdout. Could be used as a poor man's annotation tool.

mrview view tool: buttons to copy voxel and scanner location to clipboard

---

src/gui/mrview/gui_image.cpp

Proposed fix for #940: `mrview: src/gui/mrview/displayable.h:309: void MR::GUI::MRView::Displayable::update_levels(): Assertionstd::isfinite (value_min)' failed.` 
I added `value_min = 0.0f;` and `value_max = 0.0f;` for all colourmaps in case the cursor is outside the FOV. This gives nan as lower and upper limit for the colourbar which I think is sensible.

mrview: outside FOV: set value_min and value_max to zero

---

src/gui/mrview/tool/tractography/tractography.cpp
src/gui/mrview/tool/tractography/tractography.h

Adds '-tractography.thickness' and '-tractography.opacity' options to
mrview command line.
NB: internally, thickness runs from [-1000, 1000], but the CLI ranges
[-1.0, 1.0].  Opacity is internally [0, 1000], but the CLI has the range
[0,1.0].
Keep a reference to the QSliders for thickness and opacity, then the
command line options call `setValue` on the sliders and the GUI is
automatically updated.

Adds command line options for tractography thickness and opacity

---

configure
core/types.h

As explained on [this page](https://eigen.tuxfamily.org/dox/TopicMultiThreading.html), Eigen handles multi-threading through OpenMP. This functionality can be disabled with macro `EIGEN_DONT_PARALLELIZE`, which we had activated in `core/types.h` because we typically have many, relatively small (voxelwise) operations that are more efficiently parallelized using image-level threading primitives.
However, there are two issues with this approach. First of all, `EIGEN_DONT_PARALLELIZE` is a one-off flag read only upon the first inclusion of `Eigen/Core`. The current implementation is therefore unpredictable because it depends on the header include order. For instance,
```
#include types.h
#include <Eigen/Core>
```
will deactivate Eigen parallelism, whereas
```
#include <Eigen/Core>
#include …
```

Eigen OpenMP handling

---

cmd/dwi2mask.cpp

This ensures the rights checks are done on the gradient scheme before
use, and produces a more informative error message when not found.
See also:
http://community.mrtrix.org/t/gradient-encoding-matrix-does-not-represent-a-hardi-sequence/549/10?u=jdtournier

dwi2mask: use DWI::get_valid_DW_scheme()

---

build
check_memalign
cmd/dirmerge.cpp
cmd/fod2fixel.cpp
cmd/meshconvert.cpp
cmd/tckstats.cpp
core/adapter/replicate.h
core/filter/dilate.h
core/filter/erode.h
core/filter/smooth.h
core/header.cpp
core/thread_queue.h
core/types.h
src/dwi/tractography/GT/mhsampler.h
src/dwi/tractography/GT/particlegrid.h
src/dwi/tractography/SIFT/gradient_sort.h
src/dwi/tractography/resampling/resampling.cpp
src/dwi/tractography/tracking/generated_track.h
src/gui/mrview/tool/odf/item.cpp
src/gui/mrview/tool/odf/model.cpp
src/gui/mrview/tool/overlay.cpp
src/gui/mrview/tool/roi_editor/roi.cpp
src/gui/mrview/window.cpp
src/registration/linear.h
src/registration/metric/evaluate.h
src/registration/nonlinear.h
src/registration/warp/compose.h
src/surface/freesurfer.cpp

To address #957.
Adds a new convenience call `MR::make_shared<X>()` to replace `std::make_shared<X>()`, which will allocate using the proper operator new, rather than placement new (presumably the reason why alignment requirements weren't being respected). 
Also fixes `check_memalign` to properly detect instances of `std::vector` (not sure why it wasn't working before...), and adds test for `std::make_shared`. 
I also added an equivalent `MR::make_unique<X>()` convenience call to create `std::unique_ptr<T>` pointers.

replace make_shared()

---

lib/mrtrix3/file.py

Resurgence of [this post](http://community.mrtrix.org/t/5ttgen/133/17) made me have another look at the newer solution to the `5ttgen` `run_first_all` problem, and I suspect what I had wasn't good enough.
The theory was to wait until a valid file handle can be obtained for the file the script is waiting for. That way it would happily wait for any SGE jobs to complete, rather than trying to disable SGE altogether. Trouble is, I think that a read handle could be obtained even if some other process had not yet completed writing the file data.
New approach is based on [this post](https://www.calazan.com/how-to-check-if-a-file-is-locked-in-python/): Try to get a file handle that includes write permissions, since that shouldn't be permitted if another process has its own write file handle. …

file.waitfor(): Make more robust

---

core/header.cpp

as suggested in #956.
All up for discussion. It's a simple addition, so why not. But it's not perfect, that history won't survive conversion to other formats - although it might (with a few modifications) work well with the MGH formats.

add current command-line to 'command_history' header entry

---

configure

Let the configure script strip out any mentions of Anaconda python in the PATH. This should fix recurring installation issues on both macOS and Linux (cf. issue #936 and [this](http://community.mrtrix.org/t/compilation-on-linux/123), [this](http://community.mrtrix.org/t/loading-freesurfer-6-mgz-files-crashes-mrview-mrconvert/826/11), [this](http://community.mrtrix.org/t/permission-denied-when-using-mrconvert-and-dwi2response/873/8), or [this](http://community.mrtrix.org/t/error-processing-project-file-tmp-tmpexdmto-qt-pro/288/3) forum post)

Remove Anaconda from PATH.

---

core/adapter/permute_axes.h

PermuteAxes keeps track of indices of non-existent axes to allow looping. 
Added dimensionality out of bounds check.

mrconvert fix axis insertion #977

---

docs/troubleshooting/FAQ.rst
docs/troubleshooting/display_issues.rst

The section `Linux: very slow performance when writing large images` does not make sense in [troubleshooting/Display issues](https://mrtrix.readthedocs.io/en/latest/troubleshooting/display_issues.html) so I moved it to the FAQs.
Edit: Did the same for `Compiler error during build` and `Hanging on network file system when writing images`.
As a side node: I tried to edit it in the doctest branch but it seems to be way behind `master` and has a lot of conflicts after merging with master.

docs: removed dirty page from display issues

---

lib/mrtrix3/app.py

Ensure Python3 compatibility of the new ``-version`` option in the script-API.

Support Python3 scripts with -version option

---

cmd/mrmesh.cpp

In the original code, the optimal threshold was always being calculated,
even when the user specified the threshold on the command line.  Now,
check that the threshold flag was not given before calculating the
optimal threshold.  Saves some processing time and prevents the user
from being worried that their value was not being honored.

Prevent estimation of optimal threshold when user specifies value

---

core/raw.h
core/thread.cpp

Required for thread-safe access to bitwise data - but this cast is a bit
of a hack and makes assumptions about the implementation. These
assumptions are now explicitly checked when the multi-threaded backend
is initialised - only issues warnings for now.

Threads: check that casting uint8_t to std::atomic<uint8_t> is safe

---

cmd/tckglobal.cpp
src/dwi/tractography/GT/externalenergy.cpp
src/dwi/tractography/GT/particlegrid.cpp
src/dwi/tractography/GT/particlegrid.h
src/dwi/tractography/GT/particlepool.h

As reported in #992, the recent merge of #785 accidentally introduced a segfault in `tckglobal`. This pull requests fixes this.
The error was caused by two issues:
- The new `row` method for image access interfered with an out-of-bounds check on the third dimension (DWI volumes) in the data energy computation. This was easily fixed by limiting the bounds check to the spatial dimensions.
- The memory alignment issues required a dedicated aligned allocator in `std::deque` and `std::stack` members of the object pool used to store track segments. This was fixed in 860c474 by setting the appropriate template arguments.
Today's commits clean up the code without affecting performance.

Fix segfault in global tractography.

---

core/types.h
src/dwi/tractography/GT/particle.h
src/dwi/tractography/GT/particlepool.h

Hopefully ensures Eigen 3.2 compatibility? (as discussed in #998)

Move memory aligned deque to core/types.h

---

cmd/mtbin.cpp

fix error: 
`error candidate template ignored: disabled by 'enable_if' [with _A1=MR::Helper::Value<MR::Image<float> >]`
via cast to float.

mtbin: fix isfinite check

---

src/gui/mrview/window.cpp

fixes segfault and assert failure in command line parsing as described in #1006

Mrview fix command line parsing

---

cmd/mrconvert.cpp

Currently, 
```
mrconvert -coord 3 0,1 in.mif -export_pe_table acqp.txt out.mif
```
fails with error:
```
mrconvert: [ERROR] malformed PE scheme in image "out.mif" - number of rows does not equal number of volumes
```
This pull request fixes this, and also facilitates jointly importing and exporting PE and/or gradient tables.

mrconvert PE export with -coord option

---

lib/mrtrix3/_5ttgen/fsl.py

Rather than testing for the presence of every .vtk file output by FIRST, instead look for the combined image created by the FIRST post-processing script. Also provide the user with a more clear warning regarding what it's waiting for, and the fact that there's a chance that FIRST may fail.
Closes #1011.

5ttgen fsl improved waitfor

---

cmd/mrconvert.cpp

This makes sure that the output file does not contain a PE table if a bogus phase-encode scheme is present in the input image. `mrconvert` warns that the output file's PE table is removed but currently, a bogus PE table could trigger [this](https://github.com/MRtrix3/mrtrix3/blob/master/core/phase_encoding.h#L65) exception instead.

mrconvert: don't set PE scheme if PhaseEncoding::set_scheme throws an exception

---

core/fixel/legacy/image.h

as discussed on the [community forum](http://community.mrtrix.org/t/building-failure-windows/1004?u=jdtournier).

fix compilation error on g++ 7.1 due to legacy code

---

core/file/mmap.cpp

Memory mapping of files on lustre has caused the 0% cpu use process stall, as discussed in the FAQ.  This edit just adds the lustre file system ID to the list recognized network file systems to opt for delayed write-back.

Detect lustre to avoid memory mapping files

---

core/adapter/reslice.h
core/file/json.h
core/types.h
src/dwi/tractography/mapping/writer.h

Trying to remove a bunch of new compiler warnings that myself and others have gotten since installing GCC7.
- Prevent use of multiplication when assigning to a boolean target, when a TWI target image is boolean.
- When performing oversampling using the reslice filter, compute the sum of image values using a `default_type` rather than the native datatype (which could be a boolean, or could experience integer overflow), then normalise appropriately depending on the native type (again, avoiding use of multiplication if the datatype is boolean).
***Not currently working***: Going gaga trying to figure out why my SFINAE is SNAFU.
- Prevent re-definition of `abs()` for unsigned integer types, which appears to have cropped up in a compiler header file. Some info …

Silence compilation warnings on GCC7

---

cmd/fixelcfestats.cpp
docs/reference/commands/fixelcfestats.rst
lib/mrtrix3/app.py
src/gui/mrview/tool/fixel/base_fixel.cpp
src/stats/cfe.cpp
src/stats/cfe.h

Had a go since there were [multiple requests](http://community.mrtrix.org/t/how-to-restrict-fixelcfestats-to-subset-of-tracts/845). Untested, but it's easier for me to get it installed on a server to test if I push to the online repo, so might as well post here straight away in case anybody is curious.
Wasn't a single unique solution. What I've gone with is:
- Despite using `-mask` option, output fixel image will still contain the same set of fixels as the input fixel template.
- When constructing the fixel-fixel connectivity matrix, streamlines may still be assigned to a fixel that is outside the mask, if the streamline is most collinear with that fixel. However connectivity to that fixel will not contribute in any way to the analysis.
- Only fixels within the mask are involved in data …

fixelcfestats: New option -mask

---

cmd/dirflip.cpp
cmd/dirgen.cpp
cmd/dirmerge.cpp
cmd/dirorder.cpp
cmd/dirsplit.cpp
cmd/dirstat.cpp

Hi @jdtournier,
As discussed, these are the fixes for the calculation of the energy.
dirmerge, for some reason, used 1.2/r. I've changed it to 1.0/r. Please have a look if this is correct as well.
Thanks

fixed calculation of energy

---

configure

Without this define stat was 32-bit, causing problems with large files (see https://gnunet.org/sorting-out-stat-thing).
Should address issue #1058

Ensure stat is 64-bit on Windows

---

core/image_diff.h

Clean version this time...
This is to avoid failures due to rounding errors, etc.

image_diff: relax tolerance on vox spacing

---

cmd/tensor2metric.cpp

This adds an option to sort eigenvalues by absolute size, even when eigenvalues are negative. Makes life easier for structure tensor analysis, if you must ask...

Tensor2metric sort by abs eigval

---

core/file/dicom/image.cpp
core/file/dicom/image.h
core/file/dicom/mapper.cpp
core/file/dicom/quick_scan.cpp
core/file/dicom/quick_scan.h
core/file/dicom/select_cmdline.cpp
core/file/dicom/series.cpp
core/file/dicom/series.h
core/file/dicom/study.cpp
core/file/dicom/study.h
core/file/dicom/tree.cpp
src/gui/dialog/dicom.cpp

This adds improved support for some DICOM files, by splitting series by ImageType. This means series that for example contain magnitude and phase data can be imported correctly (although separately), when before they were likely to fail due to the different data scaling parameters. It also avoids issues with some series that contain the image and the reformatting information (on Siemens scanners), and when derived images were included in the same series as the original (e.g. a mean DWI image at the end of the DW data on Philips scanners). Don't know why it's taken me so long to get around to dealing with, there was a comment in there with a [long-standing TODO item](https://github.com/MRtrix3/mrtrix3/blob/master/core/file/dicom/quick_scan.cpp#L66) to do just this... 
This is probably the …

Dicom split series by image type

---

cmd/tckresample.cpp
cmd/tckstats.cpp
src/dwi/tractography/connectome/extract.cpp
src/dwi/tractography/editing/worker.cpp
src/dwi/tractography/mapping/mapping.cpp
src/dwi/tractography/properties.h

As raised [here](http://community.mrtrix.org/t/tckstats-on-global-tractography/1049).
Have identified this duplication of code many times, but never gotten around to functionalising it.

Tractography::Properties::get_step_size() function

---

cmd/mrtransform.cpp
core/filter/resize.h
core/filter/warp.h

mrtransform: add -oversample option

---

docs/troubleshooting/advanced_debugging.rst

Triggered by [this post](http://community.mrtrix.org/t/error-segmentation-fault-invalid-memory-access/1071).
Is nice to have an up-to-date documentation page on debugging so that a link can be provided rather than having to repeat the details each time. However "Advanced debugging" documentation page was not updated to reflect changes to binary location and multi-build-configuration with `3.0_RC1`.

Docs: Update advanced debugging page for 3.0_RC1

---

bin/dwipreproc

As raised [here](http://community.mrtrix.org/t/error-unable-to-determine-matching-dwi-volume-pairs-for-reversed-phase-encode-combination/1070).
**Edit**: Will wait overnight to make sure the test with the provided data passes.

dwipreproc: Fix volume matching with zero-length gradient vectors

---

bin/dwibiascorrect
bin/dwipreproc
bin/labelsgmfix
lib/mrtrix3/_5ttgen/fsl.py
lib/mrtrix3/fsl.py

Another script fix necessary to get through my test of #1077.

Python fsl.findimage() function

---

core/filter/dwi_brain_mask.h

When an input DWI contains exceptionally low values (i.e. even in the b=0 volumes there's no voxels greater than 1.0), `dwi2mask` will provide an empty mask, which can cause errors at later steps (e.g. providing an empty processing mask to `eddy` in `dwipreproc`). Somehow, changing the syntax by which the sum of image intensities within a shell is calculated resolves the issue.
Thanks to Hamed Zivariadab for reporting the issue & providing data.
It's literally [this change](https://github.com/MRtrix3/mrtrix3/pull/1083/files#diff-3494ad7b6f68362ec038ded397892fd7L92) that fixes the issue... :man_shrugging:

dwi2mask: Fix for low image intensities

---

src/gui/mrview/tool/tractography/tractogram.cpp

Setting the stride for downsampling should be based on the output step size (if present) rather than the tracking step size. If no step size information is available at all from the track file header, then the stride should be fixed to 1.
Should have been included in #1069.
Also note relation to #1054.

mrview Tractography tool: Fix to downsampling

---

cmd/tckconvert.cpp

tckconvert would fault when reading ASCII VTK files.  Since binary are
sooo much easier to read, give the user some clue rather than
mysteriously crashing.

Warn rather than segfault on ASCII VTK files

---

Doxyfile

The [developer documentation](http://www.mrtrix.org/developer-documentation/) is currently missing heaps of stuff since `lib/` has been moved to `core/`...

Doxyfile: update input folders to list 'core' rather than 'lib'

---

bin/population_template

to avoid file metadata permission issues with [copy2](https://docs.python.org/3/library/shutil.html#shutil.copy2) on windows as reported in the [forum](http://community.mrtrix.org/t/fixed-dwiintensitynorm-error-at-population-template/1131)

population_template: replace shutil.copy2 with shutil.copy

---

core/file/config.cpp
lib/mrtrix3/app.py

This is prompted by a HPC sysadmin who prefers to keep all files related to a given package in a single location (likely to be a very common scenario). This is fine for everything apart from the config file, which is hard-coded to `/etc/mrtrix.conf`. It's difficult to see how the binaries could be modified to auto-detect the location of their config file, so it looks like an environment variable might be the only way to allow this. It's a trivial change, seems to work on my system.
Still need to fix up the scripts to match though...

system-wide config file location can now be overridden by MRTRIX_CONFIGFILE environment variable

---

bin/population_template
testing/tests/population_template

This had been bugging me for a while now, so I finally did something about it...
Issue was that `population_template` would invariably fail a test on my system. The issue was an incompatibility with Python3, due to writing a `str` to a binary file, without converting to `bytes` via `encode()` (fix in this pull request). What this did was to cause `population_template` to leave its temporary folder behind, and since that folder was not being deleted by `run_tests` either, this left untracked content in the testing repo, which would show up in the `git status` of the main repo. So I'd be doing `./run_tests` on a clean repo, and a subsequent `./build` would change the version string to add `-dirty` to it, simply because `population_template` had failed a test...
These changes rely on the …

Use tmp prefix in testing for population template

---

core/file/dicom/mapper.cpp

As discussed in #1118.
Basically, previous behaviour was to rely on the AcquistionMatrix dimensions to set the actual x & y slice dimensions, but this fails when the acquired matrix size is not that actually stored - as is the case when zero-filling in the reconstruction. Unfortunately, there is no information that I can see in the DICOM or Siemens CSA headers that actually conveys the correct size - instead, the Rows & Columns entries that would normally carry this information are used to store the full size of the mosaic. The only allusion to the actual slice dimensions is a private entry that reads `256x256p I`, in a section that seems to relate to textual information to be shown on screen - not something that can be relied upon. Another possibility is to use the FoV information and …

DICOM: fix handling of Siemens mosaic to handle zero-filled images

---

core/filter/warp.h

If non-linear warp field and template image are not defined on the same voxel grid, the warp field must be resampled onto the template grid before warping can take place. This needs to be done using an identity transform rather than an uninitialised transform.

mrtransform: Bug fix for warp field regridding

---

cmd/tckresample.cpp

This command should, in all instances, be capable of proceeding regardless of the proportion of streamlines that can or can not be resampled based on user request.
As raised [here](http://community.mrtrix.org/t/coordinates-for-tckresample-for-along-tract-analysis/1179).

tckresample: Fix command exit on resampling error

---

src/gui/mrview/mode/volume.cpp
src/gui/opengl/gl.h

Fixes #285. After quite a bit of investigating, problem turned out to be that ATI hardware/drivers can't handle it when the data for each vertex in a vertex buffer object are not aligned at 32-bit boundaries.
Suggesting merging to `master` since this fixes a (very) long-standing bug that's been eating away at me for years... And it's very unlikely to cause issues anyway.

mrview: fix volume render on ATI hardware

---

src/gui/mrview/mode/lightbox.cpp

* Fix for #1140
* However, this affects any rendered tool. Issue was that we need to ensure GL state is re-initialised because draw calls sequence is slice1, tools1, slice2, tools2 etc.
* Therefore, can't guarantee GL state remains unchanged between slices
* Ideally, want to ensure any tools restore original GL context at the end of their draw call, but regardless probably safer to do this

mrview: lightbox: Reinitialise GL state when rendering each pane

---

core/file/mgh.h
core/mrtrix.cpp

As reported [here](http://community.mrtrix.org/t/mrconvert-and-mrview-error-parsing-auto-align-header-entry-for-mgh-format/1208). 
Input & output of `split()` prior to fix in dc7db27:
```
"  0.99810399999999999  0.054095999999999998 -0.029326999999999999    2.0663290000000001"
[ (), (0.99810399999999999), (0.054095999999999998), (-0.029326999999999999), (2.0663290000000001), ]
```
Hence the error: `invalid number of entries on line 0 (5 should be 4).` Can be fixed with a prior `strip()` call, but dc7db27 nevertheless makes sense to me given the intent of the `ignore_empty_fields` parameter. a39e46b then re-formats the MGH AutoAlign field slightly. More verbose details in commit descriptions.

Fix MGZ AutoAlign header import/export

---

cmd/fod2fixel.cpp
docs/reference/commands/fod2fixel.rst
docs/reference/commands_list.rst

This option sets the maximum number of fixels to store in any particular voxel. This is enforced at the output stage, rather than during the FOD segmentation algorithm itself.
Also tweaked option grouping and the command synopsis.

fod2fixel: New option -maxnum

---

set_path

As reported in [this post](http://community.mrtrix.org/t/error-mrtrix3-executables-not-found-in-expected-location-in-windows-10-64-bit-installation/1253?u=jdtournier).

Fix set_path to look for mrinfo.exe on Windows

---

build
configure
set_path

OK, the fix I'd added in #1172 to allow `set_path` to run without error on Windows turns out to have been a dud - it runs, but it adds to the PATH using Windows paths and separator (i.e. `c:\blah` separated by `;`). Makes all but useless. Yet it runs correctly when invoked using the MSYS2-provided python executable - as do `configure` and `build`. 
So my thinking here is that we need to somehow force these scripts (and potentially all the others too) to use the MSYS2 python interpreter. One option is to modify the PATH to make sure `/usr/bin` is listed first, but given that this is set in the MSYS2-provided default `/etc/profile`, there's a good chance this might have unintended side effects - like using the wrong compiler if the user happened to have installed the MSYS2 version of GCC …

Ensure the MSY2 version of python is invoked on Windows

---

cmd/mrinfo.cpp
docs/reference/commands/mrinfo.rst

Voxel spacing was being written to a vector of integers, which inevitably misbehaved if the voxel size in mm was not an integer. This had consequences for reading this header information using the `image.Header` class constructor in Python.
Also changed `-vox` option to `-spacing`, for better consistency with the new internal nomenclature. (This one is up for debate; risk of breaking scripts, but in `dev` we don't use these `mrinfo` options for scripts anymore anyway)

mrinfo: Fix -json_all output

---

cmd/connectome2tck.cpp
src/dwi/tractography/connectome/extract.cpp
src/dwi/tractography/connectome/extract.h
src/dwi/tractography/file.h

When creating an output weights file, the `App::check_overwrite()` function was erroneously being called using the path to the track file rather than the weights file (`src/dwi/tractography/file.h:283`). This would persistently fail, since the header of the track file would be created before the path to the output weights file was specified.
Also cleaned up some `connectome2tck` code to use smart pointers rather than C-style pointers.

Tractography::File::Writer: Fix weights output

---

docs/spatial_normalisation/warping_images_with_warps_from_other_packages.rst

Fixes typo in command line reported [here](http://community.mrtrix.org/t/cross-correlation-metric-as-in-raffelt-et-al-2011/1263/3).

Typo fix in warping_images_with_warps_from_other_packages

---

core/app.cpp
core/app.h
core/formats/pipe.cpp
core/image_io/pipe.cpp
core/signal_handler.cpp
core/signal_handler.h

Someone just brought to my attention the fact that pressing Ctrl-C while a help page is displayed in the terminal renders the display unusable. I'm not sure why, but the terminal is left in a strange state, with typed commands not showing... You can see that the interrupt is handled by the invoking MRtrix command though, not the page display command (i.e. not `less`): our signal handling message pops up. 
So I figured the simplest fix was to delay setting our custom signal handlers until _after_ the command-line parsing has been done, particularly the handling of the help page. This seems to more or less fix it. 
The cleaner solution would be to have the invoking MRtrix command actually exit as soon as it's done piping its help page contents to the display command, but that turns out to …

delay signal handling initialisation

---

core/math/SH.h

Briefly mentioned in #1204 - seems `sh2peaks` fails for peaks that are perfectly aligned with the z-axis. Seems to be a simple divide-by-zero issue - the check introduced here seems to fix the problem.
In practice, this is unlikely to be a problem, given how low the chances are of ever encountering a peak perfectly aligned with the z-axis. There is no bug report for it, but it does fix a bug, so I'm wondering whether this should go on `dev`, rather than directly on `master`... Happy either way, opinions welcome.

SH peak finder: fix behaviour at pole for z-aligned delta

---

bin/dwigradcheck

In use case where input image header does not contain a gradient table, and user instead relies on the -grad or -fslgrad option, dwi2mask would fail due to the absence of a gradient table.
Instead have dwi2mask explicitly import from grad.b, which is guaranteed to exist regardless of how the baseline gradient table was provided.
No need to import the gradient table into the image header for the rest of the script, since tckgen is always run with an explicit -grad or -fslgrad option based on a permuted gradient table.
Supersedes #1151.

dwigradcheck: Fix dwi2maskcall

---

bin/average_response

Issue introduced in #1098.
Duplication of list rows using the '*' operator generates duplicate references to the first line, not duplicates of the first line contents; hence any modification to a value would be reflected synchronously across _all_ lines.
Closes #1216.

average_response: Bug fix

---

cmd/5tt2gmwmi.cpp

Error was made in porting to new syntax as part of 0.3.14, within commit ec49edcaf.
(Pretty sure this would have been one of the very first commands I ported...)

5tt2gmwmi: Fix -mask option

---

cmd/dirsplit.cpp

Prevents command from hanging with 100% CPU utilisation if only one output file is specified erroneously.

dirsplit: Ensure more than one output file

---

cmd/fixelcfestats.cpp
cmd/fixelcorrespondence.cpp
cmd/fixelcrop.cpp
cmd/fixelreorient.cpp
cmd/fod2fixel.cpp
cmd/tck2fixel.cpp
cmd/voxel2fixel.cpp
core/app.cpp
core/cmdline_option.h
docs/reference/commands/fixelcorrespondence.rst
docs/reference/commands/fixelreorient.rst
docs/reference/commands/tck2fixel.rst
docs/reference/commands/voxel2fixel.rst

Was throwing together a command to serve a niche purpose involving fixel data, and the lack of this functionality was giving me the irrits.
Though the fact that many fixel commands have an output directory that may also be an input directory, and therefore can't actually use this functionality properly, reminded me of #1043...

App: New argument types for input/output directories

---

bin/5ttgen
lib/mrtrix3/dwi2response/msmt_5tt.py

Follows from dca25c9c.
- In `dwi2response msmt_5tt`, if `5ttcheck` throws an exception, abort the script. However, if a warning is issued by `5ttcheck` rather than an exception, echo that warning to the user.
- In `5ttgen`, don't permit `5ttcheck` to throw an exception, but echo any warning issued.
Inspired by [this forum thread](http://community.mrtrix.org/t/dwi2response-msmt-5tt-error-axis-3-provided-with-coord-option-is-out-of-range-of-input-image/1417).

Script updates to reflect 5ttcheck changes

---

cmd/mrcalc.cpp

Prevents erroneous image file paths from resulting in an "error converting string" error message (due to erroneous string-to-float conversion).
As discussed on forum [here](http://community.mrtrix.org/t/displaying-fixl-based-analysis-results/1433).

mrcalc: More informative error message

---

bin/dwipreproc
lib/mrtrix3/dwi2response/fa.py

`mrinfo`'s command-line option `-shellvalues` was changed to `-shell_bvalues` in 29dbf025, merged to `dev` branch in #1211, but a couple of usages of this option in *MRtrix3* scripts were not updated.

Scripts: Small fixes to reflect mrinfo change

---

docs/dwi_preprocessing/dwipreproc.rst

Docs: dwipreproc: Slice-to-volume instructions

---

src/dwi/tractography/resampling/arc.cpp
src/dwi/tractography/resampling/arc.h

Fixing issues reported on forum [here](http://community.mrtrix.org/t/tckresample-and-tcksample-for-along-the-tract-statistics/1368).
Example data:
Current `master` code, using `-line` option:
Current `master` code, using `-arc` option:
PR code, using `-line` option:
PR code, using `-arc` option:

tckresample: Fix -line, -arc options

---

configure
core/app.cpp

I've been meaning to do this for a while, and [this recent post](http://community.mrtrix.org/t/tckgen-on-hcp-dataset-takes-excessively-long/1471/5?u=jdtournier) finally prompted some action...

include build information in -version output

---

src/dwi/tractography/algorithms/fact.h
src/dwi/tractography/algorithms/iFOD1.h
src/dwi/tractography/algorithms/iFOD2.h
src/dwi/tractography/algorithms/nulldist.h
src/dwi/tractography/algorithms/sd_stream.h
src/dwi/tractography/algorithms/seedtest.h
src/dwi/tractography/algorithms/tensor_det.h
src/dwi/tractography/algorithms/tensor_prob.h
src/dwi/tractography/tracking/method.cpp
src/dwi/tractography/tracking/method.h

As requested by @LeeReidCSIRO.
Previously, some tracking code was heavily reliant on the use of templating in `cmd/tckgen.cpp`. While the code would behave as expected in this context, some aspects appeared as though they had been designed with polymorphism in mind, but would not exhibit the expected behaviour if actually used in this fashion. This change introduces the correct polymorphism concepts such that the code can be used in this way if desired. It however does not have any significant influence on execution speed of `tckgen`, since it still exploits the template parameter of the `Tracking::Exec` class and hence does not use the underlying polymorphism.
Closes #1234.
Have confirmed that there is no measurable effect on `tckgen` performance.

Tracking code: Proper use of polymorphism

---

cmd/connectomestats.cpp
cmd/fixelcfestats.cpp
cmd/mrclusterstats.cpp

Memory for storing empirical statistics was not being allocated either before or during `Stats::PermTest::precompute_empirical_stat()` function.

Stats: Fix segfault when using -nonstationary

---

core/stride.cpp

Was not updated with other changes in 2258b08 that were merged to `dev` branch in #1211, resulting in `-strides` command-line option being ignored.
This highlights that the current testing suite assesses the underlying image data, but not the image header properties. It might be worth considering what we want to test & where / how.

Fix parsing of -strides option

---

src/gui/opengl/gl.h

`GLenum MR::GUI::GL::Texture::tex_type` was added in 3afcd2c5, but not appropriately initialised on construction, leading to unwanted warnings when running `mrview` in valgrind.

OpenGL: Prevent uninitialised variable memory warnings

---

lib/mrtrix3/run.py

Not a currently-used functionality, but necessary in other contexts where the script library is utilised.

run.function(): Support keyword arguments

---

run_tests

Simple change. As requested in #1268. 
Allows comments in test files. Anything that after a `#` will be stripped out and ignored during testing.

run_tests: handle comments in test files

---

src/dwi/tractography/mapping/writer.h

Fixes issue introduced in 17e22166. The specific use case of combining `-dec` with `-stat_vox mean` was altered to no longer rely on keeping track of a voxel-wise track density, and so memory for this buffer is no longer allocated; yet the receiving functor would still attempt to write to this buffer.
Closes #1285.

tckmap: Fix segfault with -dec -stat_vox mean combination

---

cmd/tckconvert.cpp
testing/tests/tckconvert

Fixes 2 edge cases.
1. when a VTK file does not have any lines, an uninitialized variable caused segfaults on Linux (but not Mac, hmm)
2. A .tck file with 0 streamlines now produces a valid RIB file.

Fix tckconvert vtk to tck

---

cmd/dwiextract.cpp
docs/reference/commands/dwiextract.rst

Stumbled across this trying to manipulate data manually while preserving BIDS-like formatting: Tried to use `-fslgrad` and `-export_grad_fsl` and the latter wasn't there :man_shrugging:

dwiextract: Add options for exporting gradient table

---

lib/mrtrix3/run.py

Relates to discussion in #953.
Having thought about the situation a bit, I think this is the best solution in terms of the script library. Even if decoding of DICOM text data were improved as described in #953, there's an external tool invoked by `run.command()` generating data that's genuinely invalid if interpreted as unicode, so the function needs to be robust to that.
This solution works for what I've tested it on thus far; I've got a couple of other cases to test, but would appreciate testing on problematic DICOM data as well.

run.command(): More robust text decoding

---

cmd/mtnormalise.cpp

In a very unlikely course of events, I happened to spot this one while staring at this bit of code for other reasons.  @rtabbara : looks like our masterpiece still had a little imperfection. :wink: 
For the RC3 release notes; can keep it short: "mtnormalise: bugfix related to outlier rejection"
For future reference: the bug made it a bit less likely for negative outliers to be detected (as they should've), and a bit more likely for positive outliers to be detected (as they shouldn't have).  Even though we intended for this step to be in the log domain, due to a small mistake in the looping, the log was essentially not applied (apart from one voxel, where is was wrong in another way).

mtnormalise bug fix

---

lib/mrtrix3/run.py

Unlike the Python versions provided by either MSYS or MinGW, the native Windows versions of Python are not POSIX compliant. As a result, `shlex.split()` does not appropriately handle the file system separator symbol. This change performs the necessary alterations to the `shlex.split()` call under such an environment.

run.command(): Support native Windows Python

---

cmd/voxel2mesh.cpp
docs/reference/commands/voxel2mesh.rst
docs/reference/commands_list.rst

As discussed in #1211.
Command is not used in scripts or documentation anywhere (`label2mesh` is used in the Connectome Tool instructions); it only exists for my own nefarious purposes. I like the idea of being able to run `mesh2voxel` & `voxel2mesh` *ad infinitum* :stuck_out_tongue_closed_eyes:

mrmesh: Rename to voxel2mesh

---

src/dwi/tractography/tracking/method.cpp

In some instances, when the `-backtrack` option was used with an algorithm other than iFOD2, attempting to revise the streamline direction upon truncation would result in accessing data outside of allocated memory.
Popped up in a failed CI test for #1313.

tckgen: Fix -backtrack memory error

---

src/gui/mrview/tool/overlay.cpp
src/gui/mrview/window.cpp

For options `-interpolation` and `-overlay.interpolation`, failure to flag correct parsing of the command-line option via return call resulted in a failed assertion.

mrview: Fix a couple of command-line options

---

core/file/nifti1_utils.cpp
core/file/nifti2_utils.cpp

NIfTI: handle near-zero w component in qform

---

core/mrtrix.h

This prevents a segmentation fault observed on MSYS with GCC 7.3.0, apparently due to re-use of a `va_list` upon which `va_end()` has already been called.
While I couldn't find a definitive piece of documentation, I [came](https://www.redhat.com/archives/amd64-list/2006-December/msg00001.html) across [a](https://stackoverflow.com/questions/2288680/reuse-of-va-list) few [pages](https://stackoverflow.com/questions/9937505/va-list-misbehavior-on-linux) suggesting that it is not appropriate to be calling `va_start()` upon a `va_list` that has already been passed to `va_end()`; seemingly there is some internal state parameter in the `va_list` that is not fully reset, and therefore misbehaviour can occur if the same `va_list` is used to iterate through variadic arguments a second time. The …

MR::printf(): Use va_copy()

---

cmd/mrhistmatch.cpp
testing/tests/mrhistmatch

This provides greater precision with respect to ground truth when run on test data; tolerances on automated testing updated accordingly.
Should resolve CI testing issues encountered in #1327 and #1332.

mrhistmatch: Use LU rather than normal equation

---

.gitignore
configure

The first (lesser and... less lesser) bugs have surfaced.  This pull request should deal with #1337 and #1339.  Doesn't change behaviour of any methods, and the fix to the configure script is actually a bit critical, since it enables static builds again.  So well, beautiful cases of hot-fixes in GitFlow speak; so should probably go straight to `master` ASAP.
Sorry for combining both into a single pull request.  If anyone feels strongly about this, happily split it all up; but I'm just trying to enable a swift resolution of both issues.  Separate commits though, so easy enough to look at separately, and will be nice and verbose in the git commit history.

RC3 hot-fixes

---

core/app.h

In #1282, a terminal warning was introduced in an attempt to catch cases where users failed to provide enough input arguments to command-line options.
This was refined in #1293 to prevent erroneous warnings from being displayed when having an input argument begin with a dash character is entirely reasonable.
This change further refines the logic dictating when a terminal warning should be issued, by identifying the use of piped images with command-line option inputs and not issuing the warning in that circumstance.

Prevent erroneous command-line usage warning

---

core/file/utils.h
docs/getting_started/image_data.rst
docs/reference/config_file_options.rst

1. Fix erroneous link syntax in fixel directory format description.
2. Based on colleague feedback, clarify distinction between TmpFileDir and ScriptTmpDir config file entries.
3. As suggested in #1336, Clarify locale requirements for MRtrix image format header key-value fields.
Closes #1336.

Documentation fixes / updates after 3.0_RC3 merge

---

cmd/5ttcheck.cpp
lib/mrtrix3/run.py

Just a couple of tweaks to diagnostic messages:
- `5ttcheck` when all is good.
- `run.command()` when a command fails but `stdout` / `stderr` are empty.

Diagnostic changes

---

bin/dwi2response

Came across this one myself. Details in commit message of 19eaa28.

dwi2response: Fix for absent -mask and no gradient table

---

bin/5ttgen

If the text output from `5ttcheck` was a single-line warning, then "`for line in stderr:`" would print a warning line *per word* :-/

5ttgen: Fix printing output of 5ttcheck

---

core/file/dicom/csa_entry.h
core/file/dicom/image.cpp

The wrong member function of class `File::DICOM::CSAEntry` was being used to pre-allocate the memory required to store slice timing, resulting in a mismatch in length between this data vector and the number of slices in the image.
For the sake of web searches, the issue that this fix corrects looks something like:
```
[WARNING] Number of entries in mosaic slice timing (82) does not match number of images in mosaic (60); omitting
```
Closes #1252.
Should probably wait for @jdtournier to run against private DICOM test suite.

DICOM: Fix slice timing import for mosaic data

---

src/gui/mrview/tool/connectome/connectome.cpp

In f0ef4d6f, controlling of connectome edge visibility was altered due to an observed inadequacy when attempting to suppress the display of edges based on the visibility of the nodes to which they are connected. However, removal of the relevant group box entry for some reason was not included in the commit, leading to the behaviour of each entry in the group box being inconsistent with its description. This change rectifies the mismatch.

mrview Connectome tool: Fix edge visibility

---

src/gui/mrview/tool/connectome/connectome.cpp

Failure to initialise member bool Connectome::have_streamtubes could lead to memory issues, as reported in #1330 ([this comment](https://github.com/MRtrix3/mrtrix3/issues/1330#issuecomment-390206796).
This appears to *not* be the sole issue contributing to the failure to display streamtubes, but might as well be fixed nonetheless to prevent potential segmentation faults, and help strike one potential cause off the list.

mrview Connectome tool: Fix streamtube initialisation

---

lib/mrtrix3/app.py

Users seem to continue reporting failure of commands executed within a wrapping script as though they are failures of the script itself. Maybe a minor rewording of how the error message is presented will reinforce the fact that in many circumstances, such commands are responsible for their own failure, rather than the script providing the command with bad data resulting in a failure.

Scripts: Tweak message on command failure

---

bin/dwipreproc

Some users may not appreciate the difference between slice timing data, and the "slspec" data required by `eddy` for slice-to-volume correction. This change catches the case where the user erroneously provides the former, performing the appropriate conversion whilst also warning the user that their input was in fact inappropriate.

Dwipreproc: Handle inappropriate slspec input

---

cmd/fixelcfestats.cpp

When constructing a scratch fixel mask due to non-use of the `-mask` option, give sensible values to the voxel sizes and transform matrix so as to suppress terminal warnings.
Eventually I would prefer to modify the fixel format handling more deeply so that header information such as spacing and transforms are ignored entirely for ndim < 3 (e.g. for fixel data files). But the change in this PR should at least reduce user feedback about irrelevant warnings.
Closes #1102.

fixelcfestats: Remove erroneous warning

---

check_syntax
core/file/dicom/select_cmdline.cpp
core/progressbar.cpp
core/types.h

Running `tckgen` on MSYS2 was consistently producing segfaults. This must have been happening for a while, very odd that no one's reported it so far... Here's that the output looked like on my system:
```
$ tckgen ms_wm.mif -seed_sphere -17,-7,15,5 -seed_dir -1,1,0 OR_L.tck -select 1000 -seed_unidir -include -1,-68,-11,30 -nthread 0
tckgen: [zu%] (null)    5681 seeds,     2257 streamlines,        9 selected
tckgen: [SYSTEM FATAL CODE: SIGSEGV (11)] Segmentation fault: Invalid memory access
```
After a bit of digging around, the fix [suggested in this post](https://stackoverflow.com/a/44383330/3244166) seems to do the trick - although [this post](https://stackoverflow.com/a/30851225/3244166) also helped...
Suggest merging to `master` as it's clearly a bug, and shouldn't affect anything …

MSYS2: fix segfault due to use of %zu printf format

---

cmd/fixel2voxel.cpp

When the operator chosen to map fixel data to a voxel grid results in a single scalar value per voxel, the output image should logically be a 3D image. However, due to use of the fixel format index image as the template, many such images come out as 4D. This change explicitly sets the output image dimensionality for each choice of operator.
The test data need to be updated also; but I'm posting here first to see people's opinions on base branch for the merge before I do so. I personally consider this a "bug", since when writing a script wrapping this functionality I had to explicitly pipe the result to `mrconvert -coord 3 - -axes 0,1,2` in order to get what would intuitively seem the "correct" result. But conversely, the command is not fundamentally "broken" in terms of crashing or …

fixel2voxel: Fix dimensionality of output image

---

lib/mrtrix3/app.py

Urgent fix for `master`: Python scripts currently failing.
Mistake introduced in #1410 / 292355ae.
Drastically need CI tests for scripts... Might upload one of the datasets I use for CI testing my BIDS app, which is whole-brain DWI & T1 but both downsampled by a factor of 2. Going to increase the size of the test_data module, but it's a necessary evil.

app.makeTempDir(): Fix syntax error

---

core/app.cpp
core/file/config.cpp
core/file/nifti1_utils.cpp
core/file/utils.h
core/math/rng.h
core/signal_handler.cpp
core/thread.cpp
docs/format_config_options
docs/format_environment_variables
docs/generate_user_docs.sh
docs/index.rst
docs/reference/config_file_options.rst
docs/reference/environment_variables.rst
src/gui/opengl/gl_core_3_3.cpp
src/surface/mesh.cpp

This allows signal handlers to be disabled with an environment variable. However, as noted in #1391, this may not necessarily be all that useful. 
A more useful feature on this pull request is that environment variables can now be documented in the same way as config file options, and will be updated with a call to `generate_user_docs`. 
This pull request also includes a few changes to quieten warnings with GCC 8.2.0 on MSYS2.

Disable signal handlers with env var

---

src/dwi/tractography/tracking/tractography.cpp

As noted in my response on [this forum thread](http://community.mrtrix.org/t/tckedit-after-targeted-tracking/1835). This change is necessary to be able to fully disable downsampling of track outputs for iFOD2.

tckgen: Permit -downsample 1

---

bin/dwi2response

If floating-point *b*-values are provided as input to `-shells`, the error produced is "`-shells option should provide a comma-separated list of b-values`", which isn't entirely intuitive.
This change is consistent with existing code within individual `dwi2response` algorithms for getting the list of *b*-values from an image.

dwi2response: Accept floating-point numbers in -shells option

---

cmd/amp2response.cpp

#1406 (specifically 01ebd8f) cherry-picked to `master`.
In addition to preventing a segfault in the case where the provided mask has dimensions XxYxZx1, which is really a bug and should have gone to `master` immediately, this change can apparently significantly speed up `amp2response` in some usage scenarios. I've therefore had a request for this change to be merged into `master`, so that for those where the processing time is problematic, they can simply update their `master` branch before commencing processing, rather than themselves managing a dedicated branch install with this change cherry-picked. I'm therefore requesting that the speedup also go to `master`, even though it's not strictly a "bug".

amp2response: Bug fix and speedup

---

cmd/tck2connectome.cpp
src/connectome/connectome.cpp

(Reported to me by Tanya Poppe)
On 4-D node images, `tck2connectome` outputs a warning for missing nodes, and produces an empty connectivity matrix. The commit in this pull request adds a trivial check for 3-D inputs, which can hopefully demystify such error cases more easily.

tck2connectome empty output on 4-D parcellation image 

---

lib/mrtrix3/fsl.py

In environments where multiple FSL versions can be loaded (HPC),
preferring the fsl5.0-X defaults leads to undesirable behaviour.
Users may explicitly activate some custom FSL either with environment
modules or manually with the default FSL setup procedure. If there is
a fsl package installed which prefixes their scripts with "fsl5.0-"
(i.e. neurodebian) mrtrix should not prefer that one over the explicit
user choice. This PR defensively changes the preference, but actually I would argue to completely drop the fsl5.0 convenience detection. If this is just to work with neurodebian then this assumption is missing the fact that neurodebian still requires users to run `source /etc/fsl/5.0/fsl.sh` to actually load and activate everything. Afterwards all binaries are in PATH and can and should …

Change FSL autodetect behaviour

---

cmd/dcminfo.cpp
core/file/dicom/element.cpp
core/file/dicom/element.h

As discussed on [this forum thread](http://community.mrtrix.org/t/dcminfo-tag-broken/1986).
Suggest committing to `master` since this is a (admittedly minor) bug fix, but also unlikely to affect anything else. Happy to commit it to `dev` if this is deemed more appropriate.
In case you're wondering: this passes all testing on my DICOM store.

dcminfo: fix -tags output

---

src/gui/mrview/window.cpp

Processing of this option was removed in merge commit 42573be60, presumably due to a mistake during conflict resolution.
Suggest merging to `master` directly since this is a clear bug fix, and the fix is totally benign.
[EDIT]
See [original report on the forum](http://community.mrtrix.org/t/mrview-norealign/1988).

mrview: fix -norealign option

---

src/gui/mrview/tool/connectome/connectome.cpp

Since these capabilities interpret low values as transparent and high values as opaque, 'opacity' is a more appropriate term. It is also more consistent with other mrview tools.

mrview Connectome tool: 'transparency' -> 'opacity'

---

cmd/connectomestats.cpp

Remove underscore between output prefix and fixed output file suffixes, in order to make output file names more consistent with other MRtrix3 statistical inference commands.

connectomestats: Alter output file names

---

cmd/mrpad.cpp

Previously the header translation was erroneously or not modified if the padding in y- and z-direction differs from that in the x-direction.

mrpad: fix header translation of y and z axes

---

core/file/dicom/element.cpp
core/file/dicom/element.h
core/file/dicom/image.cpp
core/file/dicom/series.cpp

A bunch of simple changes to prevent crashes when reading slightly malformed DICOM files with field present but left empty.

DICOM: increase resilience to errors and empty fields

---

cmd/dwiextract.cpp

Fix to selection of DWI volumes where there are volumes with the same phase encoding direction but different readout times.
Thanks to @treanus for report, solution & test.

dwiextract: Fix extraction based on total readout time

---

lib/mrtrix3/_5ttgen/gif.py
lib/mrtrix3/image.py
run_pylint

`app.error()` call contained a reference to the function being invoked, rather than the parameter that was passed to the function.
Not hugely consequential given the script is throwing an error at that point anyway; but nevertheless preferable for a more appropriate error message than "`TypeError: must be str, not function`".
Observed on [forum](http://community.mrtrix.org/t/dwi2response-dhollander-script-meet-error/2054).

mrtrix3.image.statistic(): Fix parameter naming

---

core/file/dicom/mapper.cpp

There are examples now of Siemens mosaics where the number of entries in the CSA NumberOfImagesInMosaic entry reports a large size than the number of slices - leading to the whole entry being ignored - yet the last few entries are empty. This change allows for this situation, by taking as many entries as there are slices, and ignoring the last few entries.

DICOM: be more lenient with slice timing vector in Siemens mosaics

---

.travis.yml
bin/dwipreproc

My guess is that somewhere in the `topup` code, when provided with the `--fout` option to output the estimated field, it generates a deep copy of the input *b*=0 series, and then overwrites the contents of the first volume with the estimated field. However because they erroneously don't reduce the template image to 3 axes when generating said copy, the output "field map" image contains copies of all but the first input *b*=0 volume.
Would expect to be fixed reasonably quickly at their end, but need to catch and handle here nonetheless.
Closes #1493.

dwipreproc: Compatibility with FSL6.0.0

---

src/dwi/tractography/streamline.h

As re-raised on [forum](http://community.mrtrix.org/t/tract-lengths/1991/5).
Turns out I should have paid closer attention to the contents of that function than just the function template :disappointed: 
Addressing this separately to #1507. That introduces changes in behaviour and interface in a number of different contexts. This PR is purely to address the erroneous calculation of lengths of nonlinearly-warped streamlines.

Explicit streamline length calculation on master

---

core/command.h

This otherwise prevents compilation on non x86 platforms (see #1514)
This is a harmless change, no reason not to merge to `master`.

only include xmmintrin.h header if actually used

---

bin/dwiintensitynorm

Function `app.mrconvertOutputOption()` can only be applied when `run.command()` is calling `mrconvert`; the command-line options it exploits are not present in other binaries.

dwiintensitynorm: Fix bug introduced in #1389

---

core/algo/random_threaded_loop.h
core/algo/stochastic_threaded_loop.h
core/algo/threaded_loop.h
core/thread.cpp
core/thread.h
core/thread_queue.h

Partially addresses #263.
@jdtournier: Querying the number of threads currently being used and then executing however many more are available might lead to race conditions, so I just went with the simple solution of either multi-threading or not.

Prevent deep multi-threading

---

cmd/mrtransform.cpp

Addresses this issue:
http://community.mrtrix.org/t/mrtransform-changes-strides-but-also-qform/2353

mrtransform: default to identity transform

---

.travis.yml

Cherry-picked c5419c17 from #1563 in order to permit merge of #1560 to `master`.

travis.yml: install typing module required for sphinx

---

cmd/mrcat.cpp

If there is no axis along which the size is greater than 1, the loop needs to exit before querying the size of axis index -1.

mrcat: Fix segfault on single-voxel images

---

.travis.yml
core/progressbar.cpp

Prompted by discussion in #263...
This means the terminal doesn't get clogged up with the same line repeated over and over again when the progressbar line width exceeds the terminal's width...

progressbar: disable line wrapping while updating terminal

---

core/bitset.cpp

As discovered in the process of #1543 (specifically 7273d35b) & verified using the unit tests in 543081f9.
No implications in the repository here: the function's only used in one place, and in that instance the instance is zeroed first so the relevant code never executes. But it's a bug nonetheless, so should go to `master` in case of external library use.

BitSet::resize(): Bug fix

---

cmd/connectome2tck.cpp

Memory for node volumes and centres of mass when generating exemplars was initialised based on the maximal node index observed in the assignments file. In the rare circumstance where one or more of the highest-valued nodes in a parcellation did not have any streamlines assigned to it, this would lead to a buffer over-run when compiled in release mode. This change introduces an explicit check for such, and issues a warning to the user.
Closes #1581.
Testing proposed changes compiled in debug+assert mode:
```
$ connectome2tck tracks.tck assignments.csv test/ -exemplars parc.mif -files single
connectome2tck: [done] reading streamline assignments file
connectome2tck: [100%] generating exemplars for connectome
connectome2tck: [100%] finalizing exemplars
$ mrstats parc.mif -output max
84
$ …
```

connectome2tck: Fix assertion failure / segfault

---

build
core/version.h

This allows version information to be added to the repo itself, and it'll be used in the event that `git` isn't present or the code was downloaded as an archive - addresses #1514. The version string must be set to the corresponding tag. When `git` can be used, the `build` script will check that the version information stored in the repo matches the version string produced by git (`git describe --abbrev=0`), and fail if it doesn't match. This means when a new version is to be released, the version string will need to be updated and then that commit tagged with the same version string before pushing with tags. 
This will need a bit of finessing when merging to `master`. Mostly likely strategy will be to force a fast-forward merge of a manual non-fast-forward merge - if that makes sense to …

Improve build versioning when git not present

---

cmd/warpcorrect.cpp
docs/reference/commands/warpcorrect.rst
docs/reference/commands_list.rst

Added two options that allow specifying the marker values of out of bounds values either as floating point number or as a 3D vector (`-marker coordinates`) and the numerical precision used for the floating point comparison (` -tolerance value`).
The default behaviour of `warpcorrect` has not changed other than that it uses floating point comparison with numerical precision of 1e-5 instead of the check for equality.
I added a warning if no out of bounds value was found (related to #1551) and an info-level statement as to how many voxels were modified.

warpcorrect: added option to specify out of bounds value or vector

---

bin/population_template

Remove intermediary files only if they exists so that the `-continue` option does not fail. More detailed issue description [here](http://community.mrtrix.org/t/population-template-continue-option-not-working/618/16?u=maxpietsch).

population_template: fix -continue

---

src/gui/mrview/mode/lightbox.cpp
src/gui/mrview/mode/lightbox.h

Don't know whether or not this would be causing the software to crash sporadically, but it was certainly failing assertions, and in the past I'm sure I've had random crashes with lightbox mode when compiled for release.

mrview Lightbox: Don't modify GL elements in wrong context

---

core/header.h
core/image_io/default.h
core/transform.h

Relevant warning: `-Wdefaulted-function-deleted`
- Can't have default move constructor in a class that has a reference member variable
- Can't have assignment operator in a class that has `const` member variables
--------
Full warnings:
```
./core/header.h:205:22: warning: explicitly defaulted move assignment operator is implicitly deleted [-Wdefaulted-function-deleted]
NDimProxy& operator=(NDimProxy&&) = default;
^
./core/header.h:215:25: note: move assignment operator of 'NDimProxy' is implicitly deleted because field 'axes' is of reference type 'vector<MR::Header::Axis> &'
vector<Axis>& axes;
^
./core/header.h:243:26: warning: explicitly defaulted move assignment operator is implicitly deleted [-Wdefaulted-function-deleted]
DataTypeProxy& operator=(DataTypeProxy&&) = default;
^ …
```

Prevent new compiler warnings on Clang8

---

lib/mrtrix3/app.py

Minor hiccup with #1449.
Old:
```
EXAMPLE USAGES
To compute the mean
diffusion-weighted
signal in each b-value
shell:
$ dwishellmath dwi.mif mean shellmeans.mif
```
New:
```
EXAMPLE USAGES
To compute the mean diffusion-weighted signal in each b-value shell:
$ dwishellmath dwi.mif mean shellmeans.mif
```

Python help: Example usage fix

---

bin/dwipreproc

Residual issue with changes in #1449 that only arises when the CUDA version of eddy does not complete successfully.

dwipreproc: Fix exception on CUDA eddy failure

---

lib/mrtrix3/run.py

Because of the difficulties associated with types in which string data can be stored between Python2 and Python3, it is easiest to simply assume that if the input to `run.command()` is not a list, it is a type for which string-based operations can be performed.
Issue was observed running `dwishellmath` on Python2, as it constructs `run.command()` calls based on the output of `image.mrinfo()`, which comes out as `unicode` (yet my Python2 doesn't seem to recognise '`unicode`' as a builtin keyword...).

run.command(): Don't validate input type

---

core/formats/mrtrix_utils.h
core/header.cpp
core/image_io/default.cpp
testing/tests/mrconvert

Resolving issues described in #1618.
- Prevent loading of MRtrix format images with less than 3 dimensions from throwing an exception due to voxel size specification.
- Fix bug in designation of square bracket usages to image axes on output image creation.
- For default image IO handler, prevent throwing of exception due to pre-existing files without `-force` / wiping of header information with `-force` at writeback in cases where image header and data are stored in the same file.

Fixes to multiple square bracket image path notation

---

cmd/mrhistmatch.cpp
core/algo/histogram.h

Re-submission of #1627: Both branch name and name of command in commit message were incorrect.
> Small tweak to mrhistmatch to enable operation on 4D images.
> By merging this prior to #1626, that script will be able to operate using all b=0 data from each image series, rather than having to collapse them into a mean b=0 image per series. Therefore will merge this PR first, then make the corresponding change in #1626.

mrhistmatch: Enable operation on 4D images

---

bin/dwicat
docs/reference/scripts/dwicat.rst
docs/reference/scripts_list.rst

Hey Robert,
Could you get it approved by some other developer. 
Best
Lena & Jakub

New script dwicat

---

core/adapter/permute_axes.h
testing/tests/mrconvert

This allows the correct interpretation of negative axis indices in the specification of the new axes, which is required to insert additional axes (e.g. going from dimensions [ X Y Z 3 ] to [ X Y Z 1 3 ]). This behaviour is required and documented for mrconvert's -axes option, which currently doesn't work as stated (fixed with this change).

permute_axes adapter: fix handling of additional axes

---

cmd/mrmetric.cpp
docs/reference/commands/mrmetric.rst
src/gui/opengl/font.cpp
src/gui/projection.h
src/registration/metric/thread_kernel.h

fixes the cross-correlation metric, updated mrmetric's command description.
reported and discussed [here]( http://community.mrtrix.org/t/cross-correlation-and-mrmetric/2648/9)

mrmetric: fix cross correlation metric looping

---

bin/dwigradcheck

Script failed to overwrite existing gradient table text files regardless of the presence of the `-force` command-line option.
Closes #1647.

dwigradcheck: Fix -force option

---

core/header.cpp

Arising from changes in #1618.
Prevents buffer overflow when concatenating axis is higher than the dimensionality of the image.

Header::concatenate(): Catch segfault 

---

lib/mrtrix3/matrix.py

Manually cherry-picked changes from #1614 that are requisite fixes for `dev` code introduced in #1603. Fixes were found in the process of #1614, but are not specific to #1614, so are being committed separately.
- `matrix.load_numeric()`: Skip empty fields resulting from repeats of the delimiter.
- `matrix.save_numeric()`: Fix variable name error when writing 1D numerical data.
- **Edit** `matrix.dot()`: Fix for 1D input data.

Fixes to mrtrix3.matrix module

---

src/dwi/tractography/connectome/extract.h

Was hunting an issue that turned out to have already been fixed in #1582. But this one inconsequential mistake meant that `valgrind` was saturated with errors.

connectome2tck: Prevent valgrind error

---

core/adapter/replicate.h
core/image.h

- In `Adapter::Replicate`, if the adapter is constructed based on an image whose voxel locations are not zero (e.g. the image has already been used in a loop), it is possible for the value accessed through the adapter to be based on the prior voxel location of the image from which it was constructed, rather than its own zero-filled axis locations. If that location is outside the image FoV, particularly if this leads to a data offset beyond the size of the allocated array, this leads to a buffer overrun.
- If printing the contents of an Image class using the `<<` operator, only print the value underlying the current voxel location if that location is within the image FoV.
Discovered in trying to merge `dev` into `stats_enhancements` in order for CI to pass on #1639 / #1543, but these two …

Fix two buffer overruns

---

docs/dwi_preprocessing/denoising.rst

Hope this fixes the math typesetting on the updated denoising page...

docs: fix math typesetting again

---

cmd/dwidenoise.cpp
docs/reference/commands/dwidenoise.rst

With these changes, the patch size in `dwidenoise` is by default selected as the smallest cubic extent at least as large as the number of DWI volumes in the data. So, 
- datasets with <=27 volumes will now be processed with `-extent 3x3x3`
- datasets with <=125 volumes will now be processed with `-extent 5x5x5`
- datasets with <=343 volumes will now be processed with `-extent 7x7x7`
- etc.
This helps ensure that the data redundancy is exploited to its fullest, and avoids implausible sudden jumps in the estimated noise level maps when the patch size gets too small. This will obviously affect default run time for HCP-like datasets, but after discussion with @maxpietsch I feel that this is a cost worth paying. In any case, users can always override the option if run time becomes prohibitive.

Smarter default patch size for denoising

---

lib/mrtrix3/dwi2response/msmt_5tt.py

As per 46d1db4; problem fundamentally caused by 63f51aad.

dwi2response msmt_5tt: Fix erroneous warning

---

cmd/mrthreshold.cpp
lib/mrtrix3/_5ttgen/freesurfer.py
lib/mrtrix3/_5ttgen/fsl.py
lib/mrtrix3/_5ttgen/gif.py
lib/mrtrix3/dwi2response/tournier.py

- `mrthreshold`: Fix erroneous exception message introduced in #1636.
- `dwi2response msmt_5tt`: Compatibility fix for low-resolution data (ie. few voxels), when running `dwi2response tournier`, based on new `mrthreshold -top` implementation in #1636.
- `5ttgen`: Fixes to FoV cropping due to behaviour of `mrgrid crop`, which deviated from former command `mrcrop` in #1609 but was restored to previous behaviour in #1678.

Script updates for recent PRs

---

core/file/json_utils.cpp

using the proxy meant pe_scheme was being overwritten when writing to new_line

Force copy of pe_scheme rows instead of proxy

---

cmd/mrinfo.cpp
docs/reference/commands/mrinfo.rst

changes the description of `-transform` from  "the voxel to image transformation" to " the transformation from image coordinates [mm] to scanner / real world coordinates [mm]".

mrinfo: transform doc

---

configure

As discussed in https://community.mrtrix.org/t/error-linking-qt-application/1690/12?u=jdtournier

configure: fix Python decode error on Windows

---

set_path

And again, as per #1694... Should be the last this time - no other occurrence of this construct, as far as I can tell.

set_path: fix Python decode error on Windows

---

src/gui/dwi/renderer.cpp

Reported by @bjeurissen due to crashes on macOS using ATI hardware & drivers. The error message was:
```
mrview: [ERROR] GLSL log [OpenGL shader program]: ERROR: Input of geometry shader 'position_GSin' not written by vertex shader
Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt.
You must not let any exception whatsoever propagate through Qt code.
If that is not possible, in Qt 5 you must at least reimplement
QCoreApplication::notify() and catch all exceptions there.
mrview: [ERROR] error linking OpenGL shader program ID 21
mrview: [SYSTEM FATAL CODE: SIGSEGV (11)] Segmentation fault: Invalid memory access
```
Looking at the shaders generated, that is in fact correct - even though it should have no effect on the …

Mrview fix dixel odf render

---

cmd/warpcorrect.cpp

small fix to `warpcorrect` when using nan as the out of bounds marker:
- fixes warning "no out of bounds voxels found with value" due to zero count
- if the marker is nan and any coordinate component is nan, all coordinate components are set to nan

warpcorrect nan

---

.travis.yml
travis.sh

Move documentation generation and comparison with repository contents from "`run`" test to "`build`" (renamed "`build_docs`"); this will hopefully make any issues regarding documentation mismatches easier and faster to diagnose, as the offending non-zero `git diff` will no longer be buried after the massive output from the "`run_tests`" script.

TravisCI: Move docs testing

---

core/math/SH.h
testing/cmd/testing_sh_precomputer.cpp
testing/tests/sh_precomputer

Seems the SH precomputer was still wrong, even after #1206...
The fix we did then made it work for the `Math::SH::get_peak()` call, but screwed up the `PrecomputedAL::value()` call... This is because the √2 factor had originally been absorbed in the precomputed Associated Legendre polynomials, which wasn't taken into account in the `get_peak()` call, but was taken into account by the `value()` call. This PR now ensures the precomputed Associated Legendre polynomials still _don't_ have the additional √2, so that they are interchangeable with the non-precomputed ones, but fixes the `value()` call so that that factor is correctly taken into account there. 
On the funny side, it looks like there had actually been no problem with the tracking until we decided to 'fix' it with #1206... 🤦‍♂ …

Fix sh precomputer again

---

bin/foreach
docs/reference/commands/foreach.rst

- change to PRE: now removes .gz if present then splits off extension instead of truncating after the first '.'
- fix to UNI: if the common suffix is empty (common for directories without common name suffix) the output was emtpy, now it defaults everything after the common prefix

foreach fixes

---

src/dwi/tractography/tracking/shared.cpp

Bug found during the workshop: ``tckinfo`` did not print the max_angle of a track file.

tckinfo: fix issue of printing max angle 

---

docs/installation/linux_install.rst

As raised in #714.
`numpy` dependence was removed in #1603, and thus does not need to be installed.

Installation: Remove numpy dependence

---

cmd/tckgen.cpp
docs/reference/commands/tckgen.rst
src/dwi/tractography/algorithms/fact.h
src/dwi/tractography/algorithms/iFOD1.h
src/dwi/tractography/algorithms/iFOD2.h
src/dwi/tractography/algorithms/sd_stream.h
src/dwi/tractography/algorithms/tensor_det.h
src/dwi/tractography/tracking/shared.cpp
src/dwi/tractography/tracking/tractography.cpp

First component of #1729. This reverts changes that affected default maximum angles for various tracking algorithms made in #1507. A second PR will then investigate potential changes to these defaults in a more targeted fashion.
Main changes being reverted can be found in the diff of #1507 [here](https://github.com/MRtrix3/mrtrix3/pull/1507/files#diff-8664fcc974921f94a61f6dd2bdc73f5a).

tcken: Revert default maximum angle calculation

---

core/math/SH.cpp
docs/reference/commands/amp2sh.rst
docs/reference/commands/dwi2fod.rst
docs/reference/commands/fixel2sh.rst
docs/reference/commands/sh2amp.rst
docs/reference/commands/sh2peaks.rst
docs/reference/commands/sh2power.rst
docs/reference/commands/sh2response.rst
docs/reference/commands/shbasis.rst
docs/reference/commands/shconv.rst

changed
> mrtrix3.readthedocs.io/en/VERSION/concepts/spherical_harmonics.html
to
> mrtrix.readthedocs.io/en/VERSION/concepts/spherical_harmonics.html

docs: fixed SH description URL

---

cmd/mrinfo.cpp
core/file/json_utils.cpp
core/file/json_utils.h

Well that was tremendous fun. Details in 2d279b2. Related to attempting to resolve BIDS-Apps/MRtrix3_connectome#59 via #1735.
`master`:
```json
{
"EchoTime": "0.028",
"FlipAngle": "90",
"MultibandAccelerationFactor": "1",
"PhaseEncodingDirection": "j-",
"RepetitionTime": "3.93",
"SliceEncodingDirection": "k",
"SliceTiming": [
[
1.96500003,
0.0,
2.03250003,
0.0675000027,
2.09750009,
0.132499993,
2.1624999,
0.197500005,
2.22749996,
0.262499988,
2.29250002,
0.327499986,
2.3599999,
0.395000011,
2.42499995,
0.460000008,
2.49000001,
0.524999976,
2.55500007,
0.589999974,
2.61999989,
0.654999971,
2.68499994,
0.722500026,
2.75250006,
0.787500024,
2.81750011,
0.852500021,
2.88249993,
0.917500019,
2.94749999,
0.982500017,
3.01250005,
1.04999995,
3.07999992,
1.11500001,
3.14499998,
1.17999995, …
```

JSON handling changes

---

bin/dwibiascorrect
bin/dwifslpreproc
lib/mrtrix3/image.py
lib/mrtrix3/path.py

Only two remaining functions within the Python API where it was considered more appropriate to use keyword arguments rather than ordered arguments. Was raised in #1736, but is ultimately downstream from #1449.
For any future additional capabilities in the API, experience suggests that keyword arguments should be used fairly liberally. Even if it initially looks like a function only needs one optional parameter, it only requires one new capability to be added to that function that itself requires an optional argument, and you then have argument order ambiguity.

Python: Use of kwargs for API functions

---

build

Addresses #1042: remove binary files in the target bin folder if no corresponding `.cpp` file can be found. The check whether a file is binary should be conservative but `check_encoding` makes it a rather expensive operation and could be relaxed if need be.
Removal is triggered for every build, irrespective of the build target.

Build remove outdated bin

---

cmd/mtnormalise.cpp
testing/tests/dwi2fod
testing/tests/mtnormalise

Add a test for `mtnormalise`. Note that this involved modifying the existing tests for `dwi2fod msmt_csd` to preserve separate outputs for WM, GM & CSF.

Mtnormalise tests

---

src/gui/dialog/opengl.cpp

Turns out the max texture size isn't the same for 2D and 3D textures... We basically only use 3D textures in `mrview`, so that's what should be reported in the OpenGL dialog. Could have saved me a lot of time debugging a non-issue...

MRView: report 3D texture size

---

core/progressbar.cpp
core/progressbar.h
src/gui/dialog/progress.cpp

Closes #1700 
I think this should do it.... The first commit here is the actual fix (silly mistake on my part). The second commit cleans up the implementation a bit (better encapsulation, but really mostly cosmetic). The last commit actively prevents a ProgressBar from displaying if another is already active - which should mean there is no need to use a loglevel latch to keep nested ProgressBars quiet...

Progressbar fix quiet

---

lib/mrtrix3/app.py

Fix to a glitch in the progress bar `done` method as reported on the [forum](https://community.mrtrix.org/t/population-template-python-error/2931).

app.py: progress bar: cast to int

---

bin/dwifslpreproc
lib/mrtrix3/matrix.py

Export of slice specification data for `eddy`'s slice-to-volume correction were not appropriately formatted as integers at point of text file generation.
Fixes #1773.

dwifslpreproc: eddy "slspec" export fix

---

core/file/json_utils.cpp
core/file/json_utils.h

This is necessary in order for the combination of `-fslgrad` and `-json_import` to work correctly: without this fix, the diffusion gradient table imported via `-fslgrad` is erased upon populating the header key-value member using the contents of the input JSON file.

mrconvert -json_import: Preserve existing key-values

---

cmd/connectomestats.cpp
docs/reference/commands/connectomestats.rst

As raised on the [forum](https://community.mrtrix.org/t/group-connectivity-analysis/2333/3). We no longer have the authority to attempt to change the name of a published method, given the duration of time since its publication, our generally pessimistic outlook on its performance, and the subtlety of our criticism of the existing name; so we'll be sticking to this name from now on.

connectomestats: Rename NBSE to TFNBS

---

cmd/mrdegibbs.cpp

Currently, running with `-axes 0,1,2` does not raise an error, but it should...

mrdegibbs: fix check for number of entries supplied to -axes

---

cmd/connectome2tck.cpp
src/dwi/tractography/connectome/exemplar.cpp
src/dwi/tractography/connectome/exemplar.h
src/dwi/tractography/connectome/extract.cpp

Fixes #1769.
Cannot modify `mrview` to properly read data generated by `connectome2tck` prior to this fix, since the NaNs present in the track file make accurate parsing of the data impossible. However upon fixing the output of `connectome2tck`, no modification of `mrview` code was required in order to properly display these exemplars without assertion failure despite the absent parcels:
Thanks @JeroenBlommaert for the report.

connectome2tck: Skip non-valid exemplars

---

appveyor.yml
run_tests
travis.sh

A little cleanup following #1614.
Currently, if certain aspects of CI fail, the relevant log files are not visible, because the requisite file move operation is not executed due to `run_tests` returning non-zero.

Change testing log filenames

---

.travis.yml

Necessary to fix TravisCI testing on `master` for various PRs.
Echoes #1535, which applied the same fix on `dev`.

TravisCI: Explicit brew update call

---

core/math/rng.h

A quick test shows that `std::random_device` now works as expected on Windows too (it used to produce the same seed every time). This now means the RNG initialisation uses the same code across all platforms.

RNG: use std::random_device to initialise on all platforms

---

cmd/mrcalc.cpp
core/file/json_utils.cpp
core/mrtrix.h
src/connectome/lut.cpp
testing/cmd/testing_diff_matrix.cpp
testing/cmd/testing_to.cpp
testing/tests/to

Closes #1780.
This one dragged out for longer than was predicted. In the end I had to completely overhaul the string-to-complex conversion, because it's a custom format (a+bi) that the standard stream operator doesn't handle, and it's called by `mrcalc` which means it needs to be robust.
Of the 188 tests in `testing/cmd/testing_to.cpp`, 56 currently fail on `master` / `dev`.
Anyone feel free to add extra tests if you think you can make it misbehave.

New MR::to<std::complex>() specialisation

---

src/dwi/tractography/SIFT/gradient_sort.cpp
src/dwi/tractography/SIFT/gradient_sort.h
src/dwi/tractography/SIFT/sifter.cpp

Necessary to fix a segfault in some demonstration data I'm working on. Basically for certain synthetic reconstructions, an entire multi-threaded search block gets removed, resulting in an iterator overflow.

tcksift: Sorter fix for rare usage

---

cmd/dirflip.cpp
cmd/dirorder.cpp
cmd/dirsplit.cpp
docs/reference/commands/dirflip.rst
docs/reference/commands/dirsplit.rst

Encountered this internal limitation while writing a script for generating acquisition schemes. Details in 3593415.
Execution is still way faster than other related commands, so that's no issue.
Also considered altering the optimisation of order by calculating the SH condition numbers for prospective addition of individual remaining directions; but undecided as to whether or not it's worth the effort yet.

dirorder: Exhaustive search

---

cmd/mrview.cpp
cmd/shview.cpp
src/gui/gui.h
src/gui/mrview/file_open.cpp
src/gui/mrview/file_open.h
src/gui/opengl/gl.cpp
src/gui/shview/file_open.cpp
src/gui/shview/file_open.h

This adds support for opening images by dragging onto the dash, and by double-clicking in the Finder.

mrview: add support for QFileOpenEvent (macOS)

---

src/dwi/tractography/resampling/downsampler.cpp

This caused crashes in rare cases, due to downsampling tracks with a single vertex.
First raised by @bjeurissen due to consistent crashes in `dwigradcheck` on Catalina, eventually tracked down to the use of downsampling (so nothing to do with macOS or multi-threading), and the issue isolated with a massive overnight 'valgrind' job on Linux... :sweat_smile:

tckgen: fix out-of-bounds access in downsampler

---

run_tests
testing/binaries/tests/fod2fixel

Minor fix to CI testing so that repeated executions of `run_tests` does not yield failures in `fod2fixel` tests due to pre-existing (i.e. not properly deleted) directories.

Testing: Change fod2fixel temp data paths

---

core/mrtrix.h
testing/cmd/testing_to.cpp

Supersedes #1821.
Rather than reverting initial changes, figured it would be cleaner to instead cherry-pick the relevant commit.
Outstanding question:
> There may be an argument for a `strip()` call actually happening *earlier*: i.e. not just for conversion to numerical types, but *any* kind of DICOM extracted strings should throw out any superfluous whitespace.

MR::to<>(): Strip whitespace (DICOM fix)

---

cmd/dwi2mask.cpp

Description in 099b4fc.
While it's unlikely for this behaviour to have been consequential for any analyses being undertaken on `master`, and it's principally to make a specific processing technique in #1543 work as intended, it is nevertheless erroneous behaviour and should therefore be fixed on `master`.

dwi2mask: Fix for cleaning filter with cropped data

---

.github/workflows/checks.yml

Simple fix so that if a `pylint` test fails, the reason for that failure can be found within GitHub Actions (#1824).

CI: Print pylint.log on failure

---

build

Fix for changes in #1824 to detect mismatch between current configuration and `build` code due to changed internal string substitution names.

Build: Detect outdated configuration

---

lib/mrtrix3/run.py

Works on Linux; requires test on Windows.
Closes #1825.

run.command(): Use same Python interpreter

---

bin/foreach

foreach used to support looping over just folders, by adding a trailing '/'
Currently this is broken because basename('foldername/') is empty, causing NAME to be empty.
This should fix this.

support foreach */ again to loop over directories

---

src/dwi/tractography/SIFT/output.h

Only applies if SH output images are [explicitly enabled by uncommenting code](https://github.com/MRtrix3/mrtrix3/blob/3.0_RC3/src/dwi/tractography/SIFT/model_base.h#L45); but a bug nevertheless.

SIFT: Fix TDI SH image output

---

src/gui/mrview/adjust_button.h

As discussed in #1462. Would appreciate others giving this a shot. 
Note this fixes the `-overlay.intensity` issue, but is unlikely to fix the `-overlay.colourmap` one discussed in [this forum thread](https://community.mrtrix.org/t/overlay-colourmap-and-intensity-are-not-applied-in-mrview-via-command-line/3115?u=jdtournier). I'll keep digging on that one...

mrview: fix -overlay.intensity

---

cmd/mrcolour.cpp

Explicitly clamping scaled input values to the range [0.0, 1.0] appears to be necessary for some colour mappings to ensure that extrema input values properly map to the endpoints of the colour map.

mrcolour: Clamp input values

---

bin/dwishellmath
bin/labelsgmfix
bin/population_template
lib/mrtrix3/_5ttgen/freesurfer.py
lib/mrtrix3/_5ttgen/fsl.py
lib/mrtrix3/_5ttgen/gif.py
lib/mrtrix3/dwi2response/dhollander.py
lib/mrtrix3/dwi2response/fa.py
lib/mrtrix3/dwi2response/manual.py
lib/mrtrix3/dwi2response/msmt_5tt.py
lib/mrtrix3/dwi2response/tax.py
lib/mrtrix3/dwi2response/tournier.py
lib/mrtrix3/dwibiascorrect/ants.py
lib/mrtrix3/dwibiascorrect/fsl.py
lib/mrtrix3/dwinormalise/group.py
lib/mrtrix3/dwinormalise/individual.py
lib/mrtrix3/run.py

Passing a user-specified path to `run.command()`'s keyword argument `mrconvert_keyval` must not be escaped, as the string is inserted directly as a list element and is not parsed as part of a command string.
Cherry-picked first commit from #1689.
Comments:
- This arose because I failed to appropriately modify usage during the evolution of #1449. In an earlier iteration I was inserting these entries into the `mrconvert` command string, which required path escaping, and then trying to subseequently erase them from the command string printed to the terminal; eventually I realised I could just separate the actual command `argv` from the terminal printout at an earlier point in the function, and have this parameter only influence the former. I simply failed to update the calls to specify …

run.command(): Fix mrconvert_keyval usage

---

.github/workflows/checks.yml
.github/workflows/package-windows-msys2.yml

I think this is what's borking Windows tests. Couldn't rename the files in the release to match the fetch calls.

GitHub: Fix for Windows workflows

---

src/gui/mrview/adjust_button.cpp

To address dark mode issues #1864 for `AdjustButton`s
- removes hard-coded background gradient and uses Widget background colour instead
- border colour emphasized

mrview: adjust button: dark mode modifications

---

cmd/mrconvert.cpp
cmd/mrinfo.cpp
core/axes.cpp
core/axes.h
core/file/config.cpp
core/file/json_utils.cpp
core/file/json_utils.h
core/file/nifti1_utils.cpp
core/file/nifti2_utils.cpp
core/formats/nifti_utils.h
core/header.cpp
core/header.h
core/mrtrix.h
docs/reference/commands/mrinfo.rst
docs/reference/commands/mrview.rst
docs/reference/config_file_options.rst
src/gui/mrview/window.cpp

In trying to resolve the various issues with JSON handling (#1735, #1738, #1771), it looks like there was quite a bit wrong with the relevant code. Given the breadth and magnitude of issues, I'd like to try to get JSON handling working as well as possible on `dev` (essentially expanding #1738), and then once we're happy with the behaviour here, determine what does or does not require immediate rectification on `master`.
-----
The complexity of the problem is as follows. 
1. Input orientation information could be either:
1. Stored in the image header, in which case such data *may* be reoriented in the header key-value data during the `Header::realign_transform()` function (depending on `-norealign` or `Header::do_not_realign_transform`);
2. Imported via `-json_import`, which occurs *after* …

JSON handling on dev

---

cmd/fixelcfestats.cpp
docs/reference/commands/fixelcfestats.rst

Print a custom Exception if the user attempts to run `fixelcfestats` by providing a track file.
Closes #1834.

fixelcfestats: Catch former usage

---

src/gui/mrview/adjust_button.h
src/gui/mrview/tool/overlay.cpp

Suggested fix to bug introduced in d411e6c5d7928ca (#1850), reported [here](https://community.mrtrix.org/t/mrview-view-options-segmentation-fault/3170). It seems to work but I am not 100% sure if this is a full fix as I've reverted `setValue` back to not trigger the `valueChanged` signals, `setMin` and `setMax` do.

mrview: fix view tool

---

core/math/math.h

math/math.h: Remove unneeded <locale> header

---

cmd/mrregister.cpp
core/math/math.h

modified centre of images format in linear transformation format (`save_transform()` and `load_transform()`) to unify key-value data  #1878
The file format changed from
```
#centre -1 -4 -2
1 0 0 0
0 1 0 0
0 0 1 0
0 0 0 1
```
to 
```
1 0 0 0
0 1 0 0
0 0 1 0
0 0 0 1
```
but the reading of the deprecated format is still supported.

linear registration: change of transform file format

---

src/dwi/tractography/roi.cpp

Bug exposed by change in ebaba50, and triggered by passing single-volume 4D mask as ROI to `tckgen`, resulting in:
tckgen: [ERROR] FIXME: sizes requested for Subset adapter must be positive
This is on `master`, so needs to be fixed ASAP.

tractography: fix ROI construction when passed a 4D mask

---

bin/dwifslpreproc

Discovered issues from #1603 in `dwifslpreproc` arising specifically from use of either slice-to-volume motion correction or explicit volume recombination.

dwifslpreproc: Fix writing of matrix files for FSL

---

core/formats/nifti_utils.h

Bug in #1843, which results in integer overflow if an image file name is shorter than "`.nii.gz`" (which arises in `./run_tests scripts`).

Formats::is_nifti(): Fix for images with short names

---

bin/dwifslpreproc

Bug discovered after report on the [forum](https://community.mrtrix.org/t/dwifslpreproc-eddy-mask-nii-looks-faulty/3164).
Issue was introduced in `3.0_RC1`. Due to the generalisation of `dwipreproc` features, `applytopup` was no longer run on the NIfTI images provided as input to `topup`, instead being run on volumes extracted from the imported DWI series based on phase encoding information. That image possesses the same strides as the input image.

dwifslpreproc: Fix strides of images input to applytopup

---

bin/dwifslpreproc
cmd/mrinfo.cpp
docs/reference/commands/mrinfo.rst

- In `dwifslpreproc`, when determining whether or not explicit volume recombination should be performed (as well as which pairs of volumes should be combined), rather than using a hard-coded b-value difference threshold, instead obtain the outcomes of applying the C++ shell clustering algorithm to those data, and ensure that paired volumes are attributed to the same shell.
- `mrinfo` has a new option `-shell_indices` to facilitate this.
Closes #1848.
Passes script testing.

dwifslpreproc: Use DWI shell clustering algorithm

---

lib/mrtrix3/matrix.py

Details in 009b4b8f. 
Only consequential for mis-use of the function (which the function creator was guilty of :roll_eyes: )

matrix.save_numeric(): Fix for erroneous usage

---

src/gui/mrview/mode/base.cpp

Probably a leftover from a previous buggy version of Qt...

Mrview fix cursor jump mac os

---

src/gui/mrview/tool/base.cpp
src/gui/mrview/tool/base.h
src/gui/mrview/tool/connectome/connectome.cpp
src/gui/mrview/tool/view.cpp
src/gui/mrview/window.cpp
src/gui/mrview/window.h

Finally figured out how to make the initial size of the view tool behave... Helps prevent massive expansion of window when initially showing the view tool.

mrview: fix initial size of view tool

---

src/gui/mrview/mode/ortho.cpp
src/gui/mrview/mode/ortho.h
src/gui/mrview/tool/view.cpp
src/gui/mrview/tool/view.h
src/gui/mrview/window.cpp

Adds a config file option `MRViewOrthoAsRow` to show the 3 orthoview panes in a row, e.g.:
Any use...?

mrview: add config option to show ortho view in a row

---

lib/mrtrix3/app.py
lib/mrtrix3/image.py
lib/mrtrix3/matrix.py
lib/mrtrix3/path.py
lib/mrtrix3/phaseencoding.py
lib/mrtrix3/run.py
lib/mrtrix3/utils.py

I can't remember exactly what it was that caused me to start changing these, but I did eventually recall #1616 where we had an issue with Python2 passing unicode data to `run.command()`: the basic construct removed there for being problematic (testing whether a variable is of string type) is actually present in a number of other locations within the API.
This is the same technique as is used in the Python `six` module; but given that is not a built-in, I didn't want to introduce that dependency.

Python: Better identification of string data

---

lib/mrtrix3/run.py

Allows providing an environment variable dictionary to be propagated to the subprocess call(s) just for that `run.command()` invocation.
Was a bit surprised when I went to use this and it wasn't there...

run.command(): Keyword argument "env"

---

lib/mrtrix3/app.py

Fix was applied in 65e41c12 / #1837, but appears to have been lost in merge e0223ed9 for #1605.

Python: Restore fix to ProgressBar line wrapping

---

bin/dwifslpreproc
lib/mrtrix3/matrix.py
lib/mrtrix3/phaseencoding.py

- When saving numerical data, default to full double-precision floating-point width (erasing trailing zeros); and for matrix / transform data, print with aligned columns; these are to be consistent with C++ API and not accidentally lose precision. Alters what was done in adda703a (#1775), and makes a09ee51c (#1792) redundant.
- New function `phaseencoding.save()`, which will properly write the phase encoding direction values as integers but the readout time as a float.
Twice in a row ended up with numerical data of lower precision than what I wanted. So decided it's better to go full-precision, and in specific cases where a lower precision is wanted to reduce file size, developer can request such. Also discovered the "`g`" specifier for `format()`, which removes trailing zeros from data …

mrtrix3.matrix: Precision changes

---

lib/mrtrix3/_5ttgen/fsl.py

It appears as though some fraction of the reported issues with "`5ttgen fsl`" have arisen due to use of the FSL script "`standard_space_roi`", which internally uses Unix command "`dc`" but fails to check for its presence beforehand.
Closes #1772.

5ttgen fsl: Check for unix "dc"

---

lib/mrtrix3/__init__.py
lib/mrtrix3/matrix.py
lib/mrtrix3/phaseencoding.py
lib/mrtrix3/run.py

If the *MRtrix3* Python modules are being used in interactive mode, do not attempt to extend the `command_history` key-value of any outputs.
Note: Will require a manual change to resolve with #1903. **Edit**: Done (153349e).

Python: No empty "command_history" outputs

---

cmd/5ttcheck.cpp

Partial volume fractions must by definition lie between 0.0 and 1.0 inclusive.
Closes #1278.

5ttcheck: Validate individual image values

---

build

Resolve conflict between #1550 and #1613, which resulted in compiled Python file "`bin/mrtrix3.pyc`" being moved to `bin/purged_files/`.

build: Don't remove bin/mrtrix3.pyc

---

.gitignore
build
check_syntax
src/dwi/sdeconv/msmt_csd.h

- Address temporary files generated by "`check_syntax`" script.
- Prevent `pylint` failures for file "`lib/mrtrix3/_version.py`" when run outside of CI.
Couldn't immediately reproduce the erroneous script algorithm docs issue. I did encounter an issue when both branch swapping and using different versions of Python, but that was an outright Exception.

Partially addressing Issue #1654

---

docs/reference/config_file_options.rst
src/dwi/shells.cpp
src/dwi/shells.h

This option controls the difference in b-value necessary for DWI volumes to be classified as belonging to different shells.
In addition, the default epsilon has been changed from 100 to 80.
Closes #1634.

New config file option "BValueEpsilon"

---

cmd/tckedit.cpp
cmd/tckresample.cpp
src/dwi/tractography/algorithms/iFOD2.h
src/dwi/tractography/properties.cpp
src/dwi/tractography/tracking/shared.cpp
src/gui/mrview/tool/tractography/tractogram.cpp

This field was intended to inform decisions regarding length calculations, but is not adequately robust to serve that purpose. For instance, use of upsampling / downsampling results in a non-constant step size. Until some more robust technique is used, this parameter perhaps gives a false sense of certainty. It does however mean that if the distance between vertices in the track file differs substantially from the tracking step size, some calculations may be inaccurate; though those are typically not calculations where precision is essential.
Closes #1813.

Remove all references to "output_step_size"

---

run_pylint

fixes issue with BSD `head` (`head: cannot open '–n1' for reading: No such file or directory`)

run_pylint macOS head fix

---

bin/population_template

- For output warps, utilise the key-values of the warp image within the scratch directory, but erase the "`command_history`" field; the only entry for this field in the output image header will therefore be the `population_template` call.
- For output linear transforms, rather than copying the file from the scratch directory to the output path, import the data and then re-save; this will make the "`command_history`" field in the text file header comment reflect the `population_template` call.
Without this change, output warp images do not contain the requisite transform information within their headers and therefore cannot be used.

population_template: Keyvals of output data

---

bin/population_template
lib/mrtrix3/app.py

The terminal output from `population_template` is still pretty in-your-face despite the Progress Bars and the use of list inputs to `run.command()`.
With this proposal, linear and non-linear components each get their own single progress bar. I'm not convinced that being able to see the commands in between stages is actually informative under typical use; if a stream of command strings in the terminal is preferred by the user, `-info` can be provided.

population_template: Progress bars

---

bin/population_template

addresses #1899
removed `str2filename` conversion, fix if template path contains characters to be escaped.

population_template: remove relic str2filename conversion

---

lib/mrtrix3/dwi2response/msmt_5tt.py

Due to #1909 and #1915, 5ttcheck will not throw an Exception if there are image values that do not lie within the [0.0, 1.0] range. This includes the current version of test data. Rather than correspondingly causing `dwi2response msmt_5tt` to fail, instead catch the `run.MRtrixCmdError`, and print the message to the terminal at warning level as previously.

dwi2response msmt_5tt: Update for 5ttcheck changes

---

bin/dwi2response
bin/labelsgmfix
lib/mrtrix3/dwi2response/dhollander.py
lib/mrtrix3/dwi2response/msmt_5tt.py
lib/mrtrix3/dwi2response/tax.py
lib/mrtrix3/dwi2response/tournier.py
lib/mrtrix3/image.py

Bashed this out because I'd rather make API changes before tag. This is far more Pythonic, precludes certain mis-uses, prevents having to call `mrstats` on the same image twice in a row in some instances, and really should have been done in #1737.
Closes #1921.

image.statistics(): Return namedtuple

---

cmd/tckinfo.cpp
src/dwi/tractography/file_base.cpp
src/dwi/tractography/file_base.h

Issue arose due to potential for multi-line "`command_history`" field following #1603.
Closes #1925.

Track files: Support multi-line key-values

---

bin/dwifslpreproc

Error messages being replaced with Python exceptions due to failure to make use of str() function.

dwifslpreproc: Fix some error messages

---

src/dwi/tractography/algorithms/iFOD1.h
src/dwi/tractography/algorithms/iFOD2.h
src/dwi/tractography/algorithms/nulldist.h
src/dwi/tractography/algorithms/tensor_prob.h
src/dwi/tractography/rng.cpp
src/dwi/tractography/rng.h
src/dwi/tractography/seeding/basic.cpp
src/dwi/tractography/seeding/dynamic.cpp
src/dwi/tractography/seeding/gmwmi.cpp
src/dwi/tractography/seeding/list.cpp
src/dwi/tractography/tracking/exec.h
src/dwi/tractography/tracking/method.cpp

It looks like XCode finally supports this as of version 8:
https://stackoverflow.com/a/29929949/3244166
This unifies the handling of the RNG instance used in the tractography code between macOS and the other platforms, and avoid having to handle it using a clunky pointer.

Use thread local on macos

---

core/file/dicom/select_cmdline.cpp
core/file/dicom/tree.cpp
core/mrtrix.cpp
core/mrtrix.h
docs/reference/environment_variables.rst

Another branch that was lying around gathering dust...
This allows the use of simple wildcard pattern matching with patterns supplied via the environment variables:
- DICOM_PATIENT to match PatientName
- DICOM_ID      to match PatientID
- DICOM_STUDY   to match StudyName
- DICOM_SERIES  to match SeriesName
Example usage:
```
DICOM_SERIES='diff*iPat2' DICOM_PATIENT='*donald*' mrinfo dicom/
```

DICOM: allow simple selection of series from environment variables

---

docs/getting_started/beginner_dwi_tutorial.rst
docs/getting_started/key_features.rst
docs/installation/before_install.rst

Simply mentions the availability of the Unix tutorial in a few places, and also suggests citing the paper rather than the website in publications (a bit overdue, that one...).

docs: add MRtrix3 paper and mention Unix tutorial

---

cmd/fixel2peaks.cpp
docs/reference/commands/fixel2peaks.rst
lib/mrtrix3/dwi2response/tax.py
lib/mrtrix3/dwi2response/tournier.py

Update `dwi2response` `tournier` and `tax` algorithms to reflect changes in #1874 to the `fixel2voxel` command and new commands `fixel2peaks` / `peaks2fixel`.
Also includes `-number` option to `fixel2peaks`.
This gets `./run_tests scripts` to pass for these two algorithms; there is however a change elsewhere that has resulted in the outcomes of `dwi2response msmt_5tt` changing, which I'll look into separately.
Closes #1942.

dwi2response: Fixes for #1874

---

src/gui/mrview/tool/view.cpp

In the View tool, the copy buttons previously used a space as the separator for the pasted text, which made it unwieldy for pasting directly into e.g. a `tckgen` command. This uses a comma instead.

mrview use comma as separator when copying focus position

---

bin/population_template

fix to the prefix and suffix removal for masks required to match images and masks under certain circumstances (due to using rstrip which matches a _set_ of characters)

population_template: fix to mapping between mask and images

---

cmd/dwi2fod.cpp
core/math/math.h
src/dwi/sdeconv/msmt_csd.h

Some of the error messages people were getting stuck on today could be a bit more verbose.
The more egregious one is "`no data in matrix file`" when in actual fact the file doesn't exist, because the initial state of the input stream wasn't checked.

dwi2fod: Improve error messages

---

cmd/fixel2voxel.cpp
docs/reference/commands/fixel2voxel.rst

Placing values of NaN in voxels where there are fewer fixels than the maximum resulted in altered behaviour of the `dwi2response tournier` algorithm in specific instances. This returns the default behaviour of this operation to be the same as the previous "`fixel2voxel split_data`" (changes in #1874). There is already an option "`-fill`" in place to change this at the command-line; only the default behaviour is being changed.
This is what ultimately led to the alteration of outcomes of `dwi2response msmt_5tt` in the script test data that was mentioned in #1943.

fixel2voxel none: Revert default fill to 0.0

---

bin/dwifslpreproc
core/file/dicom/mapper.cpp

Extracted changes from #1735 in order to apply to dev. In dwifslpreproc, perform a robust parsing of slice timing information from the image header.
During DICOM import, separate slice timings by space rather than comma; although the results of JSON export should be the same following #1771 / #1843, use of space delimiter for vector data is more consistent with other multi-dimensional data handling in image headers.
While #1735 was closed in part because it was targeted at `master`, I think that the changes there should nevertheless have been brought into `dev`. Currently `dwifslpreproc` fails on `dev` when utilising S2V due to [this line](https://github.com/MRtrix3/mrtrix3/blob/ce5bfd6c35369885de48a4e7179c226d0cfd3955/bin/dwifslpreproc#L244) having been tailored for erroneous slice …

dwifslpreproc: Changes to slice timing handling

---

core/mrtrix.cpp
testing/cmd/testing_unit_tests_parse_ints.cpp
testing/tests/parse_ints

Going through old stale branches and came across this. Any use...?

Allow parse_ints() to process whitespaces

---

core/file/dicom/image.cpp

As reported on forum:
https://community.mrtrix.org/t/dcm2niix-and-mrinfo-different-total-readout-time/3224
Issue was simply that computing the readout time requires knowledge of the matrix size, and in the case of Siemens mosaics, this entry is not the acquired matrix size.

Fix incorrect total readout time when parsing Siemens mosaics

---

core/math/average_space.h

average space default header transformations were not set to identity

mrmetric average space fix

---

lib/mrtrix3/dwinormalise/group.py

fix to `dwinormalise group` necessitated by name changes of temporary files within the `population_tempalte` scratch directory.

dwinormalise warp fix

---

cmd/fixelcfestats.cpp
core/math/stats/import.h

Addresses issue raised in #1543. More details in commit message.
Tested as working in the case where the text file listing all input files for statistical inference resides in a directory that is neither the input fixel directory nor the current working directory.

Stats: Modify import of cohort data

---

docs/dwi_preprocessing/denoising.rst

Changes to the patch size defaults and recommendations.

docs: update patch size selection for denoising

---

cmd/fod2fixel.cpp
docs/reference/commands/fod2fixel.rst
src/dwi/fmls.cpp
src/dwi/fmls.h

This kept irking me following discussion in #1874. Going back and looking through the code it was clear that this ambiguity of the word "peak" has been there for a while. Gets worse when talking about things like lobes containing multiple peaks, or merging lobes based on the ratio between the minimum of maximal amplitudes and the amplitude at the bridging dixel...
I had a go at making some changes to try to remove the ambiguity; not wholly sold on all of it (hence draft PR), but there's at least some stuff in there to consider.

fod2fixel: Revise options / help / code RE: "peaks"

---

.github/workflows/checks.yml
bin/dwifslpreproc
core/header.cpp

Closes #1956.
Using a fixed threshold difference in slice timing based on observation of precision of data in Siemens Mosaic CSAs.

Header::merge_keyval(): Add tolerance for slice timing differences

---

cmd/dirmerge.cpp
docs/reference/commands/dirmerge.rst

Went to give this option a go as I wanted to prioritise reduction of long-term eddy currents over truncation optimisation, and was met with `SIGSEGV`.
Flagging @jdtournier in case of objection against increasing the precision of the output directions.

dirmerge: Fix -unipolar_weight option

---

cmd/tsfmult.cpp
cmd/tsfsmooth.cpp
cmd/tsfthreshold.cpp
src/dwi/tractography/streamline.h

Resolution of compilation issue introduced in #1988.

DWI::Tractography::TrackScalar: Fix compilation on G++5

---

cmd/fixelcfestats.cpp
matlab/private/add_field.m
matlab/read_mrtrix.m
matlab/read_mrtrix_tracks.m
matlab/read_mrtrix_tsf.m

- `fixelcfestats`: Rename header key-value field "`nonstationarity adjustment`" to no longer contain a space.
- MatLab `read_*()` functions: For incoming header key-values, replace spaces with underscores in field names.
Closes #1633.

Matlab: Address header keys with spaces

---

core/file/dicom/element.h
core/file/dicom/image.cpp

Relegate warnings due to empty acquisition time fields in the DICOM headers to debug level - these are otherwise very annoying when loading a DICOM data set in `mrview` (you get a warning per affected slice...). Reported by @bjeurissen. 
Also a minor improvement in how these fields are parsed - might avoid segfaults in the future...

DICOM: improve handling of time fields

---

cmd/mrconvert.cpp

`mrconvert` calls can include `-clear_property command_history` to prevent propagation or generation of identifying information. This includes suppressing the addition of the currently executing command to the end of `command_history`.
When doing so when the input image does not itself contain `command_history`, the command will currently generate a warning to say that that field does not exist. This shouldn't occur, as specifying `-clear_property command_history` is still serving a purpose even if not currently present.

mrconvert: Avoid unnecessary warning

---

matlab/read_mrtrix.m
matlab/write_mrtrix.m

Closes #2016 
Given the fix, I've no idea how this ever worked for `.mif` outputs...

write_mrtrix.m: fix handling of .mih outputs

---

matlab/read_mrtrix.m
matlab/write_mrtrix.m

Brings #2017 into `dev`, and also increases the precision of floating-point outputs so as to prevent modification of images when passed through the Matlab read / write functions.

Matlab function fix dev

---

core/app.cpp

Show dash character in front of option name when explaining to the user how their usage of the command is erroneous.

Improve error messages on erroneous option usage

---

src/dwi/shells.cpp

Spawned by [forum thread](https://community.mrtrix.org/t/wrong-number-of-shells-after-mrconvert/3509).
```
$ mrinfo test.mif -dwgrad
0    0    0    0
0    0    1  100
0    0    1  100
0    0    1  100
0    0    1  100
0    0    1  100
0    0    1  100
0    0    1  700
0    0    1  700
0    0    1  700
0    0    1  700
0    0    1  700
0    0    1  700
0    0    1 1400
0    0    1 1400
0    0    1 1400
0    0    1 1400
0    0    1 1400
0    0    1 1400
0    0    1 1400
0    0    1 1400
0    0    1 1400
0    0    1 1400
0    0    1 1400
0    0    1 1400
0    0    1 2000
0    0    1 2000
0    0    1 2000
0    0    1 2000
0    0    1 2000
0    0    1 2000
0    0    1 2000
0    0    1 2000
0    0    1 2000
0    0    1 2000
0    0    1 2000
0    0    1 2000
0    0    1 2000
0    0    1 2000
0 …
```

DWI::Shells: Classify b=0 before clustering

---

docs/quantitative_structural_connectivity/structural_connectome.rst
docs/reference/commands/tck2connectome.rst
src/dwi/tractography/connectome/connectome.h

Feedback from collaborators operating on a wider gamut of data has been that the default maximal radial search distance is too restrictive, and leads to too many false negatives relative to the false positives introduced by increasing the limit (which many have been doing manually).

tck2connectome: Increase default radial search

---

cmd/dwi2mask.cpp
cmd/dwi2tensor.cpp
cmd/fixelcfestats.cpp
cmd/fod2dec.cpp
cmd/fod2fixel.cpp
cmd/mrtransform.cpp
cmd/mtnormalise.cpp
cmd/warp2metric.cpp
docs/reference/commands/dwi2mask.rst
docs/reference/commands/dwi2tensor.rst
docs/reference/commands/fixelcfestats.rst
docs/reference/commands/fod2dec.rst
docs/reference/commands/fod2fixel.rst
docs/reference/commands/mrtransform.rst
docs/reference/commands/warp2metric.rst

Moving the `REFERENCES` section in `mtnormalise` was necessary to prevent the website publication crawler script from crashing out. The rest are just small fixes to the formatting that comes out of that script.

Reference fixes for website publication crawler

---

.github/workflows/checks.yml

This is to avoid cluster of actions getting triggered every time a pull request is commented on or mentioned in a separate issue, etc... :angry:

GitHub Actions: don't trigger on pull request edited

---

core/math/zstatistic.cpp

Warning regarding comparison between signed and unsigned integers on some compilers under Eigen 3.2.

Math::Zstatistic: Fix compiler warning

---

core/math/stats/import.h

Fixes issue reported on [forum](https://community.mrtrix.org/t/connectomestats-unable-to-load-all-input-data-error/3595/5).
Fixes issue where an exception is erroneously thrown when the subject filename list resides in the current working directory, and no template directory is defined. 
Error arising from #1977.
It is possible to bypass the issue by simply prepending the path to the subject file list with "`./`"; nevertheless targeting at `master` since it's a bug.

CohortDataImport::initialise(): Fix for cwd

---

bin/dwifslpreproc

Caused mrtransform to fail when the number of se_epi images made it interpretable as SH coefficients (e.g. 6)

dwifslpreproc: add missing reorient_fod option

---

core/progressbar.cpp
core/progressbar.h

Minor issue reported by @dchristiaens , but fixes a problem left over from #1586. This only influences the progressbar updates when redirected away from the terminal. 
Example for a simple mrconvert DICOM to nii conversion:
```
mrconvert 3dfl/ anat.nii 2> log.txt
```
Content of `log.txt` using current `master`:
```
done
============================================]
=====================]
```
Content of `log.txt` using this PR:
```
mrconvert: scanning DICOM folder "3dfl/"... done
mrconvert: reading DICOM series "fl3D_1x1x1_tra"... [==================================================]
mrconvert: copying from "XXXXXXXX...ri vol) [MR] fl3D_1x1x1_tra" to "anat.nii"... [==================================================]
```

progressbar: fix behaviour under redirection

---

bin/dwifslpreproc

As reported on [forum](https://community.mrtrix.org/t/invalid-dwi-scheme-after-dwifslpreproc/3715).
Bug is the consequence of #1389.
Unfortunately it seems nobody used explicit volume recombination on `dev` for the last two years, I didn't spot the issue, and the script test suite has to call `testing_diff_header` without the `-keyval` flag because `eddy` is stochastic...

dwifslpreproc: Don't discard modified dw_scheme

---

cmd/mtnormalise.cpp

I'd add a warning to prevent accidental use of only one component in `mtnormalise`. This issue came up when debugging a user's analysis.
```
$ mtnormalise wm.mif wm_norm.mif -mask mask.mif
mtnormalise: [WARNING] Only one contrast provided. If multi-tissue CSD was performed, provide all components to mtnormalise.
mtnormalise: [100%] performing log-domain intensity normalisation
```

mtnormalise: warn if only one contrast provided

---

.github/workflows/checks.yml
.readthedocs.yml
docs/README.md
docs/conf.py
docs/getting_started/image_data.rst
docs/installation/build_from_source.rst
docs/requirements.txt

As discussed recently - [preview here](https://mrtrix.readthedocs.io/en/doctest/installation/build_from_source.html). I think this addresses everything that we'd talked about, other than the latter half of this specific point:
> - May want to include explicit statement about Python3 being preferable but that depending on the distro there is a chance of Python2 being inadvertently pulled in
I'm not sure we need to go into this amount of detail, especially in light of #2047...

Updates to installation documentation

---

bin/dwifslpreproc

Modification resulting from my own needing to be able to catch eddy errors and modify parameters accordingly within an automated pipeline; but likely beneficial for users executing the script directly as well.
Basically, if the CUDA version of `eddy` fails, the resulting error message gets essentially hidden, because the exception is caught, the OpenMP version is run, and the error message produced by that version may give no insight into why the CUDA version failed.
With this change, if both the CUDA and OpenMP versions of `eddy` fail, the resulting error messages are concatenated into a single exception. When that is raised, the user (/ wrapping script) is provided with the terminal outputs generated by both versions of the command, enabling proper diagnosis.

dwifslpreproc: eddy error message

---

cmd/mrcolour.cpp
docs/reference/commands/mrcolour.rst
src/colourmap.cpp
testing/binaries/tests/mrcolour

This PR adds two of my favourite colour maps, [viridis and inferno](https://bids.github.io/colormap/) to `mrview` and `mrcolour`. As opposed to _jet_ and others, these are perceptually uniform and also much more friendly to colourblind people.
Viridis:
Inferno:
The implementation uses a 6th order polynomial approximation published [here](https://www.shadertoy.com/view/WlfXRN) (public domain; CC0 license). Using this approximation seems a better fit with the MRtrix3 codebase than defining the [lookup tables](https://github.com/BIDS/colormap/blob/master/colormaps.py) of the original colour maps. I have compared them in python and they seem to be a fairly good match (shown here for inferno).
**Question:** Personally, I strongly prefer _inferno_ and _viridis_ over the _hot_ and _cool_ colour …

mrview: add viridis colour maps and fix PET colour map

---

cmd/mrthreshold.cpp

#2086 has become bloated showing commits that are unrelated, probably because it was initially configured as a merge to `dev`. But I do think I'd consider this a bug, so I've done a clean cherry-pick and made a new PR.

mrthreshold: Suppress progressbars if writing to cout

---

run_tests

As discussed in #1517.
Will permit execution of tests when using pre-compiled binaries by explicitly downloading the relevant test data into the appropriate location. No guarantee is provided with respect to correspondence between software and test data versions.

run_tests: Permit running with manually-downloaded test data

---

cmd/mrconvert.cpp
docs/fixel_based_analysis/mt_fibre_density_cross-section.rst
docs/fixel_based_analysis/st_fibre_density_cross-section.rst
docs/quantitative_structural_connectivity/ismrm_hcp_tutorial.rst
docs/reference/commands/mrconvert.rst

There were a few places with leftover `mrresize` examples in the docs as reported in the [forum](https://community.mrtrix.org/t/mrresize/3589/2)

docs: replace mrresize by mrgrid

---

bin/dwifslpreproc

Script provides `eddy_quad` with the spline field rather than the image in Hz; as a result `eddy_quad` produces an error like:
```
Traceback (most recent call last):
File "/software/FSL/fsl6/bin/eddy_quad", line 54, in <module>
main(args.eddyBase, args.eddyIdx, args.eddyParams, args.mask, args.bvals, args.bvecs, args.output_dir, args.field, args.slspec, args.verbose)
File "/software/FSL/fsl6/fslpython/envs/fslpython/lib/python3.7/site-packages/eddy_qc/QUAD/quad.py", line 345, in main
eddyOutput['std_displacement'] = np.std(dispField[data['mask'] != 0.0])
IndexError: boolean index did not match indexed array along dimension 0; dimension is 51 but corresponding boolean dimension is 96
```

dwifslpreproc: Fix eddy_quad susceptibility field

---

src/gui/dwi/render_frame.cpp

This should fix #2121. Needs testing on a Qt4 installation though, I can't do this easily on Arch...

don't use QWheelEvent::pixelDelta() on Qt<5.5

---

src/dwi/sdeconv/msmt_csd.h

This was due to uninitialised rows in the transform matrix when some of the volumes were left out.
This fixes #2129 - see also [discussion on the forum](https://community.mrtrix.org/t/dhollander-response-function-estimation/3895?u=jdtournier).

dwi2fod: fix error when volumes not assigned to shells

---

cmd/connectomestats.cpp
cmd/fixelcfestats.cpp
cmd/mrclusterstats.cpp
cmd/vectorstats.cpp

Prior change in the implementation of strong FWE control, changing the command-line option from receiving a boolean to being a flag, was not propagated to the point in code at which that option was read. This however now results in an error upon attempting to use that option due to merge of #1794, as it erroneously attempts to convert the next item on the command-line following the `-strong` option to a double.

Stats commands: Fix -strong option

---

cmd/mrtransform.cpp
docs/reference/commands/mrtransform.rst

For options that receive multiple command-line inputs, the names of those arguments are space-separated; it is therefore preferable for the description of an option that receives only one command-line input to not have space separators in its name.

mrtransform: Tweak -modulate option help

---

cmd/mrtransform.cpp

If the input image does not contain any diffusion gradient table, and a linear transformation is applied, do not issue a warning about the failure to reorient gradient directions.

mrtransform: Prevent erroneous warning

---

lib/mrtrix3/dwi2response/tournier.py

Created whilst doing a quick investigation regarding [this forum post](https://community.mrtrix.org/t/dwi2response-error-iter0-fixel-peaks-mif/4010); don't think it is actually a solution, but would nevertheless prefer that the appropriate function be used rather than the "`/`'" character.

dwi2response tournier: Use os.path.join()

---

.gitmodules
run_tests

This is to allow binary packages to be tested. To use, make sure you
have a clone of the MRtrix3 repo checked out, and the binary package you
want to test is installed. Then set the MRTRIX_BINDIR environment
variable to point to the location of the executables to be tested, and
invoke run_tests. For example:
```
MRTRIX_BINDIR=~/miniconda3/bin/ ./run_tests binaries
```

run_tests: allow different location for MRtrix executables

---

docs/installation/build_from_source.rst

As described in #2142. 
I have some recollection of a discussion where Qt 5.05 would be a more specific minimum requirement; anyone recall?

Docs: State Qt5 as GUI requirement

---

core/filter/resize.h

mrgrid: ensure no oversampling when using nearest-neighbour interpolation

---

cmd/dwi2tensor.cpp
cmd/dwidenoise.cpp
cmd/sh2peaks.cpp

This was originally intended to fix #2148, but now includes other similar fixes elsewhere.

Remove copy_ptr and fix handling of masks when more than 3D

---

cmd/connectomestats.cpp
cmd/fixelcfestats.cpp
cmd/mrclusterstats.cpp
cmd/vectorstats.cpp

Arose from discussion on [forum](https://community.mrtrix.org/t/connectomestats-fwe-correction/3348/6).
Potential for similar confusion regarding uncorrected *p*-value files as there can be for FWE-corrected *p*-values, in that the values stored are actually (1-*p*).

Inference: Change filename of uncorrected p-values

---

lib/mrtrix3/dwibiascorrect/fsl.py

Terminal warning issued to user was copy&pasted from `3.0_RC3`, but not properly modified to reflect the changes to the `dwibiascorrect` interface introduced in `3.0.0`.
As observed in nipy/nipype#3248 by @effigies.

dwibiascorrect fsl: Revise warning

---

core/adapter/reslice.h
core/filter/resize.h

modification to fix for #2158: warn in the reslice adapter used in the resize filter in mrgrid if the user provides oversample != 1 when nearest neighbour interpolation is requested.
```
mrgrid int.mif -voxel 8 -interp nearest regrid - -oversample 2 | mrview -
mrgrid: [WARNING] oversampling factors ignored for nearest neighbour interpolation
mrgrid int.mif -voxel 8 -interp nearest regrid - | mrview -
```

resize filter, adapter and reslice adapter: more explicit nearest interpolation and oversample handling

---

core/algo/loop.h

For some reason, constructing a Loop object from a `std::initializer_list` causes compiler warnings about uninitialised variables and outright crashes when compiling with `g++` (not a problem with `clang`). This feature is completely unused on the main repo anyway, this only manifests as an issue with `mrpeek`. I propose to simply remove it and fallback on constructing from a regular vector (which works fine anyway).

Loop(): remove constructor from initializer_list

---

build

Thanks to @spinicist for the tip.
This will no doubt help to increase portability.

When building a -noshared configuration, statically link libgcc and libstdc++

---

bin/dwifslpreproc

This I think makes sense as a solution.
I don't know for certain, but what I think has happened is that prior to integration in FSL6, `eddy_quad` required Python3, whereas now in FSL6 it gets an FSLPython shebang and so needs to be executed as-is.
This approach should succeed on first attempt for anyone with FSL6 installed, whereas for any systems that happen to have FSL5 combined with an EddyQC installation from source it'll still make a second attempt by explicitly invoking the Python3 compiler.

dwifslpreproc: For EddyQC, don't invoke Python3 interpreter

---

cmd/fixelconvert.cpp
cmd/fixelcrop.cpp
cmd/fixelfilter.cpp
core/fixel/helpers.h
core/image_diff.h
run_tests
testing/binaries/tests/fixelconvert
testing/binaries/tests/fixelcorrespondence
testing/binaries/tests/fixelcrop
testing/binaries/tests/fixelreorient
testing/binaries/tests/tckconvert
testing/binaries/tests/voxel2fixel
testing/binaries/tests/warp2metric

Argument "`bool check_if_empty`" of function "`Fixel::check_fixel_directory()`" was only set to `true` for commands `fod2fixel` and `peaks2fixel`. Everything else is currently set up to be permissive of existing & non-empty output fixel directories. I have decided that `fixelconvert` and `fixelcrop` should also not be permissive of such. Other commands cannot enforce this requirement due to allowing the same directory to be defined for both input & output.

Tweak error message on failed fixel overwrite

---

core/interp/base.h
core/interp/masked.h
core/interp/sinc.h
src/dwi/tractography/ACT/method.h
src/dwi/tractography/algorithms/fact.h
src/dwi/tractography/algorithms/iFOD1.h
src/dwi/tractography/algorithms/iFOD2.h
src/dwi/tractography/algorithms/nulldist.h
src/dwi/tractography/algorithms/sd_stream.h
src/dwi/tractography/algorithms/seedtest.h
src/dwi/tractography/algorithms/tensor_det.h
src/dwi/tractography/algorithms/tensor_prob.h
src/dwi/tractography/tracking/exec.h
src/dwi/tractography/tracking/method.h
src/dwi/tractography/tracking/types.h
testing/binaries/tests/tckgen

As originally reported directly by @cbajada, then posted on [forum](https://community.mrtrix.org/t/unwanted-results-using-act-tractography-with-hcp-data/2419), but I neglected to list on GitHub and hence a fix was erroneously omitted from `3.0.0`.
I second-guessed myself a bit as to how exactly I wanted to go about this, as there were a few different options, but I won't bother boring with the full details unless there are questions or concerns.
One outstanding issue is that I'm going to have to modify the test data. Can't have the transition from >=50% WM, <50% GM to <50% WM, >=50% GM align perfectly with the voxel transition from present FOD to absent FOD, as this change now means that there's no valid DWI data just inside of the GM.

[BUG] tckgen: Fix absent CST with ACT

---

core/file/nifti_utils.cpp

@jdtournier: This removes the warning for me on a dataset where the error was appearing.
I was just printing out variable contents and noted that the 3x3 matrix produced from Q was identical to R until the `Q.w` check resulted in negating the vector, which changed the matrix (some elements unchanged, others changed by maybe 1e-3).
I always lose my understanding of quaternions as soon as I'm finished dealing with whatever code uses them, plus there's the confound of NIfTI peculiarities, so I'm handing this one off to you if it needs to be resolved in a different way.

NIfTI: Fix verification of rigid transform

---

cmd/labelconvert.cpp

As reported on [forum](https://community.mrtrix.org/t/tracks-passing-through-brainstem-counted-for-connectome/427/4).
Even if this isn't the actual source of confusion for the user, it nevertheless makes sense that if the command-line option is not going to achieve its purpose properly due to not having a target parcel index, the command should not be executing.
I've also promoted the case where "`Spinal_column`" is specified *multiple times* in the output parcellation from a warning to an error.

labelconvert: Error if -spine used but absent from LUT

---

cmd/vectorstats.cpp
core/math/stats/import.h

For some experiments, it may be preferable for the primary input to the `vectorstats` command to be the raw data in matrix form, rather than a list of files (each of which contains numerical vector data) (which is consistent with the interface of other statistical inference commands). This change attempts data import based on the user-specified argument using both approaches.
Draft pull request as I am awaiting generation of data for which the change is intended.

vectorstats: Permit numerical matrix data as input

---

docs/concepts/afd_connectivity.rst

It was always my intention that the explanations provided in the "quantitative structural connectivity" manuscript would supersede the contents of this documentation page. Once the manuscript is properly published we can discuss how the software documentation may or may not change; but for now I think it's worth throwing a hyperlink to the preprint in there, since for anyone interested in such concepts it's going to be a better reference than that text-only documentation page.

Docs: afdconnectivity: Link to preprint

---

cmd/dirstat.cpp

Slight tweak so that the printout for shells with between 6 and 14 directions makes a little more sense.

dirstat: Nicer printout for < 15 direction shells

---

cmd/tckconvert.cpp
docs/reference/commands/tckconvert.rst
testing/binaries/tests/tckconvert

This change enhances the functionality of `tckconvert` by enabling writing `vtkPolyData` files (`.vtk`) in a binary format.  In addition to being faster because floats do not need to be converted to ASCII, the files are smaller.
This PR does not have a corresponding test at this moment.
To use the new format:
`tckconvert -binary streamlines.tck streamlines.vtk`
Writing the new VTK XML format (`.vtp`) is preferred and may be the subject of a future PR.
@jdtournier @Lestropie

Write binary vtkPolyDataFiles

---

core/file/mgh.h

If a MGH / MGZ file that internally contains a version 2 colourfile is read by *MRtrix3*, and then *MRtrix3* writes out a new MGH / MGZ that contains the header key-value data corresponding to the colourfile loaded in the first step (`MGH_TAG_OLD_COLORTABLE`), the resulting output file cannot be read by either FreeSurfer or *MRtrix3*. This is because until now I had never actually come across an MGH / MGZ file that contained such information, and therefore could not verify my load / save functions; the format is undocumented, so I had essentially incorrectly duplicated the FreeSurfer C code.
Full evidence below shows two MGH files generated from the original FreeSurfer MGZ: one with *MRtrix3* `master` code and one with the changes in this PR; all three of these files are then read by …

MGH/MGZ: Fix Colortable V2 write

---

core/app.h

Came across this while thinking about #1975. While the current `get_option_value()` code is permissive, this theoretically enables erroneous usage of the function by developers. This change constrains usage of the function to only those command-line options for which the usage of this function makes sense.

get_option_value(): Restrict usage

---

bin/for_each

In situations where the output of each failed command is long, it is beneficial for the final error message at the end of the terminal printout to state succinctly which inputs were not successfully processed.
```
[rob@rsmithmetabox mrtrix3]$ for_each 1 2 3 : [[ IN -eq "2" ]]
for_each: [100%] 3/3 jobs completed sequentially (2 errors)
for_each: [WARNING] 2 of 3 jobs did not complete successfully
for_each: [WARNING] Outputs from failed commands:
for_each:
for_each: [WARNING] No output from command for input "1" (return code = 1)
for_each:
for_each: [WARNING] No output from command for input "3" (return code = 1)
for_each:
for_each: [ERROR] 2 of 3 jobs did not complete successfully: ['1', '3']
[rob@rsmithmetabox mrtrix3]$
```

for_each: Tweak error message

---

configure
src/gui/dialog/opengl.cpp
src/gui/dwi/render_frame.cpp
src/gui/mrview/mode/volume.cpp
src/gui/mrview/tool/connectome/node_list.cpp
src/gui/mrview/window.cpp
src/gui/opengl/font.cpp
src/gui/opengl/gl.cpp
src/gui/opengl/gl.h
src/gui/projection.h

Second half of #2142: where the first half (#2153) only alters documentation on `master`, this goes to `dev`, and involves removing support for anything prior to 5.5 and performing corresponding checks.

Enforce Qt5

---

docs/reference/commands/mrview.rst
src/gui/mrview/window.cpp

As the name implies... Requested by @bjeurissen. 
Not ideal in that the orientation needs to be provided as a comma-separated 4-vector, which isn't massively intuitive. In due course, we'd want to add options to manipulate the orientation more meaningfully, akin to [Matlab's campan, camzoom, camorbit, etc functions](https://uk.mathworks.com/help/matlab/referencelist.html?type=function&category=views). But this would be in addition to this particular option, so I reckon we can merge this now anyway.

mrview: add -orientation cmdline option

---

cmd/dirmerge.cpp

This ensures that single-PE schemes generated by `dirmerge` (and hence `gen_scheme`) don't have an unnecessary 5th column if there is only one PE/subset (in which case that 5th column would contains 1's only).

dirmerge: don't output a 5th column if single subset

---

.github/workflows/checks.yml

See if this addresses outdated version of pylint pulled by GitHub runner as commented in #2215.
Opening a second PR in the hope that it triggers the "`secondary-checks`" GitHub Action, for which I've created a dedicated branch protection rule specifically for this PR.

CI: Try installing "python3-pylint" rather than "pylint3" (Take 2)

---

bin/dwifslpreproc

Fixes case where there is no phase encoding contrast present in the SE_EPI images (and hence they need to be combined with the DWI b=0 data for tuopup to possibly be applicable), and also the SE-EPI volumes are defined on a different image grid to the DWIs.
I thought that this one had already been fixed; not sure if it got reverted in a merge or something. Exceptionally unlikely use case (I only came across it myself due to a partially overwritten dataset).

dwifslpreproc: Fix for rare usage

---

cmd/dwidenoise.cpp

As reported on the [forum](https://community.mrtrix.org/t/dwidenoise-system-fatal-code-sigsegv-11-segmentation-fault-invalid-memory-access/2302/31).
If the user sets a patch size larger than the image dimension, this will throw an error.
If the patch size is selected automatically, it will be truncated to the image dimensions.

dwidenoise: limit patch size to image dimensions

---

cmd/afdconnectivity.cpp
cmd/mrtransform.cpp
cmd/tcksift2.cpp
docs/reference/commands/afdconnectivity.rst
docs/reference/commands/mrtransform.rst
docs/reference/commands/tcksift2.rst

Adding links to preprint within command help pages that probably should have been done in conjunction with #2201.

Minor command docs updates

---

bin/dwifslpreproc

As reported on [forum](https://community.mrtrix.org/t/dwifslpreproc-unhandled-python-exception/4335).

dwifslpreproc: On -rpe_pair, ensure -se_epi is 4D

---

core/app.cpp

Fixes issue when double-clicking quarantined files on macos.

---

lib/mrtrix3/dwi2response/dhollander.py

This simply clamps values of the input data at zero before taking their mean per-shell, which seems to fix issues raised in #2248.

dwi2response dhollander: fix handling of data with negative values

---

cmd/tckglobal.cpp

The tckglobal command when run with `-niter 10B` could only run for `1410065408` iterations instead of `10000000000` iterasions. These changes fixed the parsing issue.

tckglobal: Fix erroneous -niter parsing for values bigger that 1.4e9

---

cmd/mrtransform.cpp

Small tweak to prevent 'regridded to template image...' and 'resliced using warp image...'  from being written to the image comments. For `.mif`, this information is in the command history anyway and `mrmath` or `mrcat` tend to accumulate these comments when operating on multiple files.

mrtransform: write fewer comments 

---

core/math/stats/glm.cpp

Fixes case where GLM varies between elements (either due to the presence of non-finite values, or the addition of element-wise design matrix columns) *and* variance blocks are defined. Code pre-fix generates an assertion failure, but may proceed if compiled in release mode. But having said that, it's entirely likely that nobody other than myself has even attempted to use this kind of functionality yet.
Intention is for there to be more significant changes to this code in `3.1.0`, but should nevertheless patch this as it currently stands.

Inference: Fix for exotic usage

---

lib/mrtrix3/image.py

Discussed in #2248
I consider this a bug fix, but I suggest merging to `dev` given there is scope for this to change behaviour of existing apps. Up for discussion.

python: fix handling of N/A output in image.statistics()

---

bin/dwifslpreproc

As reported on [forum](https://community.mrtrix.org/t/dwifslpreproc-output-is-the-same-as-input/4266/5).
Follow-up to #2150.
Main issue was that if `-topup_files` or `-eddy_options "--topup="` was used in conjunction with `-rpe_none`, then variable `applytopup_cmd` would not be initialised.

dwifslpreproc: Cleanup for addition of -topup_files option

---

cmd/dirorder.cpp

Downstream of #1800, which introduced the functionality of determining the optimal reordering of directions for all possible selections of first volume, and choosing the optimal reordering from that set. Algorithm produces a segmentation fault if fewer than six input directions. This change forces the first volume in the input to be the first volume in the output in such scenarios (as there is no objective criterion by which to determine which direction is best to use first in this scenario).
Closes #2271.

dirorder: Fix segfault

---

src/dwi/tractography/SIFT/sifter.cpp

This warning message seems to result very frequently in users coming to the forum asking for help. Maybe not having it pop up in red text might help.

tcksift: Downgrade quantisation check message

---

src/dwi/fmls.cpp
src/dwi/fmls.h

As recently re-raised on [forum](https://community.mrtrix.org/t/fixel2voxel-how-to-extract-primary-secondary-and-tertiary-voxel-based-fd-maps/4394).
Here's the output of `fod2fixel` then `fixel2voxel none` on FD from the test data:
Old code:
New code:
Kinda hard to see, but there are some voxels in the top image that get brighter going from left to right, whereas in the lower image FD always decreases from left to right.

fod2fixel: Order fixels by FD

---

README.md

Fixes divergence between online documentation / actual internal requirements and the contents of `README.md`. Though as noted in #2279, there is some question as to whether such instructions should actually still remain in the latter.

README: Update to reflect revised dependencies

---

cmd/fod2fixel.cpp

As raised on [forum](https://community.mrtrix.org/t/a-warning-in-the-fixel-pipeline/4531).
I had in 61bfc64d prevented non-identity transform / voxel spacing info from being written to fixel data files, but only in the helper function `data_header_from_index()`, whereas `fod2fixel` does this same process manually.

fod2fixel: Wipe transform / spacing info from fixel data files

---

docs/reference/commands/mrview.rst
src/gui/mrview/tool/tractography/track_scalar_file.cpp
src/gui/mrview/tool/tractography/track_scalar_file.h
src/gui/mrview/tool/tractography/tractography.cpp

The pull request introduce two minor modifications of the command line of mrview related to the following discussion:
https://community.mrtrix.org/t/help-for-changing-the-colormap-of-tsf-file-in-command-line/4433
https://community.mrtrix.org/t/adding-command-line-option-to-mrview-to-set-tractography-colors/2453
1) tractography.tsf_colourmap  (allow to load a tsf file for each tractogram ) 
2) tractography.colour  (allow to specify the  rgb value of the tractogram )
tractography.tsf_colourmap  is working but the gui has not been updated
tractography.colour is half -working : if you load a second tractogram with a different color , the previous color is reset to the new one which make the option not so usefull. 
The code is more a hack than a clean version. I would be interested in knowing …

add two new command lines option in mrview for tractogram

---

src/gui/mrview/window.cpp

What it says in the title. This one has been giving me the irrits for a while, I finally decided it had to be sorted out... 
Issue manifests when adding a clip plane, then hitting the 'invert' button: this deselects the clip plane and you can't then select it again. Only way around it is to untick it and tick it again, which seems to sort this out temporarily. Other way to trigger this is to add two clip planes, then try to select both or something...

mrview: fix glitch in handling of clip plane selection

---

lib/mrtrix3/app.py

Closes #2292.
Before:
```
SYNOPSIS
Perform B1 field inhomogeneity correction for a DWI volume series
USAGE
dwibiascorrect [ options ] algorithm ...
algorithm    Select the algorithm to be used to complete the script operation;
additional details and options become available once an
algorithm is nominated. Options are: ants, fsl
```
After:
```
SYNOPSIS
Perform B1 field inhomogeneity correction for a DWI volume series
USAGE
dwibiascorrect algorithm [ options ] ...
algorithm    Select the algorithm to be used to complete the script operation;
additional details and options become available once an
algorithm is nominated. Options are: ants, fsl
```

Fix help page for algorithm module

---

core/math/stats/glm.cpp

As reported in #2289.
Fixes segmentation fault in case where:
1. Either:
1. Input data contain non-finite values (regardless of whether or not those data are or are not within the statistical inference processing mask);
2. Element-wise design matrix columns are added via `-column` option;
2. At least one F-test is performed.
Fairly obvious blunder even without explaining the surrounding code.

GLM: Fix all_stats() segfault

---

.github/workflows/checks.yml
bin/dwi2response
bin/dwifslpreproc
bin/for_each
bin/population_template
cmd/mrregister.cpp
lib/mrtrix3/_5ttgen/hsvs.py
lib/mrtrix3/run.py

Fixes the error reported in the [community](https://community.mrtrix.org/t/multi-contrast-population-template/4701/6). Also added more verbose error messages to `population_template`

mrregister: fix lmax check for nonlinear multi contrast registration

---

.github/workflows/checks.yml
bin/dwi2response
bin/dwifslpreproc
bin/for_each
bin/population_template
cmd/dirorder.cpp
cmd/mrregister.cpp
cmd/tckglobal.cpp
core/math/stats/glm.cpp
docs/reference/commands/mrview.rst
lib/mrtrix3/_5ttgen/hsvs.py
lib/mrtrix3/app.py
lib/mrtrix3/dwi2response/dhollander.py
lib/mrtrix3/image.py
lib/mrtrix3/run.py
src/dwi/tractography/GT/particlegrid.cpp
src/gui/mrview/tool/tractography/track_scalar_file.cpp
src/gui/mrview/tool/tractography/track_scalar_file.h
src/gui/mrview/tool/tractography/tractography.cpp
src/gui/mrview/window.cpp

Supersedes #2302. Independent branch necessary to resolve merge conflicts due to differential treatment of Python2 on `dev` (support dropped entirely in #2215) versus `master` (patch fix for CI in #2300).

Master to dev

---

src/gui/mrview/window.cpp

Deactivating the pan gesture to avoid spurious start and finish and sticky pan (remains in GestureUpdated state) reproducible by rendering things with latency, for instance via increased ODF render detail in ortho view mode:
Prior to this change with Qt 5.15.2:
```
QGestureEvent((QPanGesture(state=GestureStarted,lastOffset=0,0QPointF(0,0),offset=0,0,acceleration=1,delta=0,0)))
QGestureEvent((QPanGesture(state=GestureFinished,lastOffset=0,0QPointF(0,0),offset=0,0,acceleration=1,delta=0,0)))
QGestureEvent((QPanGesture(state=GestureStarted,lastOffset=0,0QPointF(0,0),offset=0,0,acceleration=1,delta=0,0)))
QGestureEvent((QPanGesture(state=GestureFinished,lastOffset=0,0QPointF(0,0),offset=0,0,acceleration=1,delta=0,0)))
QGestureEvent((QPanGesture(state=GestureStarted,lastOffset=0,0QPointF(0,0),o …
```

mrview: deactivate pan gesture to avoid #761

---

bin/dwifslpreproc
core/formats/tiff.cpp
core/image_io/tiff.cpp

The FSL `eddy` commands sometimes contain a small block of binary data at the end of their outputs. If, when attempting to write those data to a text file in the scratch directory, an encoding operation occurs, such data may yield a `UnicodeEncodeError`. This commit changes the output text files to be opened in binary mode, so such an encoding should no longer be applied.
(Note that `__str__()` is [defined](https://github.com/MRtrix3/mrtrix3/blob/3.0.2/lib/mrtrix3/run.py#L192-L193) for `MRtrixCmdError` as a straight concatenation of `stdout` and `stderr` contents, so there shouldn't be any `ascii` conversion happening there)

dwifslpreproc: Handle non-ascii data in eddy error outputs

---

Dockerfile
README.md
Singularity
docs/index.rst
docs/installation/using_containers.rst

As discussed in MRtrix3/containers#14.
Plan is to have the primary container building recipes inside the main repository, and for the "`containers`" repository to only be responsible for building the minified dependencies.
1. In order for the recipe file contained within any particular tagged version of *MRtrix3* to be guaranteed to clone that very same version of *MRtrix3* during the build process, the recipe files must be manually updated to reflect the upcoming tag name, similarly to the gymnastics already done with `core/version.h`. The [Wiki instructions](https://github.com/MRtrix3/mrtrix3/wiki/Publishing-a-new-release#merge-to-master) have already been updated accordingly.
2. I have moved some of the contents of `README.md` from the `containers` repo into a new page in the online …

Container recipes

---

bin/dwifslpreproc

#2313 can raise an Exception due to expecting bytes data but receiving string data.
I think part of the issue was that I forgot that #2191 is outstanding. While this PR prevents `dwifslpreproc` from erroring, there is a debate to be had w.r.t. the point at which text decoding should take place. Hopefully dropping Python2 support will simplify this discussion somewhat, though I still have to re-familiarise myself with the revised string handling...

dwifslpreproc: Fix eddy text file outputs (again)

---

core/app.cpp
docs/reference/environment_variables.rst
lib/mrtrix3/app.py
lib/mrtrix3/image.py
lib/mrtrix3/run.py

This environment variable modulates the terminal verbosity of commands in the same fashion as the -quiet / -info / -debug command-line options.
The contents of this environment variable are utilised by the Python API to affect the verbosity of any *MRtrix3* commands that it invokes, rather than explicitly adding the -info flag to the execution string when relevant.
The `MRTRIX_QUIET` environment variable remains, and supersedes `MRTRIX_LOGLEVEL`.
Additional fixes include Python commands now correctly honouring `MRTRIX_QUIET`, and progress bars in Python scripts no longer being erroneously displayed when the log level is zero.
Fixes #2268.
Assigned to `3.0.4` initially, but can be promoted to `3.0.3` pending team discussion.

New envvar MRTRIX_LOGLEVEL

---

core/file/dicom/dict.cpp

Fixes a minor error in the DICOM dictionary, probably caused by a glitch in the initial automated import from the DICOM specs.

DICOM: fix formatting error in dictionary

---

configure

Spawned by [forum thread](https://community.mrtrix.org/t/compiling-mrtrix-with-json-for-modern-c/4918/3).

configure: Add libpng envvars to usage string

---

core/file/nifti_utils.cpp
src/gui/mrview/tool/overlay.cpp

Fixes #2344.
On loading one image in `mrview`, then attempting to load within the Overlay tool a `.img` file that does not have a corresponding `.hdr` file:
<details>
<summary>master:</summary>
```
[rob@BRI-Pub-122 diffusion]$ gdb --args mrview fa.mif 
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual …
```

mrview Overlay: Fix segfault on bad image load

---

bin/dwigradcheck
docs/reference/commands/dwigradcheck.rst

Some users pointed out to me that it was not obvious how to obtain the corrected gradient table with dwigradcheck.

dwigradcheck: explain how to obtain corrected gradient table

---

src/gui/mrview/tool/odf/model.h
src/gui/mrview/tool/odf/odf.cpp

Currently, ODF path and file names are truncated and fixed length:
Eliding text and responsive widget width (this PR):
I tried scrolling full file names (only modify `src/gui/mrview/tool/odf/model.h`):
but the scroll bar is not shown and it's located left on load:
So I'd go with the sliding option. This is at least a partial fix for #937.

mrview: elide ODF file names 

---

Dockerfile
Singularity
core/version.h
docs/reference/commands/afdconnectivity.rst
docs/reference/commands/amp2sh.rst
docs/reference/commands/dwi2fod.rst
docs/reference/commands/fixel2sh.rst
docs/reference/commands/sh2amp.rst
docs/reference/commands/sh2peaks.rst
docs/reference/commands/sh2power.rst
docs/reference/commands/sh2response.rst
docs/reference/commands/shbasis.rst
docs/reference/commands/shconv.rst

Replacement of #2355.
f89e89c4 replaces e14597c6 by including requisite change to container recipes.
NOT TO BE MERGED; is only to be used for a final CI run.

Release 3.0.3 (take 2)

---

Dockerfile
Singularity

As per comment in #2356.
The theory here is that:
- If someone checks out the code in `3.0.3`, and then builds a container using one of the recipe files, during the building of that container it should download and compile the *MRtrix3* code specifically at tag `3.0.3`, regardless of how `master` may have changed after that point;
- If someone checks out the code in `master`, and then builds a container using one of the recipe files, during the building of that container it should download and compile whatever the *MRtrix3* `master` branch is pointing to at that point in time, regardless of what tags may or may not have been added.
(Better would be if, during container build, it would check out the *MRtrix3* code at the commit hash corresponding to the code version of the recipe that is …

Revert container recipes to pull master

---

bin/mask2glass
docs/reference/commands/mask2glass.rst
docs/reference/commands_list.rst

New command "mask2glass" written, which automatically generates a "glass brain" image for visualisation purposes, using a mask image as input. This visualisation technique has been used in publications using fixel-based analysis, and has been requested from members to apply to their own independent research.

New command "mask2glass"

---

bin/dwifslpreproc

As discussed on the forum: https://community.mrtrix.org/t/dwifslpreproc-error-somewhere-after-the-topup-process/5248/4
This is to avoid potential mismatch with the original DWI series in the subsequent mrcat call, which can result in the DW scheme being labelled as 'variable' and removed altogether. This will fix that specific issue in `dwifslpreproc`, and should be merged to `master` ASAP given there's now been several reports of this particular problem.
In due course, we'll need to discuss what the correct behaviour ought to be here. It doesn't seem right for a slight mismatch to lead to an actual loss of information. I would also be keen to find a _general_ solution, rather than just patch up this specific use case. I think that'll need a separate discussion though...

dwifslpreproc: strip DW encoding from padding slice

---

README.md

Stolen idea from: https://github.com/bids-standard/bids-specification/blob/master/README.md
They also have a DOI badge, but it appears to be a feature specific to Zenodo.

README.md: Add Twitter reference

---

docs/concepts/fixels_dixels.rst

Tiny fix affecting [Fixel docs page ](https://mrtrix.readthedocs.io/en/latest/concepts/fixels_dixels.html)
Based on previous versions of this file I'm assuming this double negative snuck in by accident. Could also be rewritten as _"are ~not~ applied inconsistently"_
Sidenote, I figured it would be overkill to open an issue about this, but do let me know if that would have been preferred. The contributing [guidelines](https://github.com/MRtrix3/mrtrix3/blob/master/CONTRIBUTING.md) are somewhat vague when it comes to documentation, and since the `doc` branch hasn't been updated in two years, I went with `master` as base.

Documentation (Fixels and Dixels): double negative typo

---

bin/blend
bin/convert_bruker
bin/dwicat
bin/dwifslpreproc
bin/dwigradcheck
bin/dwishellmath
bin/for_each
bin/labelsgmfix
bin/mrtrix_cleanup
bin/population_template
build
configure
lib/mrtrix3/_5ttgen/hsvs.py
lib/mrtrix3/__init__.py
lib/mrtrix3/app.py
lib/mrtrix3/dwi2response/dhollander.py
lib/mrtrix3/dwi2response/tax.py
lib/mrtrix3/dwi2response/tournier.py
lib/mrtrix3/dwibiascorrect/ants.py
lib/mrtrix3/image.py
lib/mrtrix3/path.py
lib/mrtrix3/phaseencoding.py
lib/mrtrix3/run.py
lib/mrtrix3/utils.py
update_copyright

Follows on from discussion on #2392. Pushing to a new branch / pull request to preserve the changes originally submitted by @maxpietsch, many of which may be appropriate for `dev`. 
This PR disables a lot of warnings to allow compatibility with Python 2. These will be re-enabled on `dev` with a view to dropping Python 2 support in future releases. Minor fixes have been applied where that could be done safely without affecting Python 2 compatibility, and where the changes would be expected to carry over to `dev` anyway.
Most of the changes boil down to disabling the warnings at the file level, along with a note to deal with them in `dev`. The rationale is to help identify these when merging to `dev` - it's otherwise difficult to work out which warnings need to be addressed and which are …

minimal set of changes to pass pylint 2.11.1 tests

---

.github/ISSUE_TEMPLATE/bug_report.md

As mentioned in #2402, replace dead link with one to relevant wiki page on community forum.

Fix link to advanced debugging help page

---

CONTRIBUTING.md

Based on feedback in #2398.
@fionaEyoung: Would this text have been more appropriate in your opinion? Eager to remove barriers to contribution as much as possible.
@jdtournier: I figure the main barrier is not `dev` vs. `master` target so much as whether we need to check formatting; in which case we probably need to merge `master` into `docs` at our end, merge the external PR into `docs`, then it's our obligation to fix then merge `docs` into `master` or `dev`. Unless it's easy to configure docs building from external forks?

CONTRIBUTING.md: Revise text RE: target branch for docs changes

---

cmd/tensor2metric.cpp

Tensor2metric was segfaulting with multiple users on the forum when provided DWIs instead of tensors. On my own system the command even became unresponsive... This change checks if the input consists of 6 volumes and thus can be considered a tensor.

tensor2metric: avoid crash when supplying input with wrong size

---

src/dwi/tractography/file_base.cpp

As [discussed on the forum](https://community.mrtrix.org/t/tck2fixel-segmentation-fault/2497/11), if a `tck` file header contains an entry for the ROI that doesn't have the expected 2 fields, this leads to a segfault when using e.g. `tckinfo` or `tck2fixel`. For some reason, the user had a header entry of the form:
```
ROI: none
```
Whereas we would normally write something like:
```
ROI: seed mask.mif
```
i.e. two separate entries. 
The change here consists simply of making sure that if only one token is parsed, a second empty string is added as the second, which then avoids the invalid memory access, and permits these headers to be used (the alternative is simply to ignore them, but I'm not sure that's the best thing to do here).

Avoid invalid memory access when ROI is malformed in tck header

---

lib/mrtrix3/run.py

Default value for environment variable `MRTRIX_LOGLEVEL` was being erroneously written as an integer type rather than a string. In some environments, the `subprocess` module attempts to check whether environment variables correspond to filesystem paths, and this results in a `TypeError` due to this specific envvar not being a string.

mrtrix3.run: Fix default MRTRIX_LOGLEVEL

---

configure

The LTO options introduced with Qt 5.15 cause non-trivial conflicts with clang++ (at least it does on Arch Linux). I expect this will start to become problematic for other users soon. 
Looking at the flags added by Qt, it looks like they don't add much over what we normally use. It's probably just as easy to ignore the additional flags that `qmake` suggest (`CFLAGS` & `LDFLAGS`), and stick to grabbing only the main ones (`DEFINES`, `INCPATH` & `LIBS`). 
Works fine on Linux, will need checking on other OS's.

configure: ignore CFLAGS & LDFLAGS from qmake

---

core/math/sinc.h

Probably inconsequential, but nevertheless spotted it while investigating modifications for other reasons.
`bool(NaN == NaN) = False`

Math::Sinc: Fix validity assertions

---

cmd/connectomestats.cpp

In almost all use cases, bug resulted in use of GLM with variable design matrix per edge, which results in re-calculation of certain data for each edge when those data could have instead been pre-calculated for efficiency.
If anyone were to provide input data where the connectome matrices contained non-finite data, bug would have resulted in non-finite test statistics, which in turn would have been reported, so confident that nobody has thus far attempted to do so.

connectomestats: Fix GLM mode selection

---

core/file/dicom/element.cpp
core/file/dicom/element.h
core/file/dicom/image.cpp
core/file/dicom/image.h
core/file/dicom/mapper.cpp

Based on test data provided by @bjeurissen where some attributes were missing , namely `SliceTiming`, `EchoTime`, `MultibandAccelerationFactor` & `SliceEncodingDirection`. For some reason, fixing the slice timing import also fixed the MB factor and slice direction imports (presumably because [these are only carried over if the slice timings are known](https://github.com/MRtrix3/mrtrix3/blob/master/core/file/dicom/mapper.cpp#L345-L353)). 
The `EchoTime` can be imported correctly if we accept the `EffectiveEchoTime` as equivalent. Not sure whether that will cause problems down the track, but it probably feels safe enough for now...?

Dicom fix missing import siemens enhanced

---

cmd/tckconvert.cpp

The cap placed on the end of a streamline was incorrectly oriented
by the PLY writer.  Some 3D printing software will not correctly
recognize this condition and will ignore the endcaps.  Particularly
painful for 10's or 100's of thousands of streamlines!
A comment to the output PLY file is added clarifying the 
coordinate system and scale of the model.
This change is a bugfix and does not introduce new features, nor break
backwards compatibility.

Fixes incorrect face orientation in PLY output format

---

src/gui/mrview/tool/connectome/connectome.cpp

See issue raised on forum:
https://community.mrtrix.org/t/connectome-init-not-working-for-fastsurfer-outputs/

mrview connectome tool: fix display of nodes when a node is empty

---

bin/population_template

mrtransform was erroneously applied to the last contrast instead of the mask when initial alignment was turned off. Only happens when initial alignment is turned off, so most studies will not be affected by this.

Correctly transform mask instead of last contrast

---

build

Attempt at fixing #2492. Definitely fixes the variability in the total number, but there is still scope for the numbering to be slightly out of order at the beginning, due to a race condition between when the index of the current job is generated and the point at which the status line is printed to the terminal. This could be fixed properly, but would require slightly deeper changes, and I'm not sure they're necessarily all that important.

Fix build progress

---

cmd/tckconvert.cpp
docs/reference/commands/tckconvert.rst
testing/binaries/tests/tckconvert

replaces #2488, this time merging to `master` with VTK output still defaulting to ASCII. 
@blezek, could do with a second pair of eyes to double-check none of my changes break anything...

Tckconvert write binary vtk

---

lib/mrtrix3/app.py

When debugging long-running scripts (such as `dwifslpreproc`), it's sometimes useful to interrupt the process when it's already moved on from the problematic stage, but hitting Ctrl-C currently deletes the temporary folder even if the process was invoked with `-nocleanup`, which IMO is unexpected. This seems to fix it.

Python: don't cleanup on SIGINT if -nocleanup option has been provided

---

lib/mrtrix3/__init__.py

This modification allows debugging scripts with VS Code #2472. Does not break modules or the main library on macOS. I don't have Windows so untested there.
Closes #2472.

python library: tweak execute to work with VS Code #2472

---

bin/population_template
docs/reference/commands/population_template.rst

1. proposed fix to #2467 
2. also fixes that the intialisation was not used in the first registration level
3. while at it, also added the option to delete intermediate templates which could be handy if many levels are requested and storage space in scratch is limited
For context regarding 1.:
The initial template space is computed after the initial trafos `R_i` (default: translations to centre of mass) are applied to the input images. 
The drift correction is supposed to prevent changes in appearance to the template over template levels and used the average transformation `A = E [T_i ]` across the image trafos `T_i` which include the initialisation. Hence for large "outliers" in the initialisation (i.e. one subject is far form the others in scanner space), the initial drift correction …

population_template initialisation and drift correction fixes

---

core/file/dicom/element.cpp

I noticed a few issues when parsing this entry, which basically boiled down to assuming the fractional part was always 6 digits long - which doesn't hold, it can be any length _up to_ 6 digits... 
[Reference docs](https://dicom.nema.org/medical/dicom/current/output/chtml/part05/sect_6.2.html) - look for entry `DT` DateTime
I'll run my DICOM tests before merging.

DICOM: fix parsing of DateTime entry

---

lib/mrtrix3/app.py

fixes #2547
This affects the macOS native packages since they're all installed via symlinks. I suggest we apply the patch on that package straight away? I.e. build the correct 3.0.4 version, but apply this fix to the package post-hoc. A bit unorthodox, but given it should only affect the version string reported, I don't think it's a bit deal. Alternatively, we just leave that package as-is, it's not exactly a deal-breaker...?

show correct version in symlinked python scripts

---

core/file/dicom/tree.cpp
core/formats/dicom.cpp

Proposed modifications based on confusion from new user.
"Directories are DICOMs and files are other image formats" perhaps shouldn't be assumed knowledge.
Details in commit message https://github.com/MRtrix3/mrtrix3/commit/942744c739282627bc95501defac9bc3774cde5c; open to suggestions for changes.

DICOM: Tweak terminal messages

---

cmd/tckmap.cpp

This fixes issues on certain macos compilers (#2567)

resize instead of assign of std::vector

---

core/file/mgh.h

Fixes the following warning when compiling on macOS13: "This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead."

Fix sprintf deprecation warning on macOS

---

docs/reference/commands/mrview.rst
src/gui/mrview/window.cpp

Apply #2569 to `dev` branch (see also #2581 for context). 
Basically, there is only a conflict between `mrview`'s `-orientationlabel` and `-orientation` options on `dev`, since the `-orientation` option _only_ exists on `dev` (#2155). I've therefore reverted #2569 with #2581 on `master`, and cherry-picked the changes onto `dev` in this PR. 
Hope that all makes sense...

Mrview rename orientationlabel option

---

.github/workflows/checks.yml

The plan is to make use of GitHub's new merge queue feature, to reduce the faff when trying to merge multiple pull requests at the same time. More detail on the GitHub docs:
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue
Note that this has been activated on master.

Update GitHub Actions workflow for merge queue

---

.git-blame-ignore-revs

Closes #2590.
Some notes:
1.  This does not influence reporting of contribution statistics in any way; it just prevents certain commits from appearing in the individual lines of `git blame`.
2.  It does *not* prevent commits from appearing in the history of commits influencing any given file on GitHub.
3.  As noted in #2590, this should be utilised in #2585 to prevent the exploitation of nested namespaces from swamping `git blame`.

Add file ".git-blame-ignore-revs"

---

src/surface/mesh.cpp
testing/binaries/tests/mesh2voxel
testing/binaries/tests/meshconvert

-   Change binary export to single-precision floating-point.
-   Change binary export to big-endian.
-   Support import of both little-endian and big-endian data. 
Closes #2593.
Given the comments in the code I suspect this was pushed as a "well this works for its current purpose" but wasn't as robust as it should have been.
Changes result in successful loading in ParaView for both binary data generated by *MRtrix3*, and those same data loaded into *MRtrix3* and then exported as ASCII (so *MRtrix3* is reading from those data correctly).
Remaining question:
-   Whether test data needs to be added.
-   Whether `master` is the right destination: it "fixes a problem", but it also changes the output to single rather than double precision, which could be construed as a "behaviour change". Son't …

VTK surface format changes

---

bin/dwi2mask
docs/reference/commands/dwi2mask.rst
lib/mrtrix3/dwi2mask/synthstrip.py
testing/scripts/tests/dwi2mask

Add a new script to execute the algorithm called Synthstrip which uses the skull-stripping method to produce a brain mask. The script can execute normally and should produce the desired output. However, the difference-comparing test is unnecessary because it makes use of additional software outside the MRtrix3. If the developer changes the source code of the software, it is possible for the script to produce a different output file while no changes are made to the script. In order to function the Synthstrip correctly, users need to have FreeSurfer v7.3.2 or a later version installed on their native systems. This is related to #2500

Dwi2mask synthstrip: New algorithm for dwi2mask

---

lib/mrtrix3/dwi2mask/consensus.py

If the user manually provides a list of algorithms to be used, and that list does not include "`b02template`", do not go on to insert separate `dwi2mask b02template` calls for the different software algorithms that can be used within such.

dwi2mask consensus: Fix user omission of b02template

---

core/math/stats/glm.cpp

Hypothetical fix for below compilation warning resulting in CI failure on #2624.
Have not been able to reproduce this, so running through CI to see what happens.
```
ERROR: ( 37/547) [CC] tmp/core/math/stats/glm.o
g++ -c -std=c++11 -DMRTRIX_BUILD_TYPE="release version with asserts" -pthread -DMRTRIX_WINDOWS -mms-bitfields -Wa,-mbig-obj -D_FILE_OFFSET_BITS=[64](https://github.com/MRtrix3/mrtrix3/actions/runs/4892616869/jobs/8734587104#step:7:65) -Werror -DMRTRIX_WORD64 -DMRTRIX_HAVE_EIGEN_UNSUPPORTED_SPECIAL_FUNCTIONS -DEIGEN_FFTW_DEFAULT -DMRTRIX_TIFF_SUPPORT -DLIBDEFLATE_DLL -idirafter D:/a/_temp/msys64/ucrt64/include/webp -DMRTRIX_PNG_SUPPORT -idirafter D:/a/_temp/msys64/ucrt64/include/libpng16 -Wall -O3 -D_GLIBCXX_DEBUG=1 -D_GLIBCXX_DEBUG_PEDANTIC=1 -Isrc -I./core -Icmd -idirafter …
```

Potential fix for GCC12 warning on MSYS2

---

core/app.cpp

App::get_matches(): Fix buffer overrun

---

cmd/dwi2adc.cpp
cmd/fod2fixel.cpp
cmd/shbasis.cpp
cmd/tckconvert.cpp
cmd/warpcorrect.cpp
core/fixel/fixel.h
core/image_helpers.h
core/math/SH.h
src/dwi/tractography/GT/internalenergy.cpp
src/dwi/tractography/GT/particle.h
src/dwi/tractography/SIFT/model_base.h
src/dwi/tractography/mapping/fixel_td_map.h
src/gui/mrview/tool/base.cpp
src/stats/tfce.h

While I was not able to reproduce the MSYS2 CI compilation issue currently manifesting in #2624, upgrading to GCC13 in my MSYS2 resulted in other compilation warnings. This fixes some but not all of them: some files relating to registration are failing to compile but do not produce any error message.
Pending observations here and in #2631, Will want to either rebase or cherry-pick to `master`.

Fix compilation warnings on GCC13

---

cmd/fod2fixel.cpp
core/fixel/fixel.h
core/fixel/helpers.h
docs/fixel_based_analysis/fixel_directory_format.rst
docs/reference/commands/fod2fixel.rst
src/dwi/fmls.cpp
src/dwi/fmls.h

Likely resolves #2637.
The storage size problem was worse than I thought.
For the BATMAN dataset, `fod2fixel` produces ~ 100,000 fixels and requires ~ 5.5MB.
Writing the lookup table as currently done in #2625 requires an additional ~ 700MB.
The solution here requires an additional ~ 16MB.
In addition to the reduction in storage space, it actually provides a little bit more information.
Part of the FOD FMLS segmentation process is identifying dixels where the FOD lobes that are segmented as two different fixels "touch".
By representing the association between dixels and fixels as a binary dixel mask per fixel rather than a fixel index per dixel, it's possible to attribute such dixels to *both* fixels, which is more faithful, even if it potentially means more complex calculations …

FOD FMLS: Masks instead of lookup tables

---

src/surface/mesh.cpp

Mesh::load_vtk() always open files in binary mode

---

configure

Currently, we have a way to specify a compiler prefix in the configure script using the `CXX_COMPILER_LAUNCHER` environment variable. This is useful to use tools like `ccache` or `sccache`. This pull requests add supports to specify a compiler prefix with multiple arguments, which can sometimes can be handy for other tools like [bear](https://github.com/rizsotto/Bear) (e.g. you can use `CXX_COMPILER_LAUNCHER="bear --append --" ./configure` to generate a compilation database).

Add support for multiple arguments to CXX_COMPILER_LAUNCHER

---

src/dwi/fmls.cpp

Was getting segfaults from `fod2fixel` after [2704f7e](https://github.com/MRtrix3/mrtrix3/pull/2644/commits/2704f7eb06ed0b405ba465509520510e96b1469f)
A misplaced brace in the restrospective assignments loop seems to be the issue, unless I've really misunderstood the assignment process.

FOD FMLS: fix assertion failure in retrospective assignment

---

.github/workflows/checks.yml

Separating out testing changes to CI from #2437 into a separate PR so I can go back and forth on it if need be.
For whatever reason, the msys version of pip refuses to install numpy; so I'm trying the mingw64 version of python instead.

CI: Install Python / numpy via mingw64

---

core/file/dicom/element.cpp

As discussed in #2690
Problem stems from failure to handle cases where nested sequences all end at the same point. Previous implementation only closed the current sequence, without considering whether its own parents also needed to close at that point. 
I'll be running my battery of tests shortly to confirm this doesn't introduce any issues with current datasets.

DICOM: fix multiframe encoding with explicit length sequences

---

docs/conf.py

Addressing CI error observed in #2713:
```
Run python3 -m sphinx -n -N -W -w sphinx.log docs/ tmp/
python3 -m sphinx -n -N -W -w sphinx.log docs/ tmp/
shell: /usr/bin/bash -e {0}
env:
QT_SELECT: qt5
Running Sphinx v7.[2](https://github.com/MRtrix3/mrtrix3/actions/runs/6147387227/job/16678768734?pr=2713#step:7:2).[5](https://github.com/MRtrix3/mrtrix3/actions/runs/6147387227/job/16678768734?pr=2713#step:7:5)
Warning, treated as error:
Invalid configuration value found: 'language = None'. Update your configuration to a valid language code. Falling back to 'en' (English).
Error: Process completed with exit code 2.
```

Docs: Explicitly specify English language to Sphinx

---

build
cmd/mrview.cpp
cmd/shview.cpp

mrview: fix crash due to change in order of includes
Also fix generation of icons QRC file.
Both changes required following move to clang-format

mrview: fix crash due to change in order of includes

---

CMakePresets.json

Removes an extra comma in `CMakePresets.json` that prevented CMake to parse the file.

Fix typo in CMake presets file

---

bin/mrtrix3.py

First attempt at addressing #2731...
Seems to work from my limited testing. Main idea is to use `importlib` (following [suggestions from StackOverflow](https://stackoverflow.com/a/50395128)) as long as Python version is 3.5 or newer and `importlib` module can be loaded successfully. Otherwise fall back to the previous `imp` approach. Seems to work on my system using either Python 3.10 (using `importlib`) or Python 2.7 (using `imp`).

add support for python importlib to locate MRtrix3 python libraries

---

CMakeLists.txt
cmake/ECMEnableSanitizers.cmake

This PR adds a new CMake module to facilitate the use of sanitizers when building MRtrix. The module is taken from KDE's [Extra CMake Modules](https://github.com/KDE/extra-cmake-modules) repo.
The module allows to easily enable compiler sanitizer flags, for example to use thread sanitizer and the undefined behaviour sanitizer you can configure the project with 
`cmake -DECM_ENABLE_SANITIZERS="thread,undefined"`. See the relevant module file for details.
Obviously, not all compilers support all santizers. It's recommended to use `clang`, which has support for all of them.

Add CMake module for using sanitizers

---

src/CMakeLists.txt

Uses `LINK_DEPENDS_NO_SHARED` to ensure that the gui library does not have a file level dependency on the shared library files of the `mrtrix::headless` lib. This prevents `mrtrix::gui` to be relinked on every modification of `mrtrix::headless`, but only on those that trigger a change in header files.

Make mrtrix::gui to not depend on mrtrix::headless

---

.github/workflows/checks.yml

When we switched to CMake, it seems that I forgot to explicitly set Clang as the compiler for our `linux-clang-build`CI workflow, so it was using GCC since it's the default compiler on Linux. This PR fixes that.

Explicitly set compiler for CI clang build

---

.github/workflows/checks.yml

The running of our CI tests were missing the `--output-on-failure` option to show error messages when tests fail. Spotted in #2774.

Output error messages in CI checks

---

core/file/png.cpp
core/image_io/png.cpp

Addresses two of the issues reported in #2772.
Simple coding errors that were seemingly never checked with `valgrind`.

Fix memory leaks related to PNG handling

---

core/math/fft.h

The `FFT1D` class in `core/math/fft.h` never called `fftw_destroy_plan` as documented [here](https://www.fftw.org/fftw3_doc/Using-Plans.html). This resulted in a memory leak. This fix calls this function in the destructor of this class, and it also additionally provides a copy assignment operator (to follow the rule of five I have deleted the move constructor and assignment operator).

Fix memory leak in mrdegibbs

---

.github/workflows/clang-tidy.yml

- Explicitly sets configuration file to ensure that the rules in our .clang-tidy are followed.
- Update to latest version 0.17.0

Update clang-tidy-review action

---

cmd/mrmath.cpp
core/misc/voxel2vector.h

Resolves #2781.
On having a quick look at this it turned out to be not as complicated as I had feared, so I just went through and got it done. This appears to happily pass tests with the address sanitiser enabled.

mrmath: Fix unfreed memory

---

CMakeLists.txt

As mentioned by @bjeurissen this morning, we should set C++ as the language for our CMake project file since we don't rely only any C code.

Set C++ as the language in main CMakeLists.txt

---

.github/workflows/clang-tidy.yml

Our clang-tidy CI review action appears to be broken after #2782, as inspecting the log of a few workflows shows that the action is unable to find the configuration file. 
It seems that using `github.workspace` doesn't work as intended, but just using a relative path from the top level directory seems to do the job.
EDIT: this is because the Github Actions runs inside Docker

Fix clang-tidy config file path

---

cmd/fixel2voxel.cpp
core/algo/loop.h
core/algo/random_threaded_loop.h
core/algo/stochastic_threaded_loop.h
core/algo/threaded_loop.h
core/apply.h
core/fixel/loop.h
core/image_helpers.h

I noticed some potential use after move in `core/apply.h`. I think this code can be fully replaced by [std::apply](https://en.cppreference.com/w/cpp/utility/apply) introduced in C++17. This PR replaces `MR::unpack` by directly calling `std::apply` instead. `MR::apply` doesn't have a strict equivalent in the STL, but can be easily emulated using fold expressions and lambdas as below:
```cpp
namespace MR {
//! invoke \c Function f for each entry in \c Tuple t
template <typename Function, typename Tuple> constexpr void apply(Function &&f, Tuple &&t) {
std::apply([&f](auto &&...x) { (f(x), ...); }, std::forward<Tuple>(t));
}
} // namespace MR
```
We could of course replace every instance of `MR::apply` with the definition of the function above, but that would be verbose and tedious. So I …

Implement MR::apply using std::apply

---

matlab/write_mrtrix.m

Currently, `write_mrtrix.m` crashes if the output filename is a `string`:
```matlab
% char array
write_mrtrix(struct('data',rand(3,3,3)), 'test.mif')
% works without problem
% string
write_mrtrix(struct('data',rand(3,3,3)), "test.mif")
% Gives error: 
% > Array indices must be positive integers or logical values.
% >
% > Error in write_mrtrix (line 134)
% > if strcmp(filename(end-3:end), '.mif')
```
As the error message indicates, this is because array indexing does not work for `string`s. This pull request uses the Matlab functions `fileparts` and `fullfile` to avoid explicit indexing. 
I also took the opportunity to make the error message if the extension is not matched a little more informative.

Allow filename in write_mrtrix.m to be string or char array

---

python/lib/mrtrix3/app.py

Another item that keeps bugging me that I would prefer to resolve in `3.1.0`.
Purpose here is to elevate the priority of making users aware that some *MRtrix3* commands may invoke non-MRtrix3 neuroimaging software commands. We do not want the contributions of any research software packages or methods that are not our own to lose their deserved attribution. Indeed I'm considering adding a help page to the documentation explaining how this works; this is probably most likely to happen in conjunction with #2601.

Python API: Change citation notification

---

cmake/BashTests.cmake

Fixes #2832. Test files are parsed by CMake at configure time and added using `add_test`. This PR ensures that when a bash test file is modified CMake automatically reconfigures to ensure that the latest version of the tests are deployed.
@Lestropie let me know if this addresses the problem.

Regenerate CMake tests when test file is modified

---

python/bin/population_template

Found this one while porting code for #2678.
Problem appears to have been introduced [here](https://github.com/MRtrix3/mrtrix3/commit/5ad072f7721063b1d91c0a786dc23891aa11a3e0#diff-052a1ef62be05c312d0356207bf56c9896d258d58eec06da679f174ae9a3921dR1242-R1245) in 5ad072f as part of #2471. 
It does *not* affect `master`, as the drift correction functionality does not yet exist there.
I'm posting as a draft for now, as currently the average transformation is recomputed at every linear registration iteration, whereas it should only need to be done once; but I'll want to test a little more before committing that.
@maxpietsch: Do you have any good exemplar data with a clear drift?

population_template: Fix linear drift correction

---

packaging/mingw/PKGBUILD

It seems that enabling LTO on Windows causes many linker errors. It looks like that this a bug in `gcc`, so we will disable for our packaging script. See https://github.com/msys2/MINGW-packages/issues/11706

Disable LTO in msys2 packaging script

---

docs/reference/commands/mrregister.rst
src/registration/linear.cpp

Second part of #2586.
I am restricting this change to altering the `mrregister` help page to reflect what the code is actually doing. I can confirm that if those `-*_metric.diff.estimator` options are omitted, then the L2 estimator is *not* used.
There is some outside chance that it was intended for the L2 robust estimator to be the default behaviour, and that this was conveyed in the help page but the code failed to achieve this. However I'm a lot more confident in updating the help page given my naivety on the topic than changing the default software behaviour. So unless @maxpietsch interjects I think this is the way to go.
There's also an argument to be made that this should go to `master` rather than `dev`...

mrregister: Fix erroneous reporting of default robust estimators

---

share/mrtrix3/labelsgmfirst/FreeSurferSGM.txt

Change erroneously omitted from 729cba3610d5164bd2c2bc0ebca79c60a9d22f1b / #2839.
Spotted as a consequence of #2849.

Move share/mrtrix3/labelsgmfix to share/mrtrix3/labelsgmfirst

---

core/app.cpp

Closes #2822.
I think what's happening is versions of these files generated by the old `build` script are getting grabbed by a `cmake` glob rather than the versions of those files that `cmake` is itself generating in the build directory. Rather than do anything too clever, I propose to just update the error message so that if any fellow dullards manage to run into the same problem, they'll know what to do.
Pretty sure I tried just deleting those files and re-building, and the compiler failed reporting a missing file; so starting with a clean build directory might be required.

Update error message on version mismatch

---

core/algo/threaded_loop.h
core/mutexprotected.h
core/progressbar.h

Having some fun with Thread Sanitizer & clang-tidy...

dev threading fixes

---

cmake/BashTests.cmake
testing/data/python_cli/help.txt
testing/unit_tests/CMakeLists.txt
testing/unit_tests/cpp_cli
testing/unit_tests/python_cli

Testing whether the proposed change in #2845 facilitates executing the Python CLI unit tests in CI for #2678.
I do realise in retrospect that this solution might not actually live that long (even if it's a useful capability to leave in place): with #2741, the Python CLI test would need to have the same mechanism of executable binary generation.

Fix python CLI CI test

---

.brewfile
.github/workflows/checks.yml

The current method of running `brew update || brew update` works, but leads to unnecessary longer installation times. See https://github.com/Homebrew/brew/issues/2491.
This adds a `.brewfile` that lists the packages needed by the CI checks.

Install MacOS CI packages using brew bundle

---

core/CMakeLists.txt
core/math/betainc.cpp
core/math/betainc.h

Partially addresses #2857.
*Hopefully* the concern about `lgamma_r()` only being available on "some" systems should not be of concern for us given the target systems...

MR::Math::betaincreg(): Use lgamma_r()

---

.github/workflows/clang-tidy.yml

Aims to fix the running of the clang-tidy review action. The issue was encountered in #2865 and #2871.
Error message:
> CMake Warning at core/CMakeLists.txt:79 (message):
libpng not found, disabling PNG support
CMake Warning at core/CMakeLists.txt:86 (message):
libtiff not found, disabling TIFF support
fatal: detected dubious ownership in repository at '/github/workspace'
To add an exception for this directory, call:
git config --global --add safe.directory /github/workspace
fatal: detected dubious ownership in repository at '/github/workspace'
To add an exception for this directory, call:
git config --global --add safe.directory /github/workspace
CMake Error at /github/workspace/cmake/FindVersion.cmake:21 (message):
MRtrix3 base version does not match the git tag!
Instead of generating …

Fix CI clang-tidy review action 

---

CMakeLists.txt
cmake/LinkerSetup.cmake

Enables the use of the LLVM linker by default on Linux platforms. It is much faster than the standard GNU linker and can provide a significant improvement in linking time, especially in incremental builds.

Use LLVM linker on Linux if available

---

cmake/LinkerSetup.cmake

Fixes. a typo introduced in #2875

Fix typo in LinkerSetup.cmake

---

src/dwi/bootstrap.h

Two components to change:
-   Removal of `current_chunk` should have no effect. It looks to me like vestigial code from trying different approaches to keep track of buffer chunks, but the use of `next_voxel` & `last_voxel` satisfies the requirement.
-   While `get_voxel()` looks like it's doing exactly the same thing, though perhaps less elegantly, it nevertheless resolves a buffer overflow. Though it looks to me like an invalid or overwritten address rather than a conventional "off-by-one"-type overflow.
On `dev`, within an individual thread, the `value_type*` yielded by the map for a previously sampled voxel is occasionally different to that used when buffer data were allocated for that voxel. Maybe one in every 1000 times that a pointer for a previously sampled voxel is requested.
I …

Fix buffer overflow in DWI bootstrapping

---

core/file/nifti_utils.cpp
core/formats/mrtrix_gz.cpp
core/formats/mrtrix_sparse_legacy.cpp
core/formats/pipe.cpp
core/formats/ram.cpp
core/formats/xds.cpp
core/image.h

It prevents NRVO (Named Return Value Optimisation) and in fact can be a pessimisation. See [here](https://devblogs.microsoft.com/oldnewthing/20231124-00/?p=109059).

Don't use std::move for return values

---

cmake/LinkerSetup.cmake

I made the unfortunate discovery that the LLVM linker cannot perform Link Time Optimisation when compiling with GCC. See [here](https://stackoverflow.com/questions/58084395/does-lto-works-when-compiling-with-gcc-but-linking-with-llvm-lld). In fact, the compilation is broken if lld is used with GCC with LTO on.
So we simply don't use lld if we detect that GCC and LTO are used together.

Disable LLD when using GCC with LTO enabled

---

core/adapter/reslice.h

@jdtournier: This part of #2768 struck me as odd:
```
using summing_type = typename std::conditional<std::is_arithmetic<value_type>::value, double, cdouble>::type;
```
While it might result in appropriate resolution for template types currently compiled, it would attempt to use `cdouble` for any unexpected type. There's already a `struct MR::is_complex<>`, which makes more sense to me; its use makes the code intention far more clear IMO.

Adapter::Reslice: Alternative resolution of complex summation

---

testing/tools/CMakeLists.txt

Useful when you want to run tests for a single command. Currently, tests require the binaries built by `testing/tools` before they can run. However, if you build a specific target `cmake --build build --target tckgen` and then run the tests via `ctest -R bin_tckgen`, it won't work because testing tools are missing.
This PR mitigates this by allowing you to run `cmake --build build --target tckgen testing_tools` and then run `ctest -R bin_tckgen`.

Add new CMake target to build testing tools

---

.github/workflows/nightly-sanitizers.yml
.github/workflows/weekly_sanitizers.yml

Sanitizers are very valuable tools to detect problems by instrumenting code for runtime bug detection. They have already proven useful for us as demonstrated in #2760, #2761 and #2755. 
This PR adds a new GitHub Actions workflow that runs our unit and binary tests compiled with sanitizers provided by [LLVM](https://github.com/google/sanitizers) each night. It'd be rather computationally expensive to run these checks on pull requests, but my tests show that they are fast enough to be run once a day (with caching enabled).
Note that this PR must be merged into `master` since scheduled GitHub Actions only run on the default or base branch.

Add periodic checks with sanitizers

---

python/bin/dwifslpreproc

In this use case, script would erroneously attempt to execute applytopup in the calculation of a processing mask for eddy. Fix to #2266.

dwifslpreproc: Fix -rpe_header with no phase encoding contrast

---

cmd/mrgrid.cpp
docs/reference/commands/mrgrid.rst

Whitespace present in name of associated compulsory argument erroneously implies that there are two input arguments expected.

mrgrid: Fix help for -as option

---

lib/mrtrix3/run.py

Sought confirmation that fix in #2802 is correct, and found that the logs were hiding the full filesystem paths of files being used, which isn't ideal from a diagnostic perspective.

run.command(): Do not hide list inputs

---

bin/for_each
docs/reference/commands/for_each.rst

Simple addition to `for_each` documentation showing how to utilise piped images within a batch processing command.

for_each: Add example usage demonstrating shell operator escape

---

cmd/mrinfo.cpp
docs/reference/commands/mrinfo.rst

Spotted in the report in #2695. I think we can safely update that one. Grepped to make sure there aren't any other commands with the same problem.

mrinfo: Update author email

---

src/dwi/fmls.cpp

Command-line option non-functional due to an error in prior modification of the option name in #1932.
Fully expect that nobody other than myself has ever attempted to use this option. It's primarily to facilitate [a more advanced fixel segmentation](https://www.researchgate.net/publication/308380892_Sparse_re-parametrization_of_continuous_Fibre_Orientation_Distributions_using_spherical_harmonic_delta_functions) that I've never had the opportunity to finish off. So most likely hasn't detrimentally impacted any users. Indeed if anyone had used it, I would hope that they would have discovered that there were no differences in FOD segmentation between inclusion and omission of the option.

fod2fixel: Fix -fmls_lobe_merge_ratio

---

cmd/mrregister.cpp

Error introduced in d81d0ed101c0005519bf33b567395867fc4ce150 as manual refinement of #2829.
Issue wasn't picked up because of incomplete coverage of `mrregister` tests; but `population_template` tests (not run by CI) fail.

mrregister: Fix -nl_init option

---

src/gui/opengl/gl_core_3_3.cpp

Extension of #2913.
Tried to quickly read up on the topic. It is considered most severely problematic to not define `NOMINMAX`, but there's strong disdain generally for including `windows.h` rather than sub-components thereof. As stated in #2913 this could be done, but would require more effort. What I thought I'd try here is throw in some #defines that are intended to disable certain components of `windows.h` that are commonly not required. This specific list I pulled from [here](https://belaycpp.com/2021/05/11/windows-h-breaks-the-stl-and-my-will-to-live/#comment-4), but have seen various references to these in different places.

OpenGL: Minimise what is imported by windows.h

---

src/gui/opengl/gl_core_3_3.cpp

Including `src/gui/opengl/gl_core_3_3.h` should automatically include `windows.h` if `APIENTRY` is not defined. Still, some libraries (e.g., the latest versions of Qt) define this macro without including `windows.h` in their public headers (to avoid polluting the global namespace).
Since this issue is currently preventing the merging of PRs on `dev`, a quick solution that explicitly includes `<windows.h>` is added to deal with this.
Ideally, no public header should automatically include `windows.h`, so a more robust approach is warranted here. We could either wrap the header to prevent the propagation of `windows.h` or replace it with something else. Will try to address this in a future PR.

Add missing windows.h include header

---

CMakeLists.txt

We primarily test our builds with Ninja, which is not the default on most platforms. This PR adds a warning if other generators are used to build MRtrix3 to recommend using Ninja instead.

Add warning if cmake generator is not Ninja

---

CMakeLists.txt
src/CMakeLists.txt

As mentioned in the meeting today, it'd make sense for production builds to have the C++ code in `src` built as a static library. This PR adds a new `MRTRIX_BUILD_STATIC` option to allow for this (@MRtrix3/mrtrix3-devs if anyone has a better name please let me know).
The option is disabled by default and is only intended to be enabled in production and external projects. For every day builds, making shared libraries provides a faster incremental build workflow.

New option to build non-core code as a static lib

---

packaging/macos/build
packaging/mingw/PKGBUILD
packaging/package-linux-tarball.sh

- Build releases by with `-DMRTRIX_BUILD_NON_CORE_STATIC` enabled, to avoid building the code in `src` into a separate shared library.
- Don't use precompiled headers when building macOS releases.

Minor changes to packaging scripts

---

core/progressbar.cpp

Likely resolves #1980.
Discovered that `mrinfo`-ing to a file produced the simplified progress bar, whereas using `2>&1 | tee` used the dynamic progress bar, producing a whole lot of junk at the head of the file if opened in a text editor.
This change means that MRtrix3 C++ commands invoked by a MRtrix3 Python command, where the latter is invoked with `-info` or `-debug` (and therefore shows dynamic information about executed processes), will now show the simplified progress bar; this is perfectly fine by me. Similarly if the stdout / stderr contents of a failed command are written to text file in the scratch directory, they will also have the simplified appearance, as they ideally should.
Not 100% happy with the appearance of the simplified progress bar (see eg. #1744), but not the top …

ProgressBar: Simple update method where stderr is pipe

---

cmake/FindFFTW.cmake
packaging/macos/build

Prevents failure when unused single and quad precision are not available

Modified FindFFTW to only look for double precision version of fftw3

---

.github/workflows/releases.yml

This PR succeeds the work done in #2835. As mentioned there, instead of having a separate workflow for weekly releases, it's better to have a single CI workflow that manages both tagged and periodic releases. 
As a first step towards that, this PR introduces a new CI workflow which creates artefacts of release builds using GitHub Actions. The artefacts are named as `mrtrix3-{os}-{branch}.{extension}` (@MRtrix3/mrtrix3-devs let me know if we want to add further information like build dates).
The workflow can be triggered manually, and the developer can specify the branch of MRtrix3 they want to build (the branch will need to be based on `cmake`).
This will be useful firstly because it allows a developer to create a release for a particular feature branch of their choice. Secondly, it will …

New workflow for releases

---

bin/mrtrix3.py
lib/mrtrix3/path.py
lib/mrtrix3/run.py

This fix is exclusively for `master` / 3.0.x, to support Python 3.12 whilst preserving Python2 support. On `dev`, Python2 support has been dropped, and `shutil.which()` is used by name.
`./run_tests scripts` successful.
Can't fully verify via CI as Python2 support is not explicitly tested. No particular interest in doing so either; would prefer to focus on testing the range of Python3 versions supported (#2821) for 3.1. So hopefully this can be reviewed from first principles.

Deprecated distutils module in Python 3.12

---

python/mrtrix3/app.py

This should unblock CI tests on `dev`.
The newly-used "pathlib" module prior to Python 3.12 utilises the `__new__()` function to initialise member variables; Python 3.12 more suitably uses `__init__()`.
I wasn't able to figure out a cleaner syntax that would work with both versions.
While we had some prior discussion about the use of composition rather than inheritance, here that composition would consist almost exclusively of pass-throughs. So I'm going to stick with the multi-inheritance strategy, at least for now. I might do some re-arrangement to allow developers to construct fstring-quote-escaped filesystem paths outside of the CLI, but I'll defer that until after CI on `dev` is unblocked.

Python API: Support Python 3.12

---

CMakeLists.txt
cmd/CMakeLists.txt
core/CMakeLists.txt
core/file/npy.cpp

Previously we relied on `add_compile_options` and `add_compile_definitions` for defining compiler definitions and options for the entire project. This commit replaces that behaviour by defining a new `mrtrix::common` INTERFACE library that links to all targets in the project (the library is linked to `mrtrix::core`). This is more CMake-idiomatic and prevents the propagation of compiler definitions to targets that do not link to `mrtrix::core` (useful when compiling MRtrix3 as a subproject of another project). Ideally, we should be using CMake presets for this kind of stuff, but we need to support CMake 3.16.

Add interface library for project-wide compile options

---

python/mrtrix3/run.py

In doing #2957 I noticed an issue whereby whenever I manually invoked my compiled-from-source Python 3.12, any Python scripts that themselves invoke Python scripts would revert to Python 3.10 that was in my `PATH`. This is contrary to previously constructed code whose intent was to ensure that if a Python script invoked another Python script, the same interpreter would be used (#1828). This occurred because on `dev`, in the course of dropping Python2 support on `dev` (#2215), the script shebangs were changed to `/usr/bin/python3` rather than `/usr/bin/env python3`---note that this persists through #2741---but the code for explicit shebang parsing was not tested on such.
I note that a reversion back to using `/usr/bin/env` seems to be the most appropriate course of action from discussion …

mrtrix3.run: Improved shebang parsing

---

core/file/mmap.cpp

This had been discussed in some detail back when #2554 was first discussed, but AFAICT this change was never explicitly proposed. Makes a measurable difference to command execution times when writing to a host drive.

Windows: Delayed writeback to host

---

src/colourmap.h
src/gui/mrview/colourmap_button.cpp
src/gui/mrview/gui_image.cpp
src/gui/mrview/tool/fixel/fixel.cpp

In 62861585ac9dedfdc64d2879124ab392ac4736a4, as part of #2911, `ColourMap::maps` was converted from a null-terminated C array to a `std::vector`. However, the loops iterating over this list weren't updated and were still relying on null-termination causing an invalid memory access. This also resulted `mrview` crashing on MacOS.
@bjeurissen Could you check if this fixes the crash on your system?

Fix invalid memory access when reading colour maps

---

clang-format-all

Repost of #2973, for which I hastily hit the merge button after resolving #2859 only to realise the next second that it had been based off the original #2859 branch and therefore re-applied the unwanted commits. Just cherry-picked the single commit onto latest `dev`.

clang-format-all: Fix shebang

---

src/gui/mrview/qthelpers.cpp
src/gui/mrview/qthelpers.h
src/gui/mrview/tool/fixel/fixel.cpp
src/gui/mrview/tool/overlay.cpp
src/gui/mrview/tool/roi_editor/roi.cpp
src/gui/mrview/tool/tractography/tractography.cpp
src/gui/mrview/window.cpp

Fix drag & drop on Windows for mrview

---

python/mrtrix3/commands/dwibiasnormmask.py

Erroneous re-use of variable name resulted in always attempting to use the synthstrip algorithm rather than the default / user selection.

dwibiasnormmask: Fix masking algorithm selection

---

cmd/dirmerge.cpp
docs/reference/commands/dirmerge.rst
testing/binaries/CMakeLists.txt
testing/binaries/tests/dirmerge/foursubsets
testing/binaries/tests/dirmerge/foursubsets_firstisfirst
testing/binaries/tests/dirmerge/onesubset
testing/binaries/tests/dirmerge/onesubset_firstisfirst
testing/binaries/tests/dirmerge/twosubsets
testing/binaries/tests/dirmerge/twosubsets_firstisfirst

Did this in addition to #2749 as I needed to modify the gradient table for the local primary project and therefore figured I'd address this annoyance as well.
Previously, the first volume in the output scheme was chosen as a random volume from the first subset of the first shell. Here, this is modified to instead be a random volume from the largest subset of the largest shell. This should slightly improve the quality of distribution of bmax volumes across the acquisition time.
Closes #2677.
@jdtournier: I've only tested this with my own usage of `dirmerge`, which doesn't involve multiple subsets as input (since Siemens can't interleave phase encoding directions). Do you have data lying around that you can feed into this modified version? Otherwise I'll have to synthesize something, as …

dirmerge: Better selection of first volume

---

python/mrtrix3/commands/dwi2mask/hdbet.py
python/mrtrix3/commands/dwi2mask/mtnorm.py
python/mrtrix3/commands/dwibiascorrect/mtnorm.py
python/mrtrix3/commands/dwibiasnormmask.py
python/mrtrix3/commands/dwigradcheck.py
python/mrtrix3/commands/dwinormalise/mtnorm.py
testing/pylint.rc

These were throwing warnings on my Windows machine with Python 3.11.9, pylint 3.2.5.
If the GitHub CI runners get upgraded to this level, some of this may need to be back-propagated to `master`; for now I'm just getting warnings out of my way while I fix other things.

Fix warnings from new pylint version

---

cmake/MakePythonExecutable.cmake

I keep alluding to it but not actually committing.
Closes #2261.
Based on #2261 and many other conversations (eg. #2215), I think that reverting `dev` to using `env` but specifying `python3` as the interpreter is the right way to go.

Python executables shebang: use env

---

cmake/Dependencies.cmake

Enabling `LOG_DOWNLOAD` the output of the download step for NIfTI headers is logged to CMake log files in the build directory, instead of the console. This reduces the unnecessary verbosity mentioned in #2984.

Disable download logs for NIfTI headers to the console

---

python/mrtrix3/commands/dwibiasnormmask.py

- Report absence of prior Dice coefficient, rather than a value of 0.0.
- Compute mask overlap image as a bitwise mask.

dwibiasnormmask minor tweaks

---

cmake/Dependencies.cmake

The NIH website seems to be too unreliable and is often down. So we download the headers from [GitHub](https://github.com/NIFTI-Imaging/nifti_clib/tree/master) instead. Addresses #2984.

Download NIfTI headers from GitHub

---

CMakeLists.txt
cmake/LinkerSetup.cmake

We no longer use LLD by default if it is available for reasons mentioned in #2986. The use of LLD can now be enabled by using `-DMRTRIX_USE_LLD=ON`. This option only exists as a convenience and will be removed once our target CMake version matches 3.19 or higher (as we will be able to leverage CMake presets to achieve the same thing).
Additionally, we use CMake's `check_cxx_compiler_flag` to see if the compiler supports LLD regardless of the platform (instead of simply relying on the presence of `ld.lld`).

Disable the use of LLD by default

---

core/formats/pipe.cpp

This popped up in evaluating #1392 / https://github.com/ankitasanil/mrtrix3/pull/1.
It seems to me that the error message created in this instance is not tailored to interpretation by a user who encounters that message.

Pipe image format: Revise error message

---

cmake/FindVersion.cmake

The logic in `cmake/FindVersion.cmake` was mistakenly assuming that a git repo has been checked out. This is not the case when building release tarballs.
This PR fixes this by running the version matching logic *only* if the directory `.git` exists in the root directory of the project.
Fixes #2987.

Fix building project with non-git repos

---

testing/binaries/tests/dirrotate/default

Prevents array values close to zero printed in scientific notation from appearing at the top of the reverse-sorted list.
Resolves issue [reported](https://github.com/MRtrix3/mrtrix3/pull/3006#issuecomment-2357862279) in #3006.

dirrotate: Fix default test

---

cmake/Dependencies.cmake

This allows the headers to be downloaded at configure time so they're unconditionally available to all targets at build time.
Closes #3002

Use FetchContent to download NIfTI headers

---

testing/README.md

Addresses #2826.
Testing tips and instructions have been updated to reflect the transition to CMake. Sections on the handling of testing data assume #2848 has been merged. 
Some instructions may not be clear or need removing due to the fact that some of the concerns/workflows no longer apply with the transition to CMake. 
It's still WIP.

Update testing README

---

testing/binaries/tests/dirrotate/default

Should fix issue [reported](https://github.com/MRtrix3/mrtrix3/pull/3012#issuecomment-2376982389) in #3012. Seems to be some kind of race condition in the BASH `[[ ]]` / `[ ]` implementation, where sometimes the "`1`" yielded by `bc` would be invoked as a command name. But it was inconsistent. And running the script manually rather than via `ctest` would never fault. So kinda weird. I've verified that this is indeed testing for expected behaviour by flipping the inequality test.

dirrotate: Test using awk rather than bc

---

.github/workflows/checks.yml

When making a PR pushing additional commits triggers the launch of our CI checks without cancelling the previous runs. This can be quite wasteful and unnecessary. This PR fixes that. Explanation of the code change [here](https://stackoverflow.com/questions/66335225/how-to-cancel-previous-runs-in-the-pr-when-you-push-new-commitsupdate-the-curre).

Cancel previous Github Action runs in PRs

---

cmd/dwi2tensor.cpp

Currently, the output of `dwi2tensor -predicted_signal` can't be loaded in the `mrview` ODF tool, as `dw_scheme` is shashed to `prior_dw_scheme`. This change ensures that `dw_scheme` remains present in the output of the `-predicted_signal` option, but is stashed for all other outputs.

dwi2tensor: Preserve dw_scheme for -predicted_signal

---

core/file/dicom/select_cmdline.cpp

Manually rewrote #2905 for `master` given that it is a problem that presumably manifests there also.

DICOM command-line selection: abort on error reading from std::cin

---

bin/population_template

Previous code attempted to write to the dictionary while looping over it; this yields an Exception.

population_template: Fix aggregation weights import

---

core/app.cpp

Noticed while working on #2678 an assertion failure for which the fix is applicable to `master`. Can see the difference for example for `mrconvert -bvalue_scaling` option, which currently does not report a type in `__print_full_usage__`.
Raises a secondary question. Just as the RST documentation is generated and stored within the repository and CI then re-generates and cross-checks against that content, there is an argument to be made for the full interface definitions generated by `__print_full_usage__` to be stored within the repository also (as has been argued for the Pydra interfaces in #2665).

Docs: Fix missing boolean types in full usage

---

core/file/png.cpp
core/file/png.h
core/formats/png.cpp
core/header.cpp
core/image_io/png.cpp
core/image_io/ram.cpp
core/image_io/ram.h
core/image_io/scratch.cpp
core/image_io/scratch.h
core/image_io/tiff.cpp
core/image_io/tiff.h
core/image_io/variable_scaling.cpp
core/image_io/variable_scaling.h
testing/binaries/tests/mrconvert

Fixes erroneous check put in place in #2535 (3acf6cc).
@jdtournier #2535 looks wrong just from the code. Look at the check vs. the error message. This I expect to still catch the erroneous use case before segfaulting, but no longer block normal operation as seems to be happening with 3.0.4. Would ideally have some unit tests...

PNG: Fix check for too few axes, memory, orientations

---

configure

Recent versions of FSL seem to ship with a full working miniconda environment, including a compiler and associated tools, and the full Qt SDK. This will cause all kinds of conflicts at the configure stage. This commit detects and mention of 'fsl' in any component and the PATH and strips it out, using the same approach as for anaconda. 
This has led to problems reported on the forum, e.g.:
https://community.mrtrix.org/t/a-problem-of-dwifslpreproc/6959?u=jdtournier
https://community.mrtrix.org/t/error-linking-qt-application-centos7/6851?u=jdtournier

configure: strip FSL from PATH

---

docs/installation/using_containers.rst

Simple addition to the documentation. Without the "--nv" flag, Singularity doesn't pass through the required access to NVIDIA drivers. If you're not using these, the existing code should work. But, if you do have NVIDIA drivers installed, you need to tell Singularity to get access to them.

Fix for mrview / singularity / NVIDIA

---

Dockerfile
Singularity

Closes #2921.
See also https://github.com/MRtrix3/containers/pull/26, which includes changes necessary to produce the minified FSL dependency that this change then downloads from OSF.
While the container minification process *intended* to capture EddyQC's `eddy_quad`, the fact that it was not being properly executed was missed because `dwifslpreproc` does not return non-zero if it fails to execute.
Unfortunately I couldn't easily resolve just this one thing. I've ended up having to update the FSL version as well. Which is not fantastic for a patch MRtrix update, since there's some chance of a change in behaviour out of our control.
Regarding #2921, if this change is deemed acceptable I can push it to DockerHub as `latest`, which would make it easy for people to access immediately but …

Fixes to containers FSL dependency

---

lib/mrtrix3/path.py

Thought that I had resolved this previously, probably when doing #2609, but in doing some other refactoring discovered that the problematic code was still in place. Maybe I fixed it some time but never pushed.
-   `num_exit()` was a bad name for the function given its operation; it checks for the number of files in a list that *exist*. But there was also an integer variable called `num_exist`.
-   `num_in_use()` function immediately got hidden behind integer variable `num_in_use`.
-   Function was immediately waiting 60s, rather than the intended operation of using a progressively increasing delay time up to a *maximum* of 60s.
The functionality should be reviewable from the code, it's pretty obviously wrong. Verifying within an existing script is hard because I can't replicate the …

mrtrix3.path.wait_for(): Fix variable ghosting

---

cmd/voxel2mesh.cpp
src/surface/algo/image2mesh.h

Two minor glitches I found in `voxel2mesh` when diagnosing issues reported by a colleague.

voxel2mesh fixes

---

cmd/dwi2tensor.cpp

Problem has been present since initial addition of iterative reweighted least squares for tensor fitting in #1542.
Does *not* affect default operation; only affects the specific use case of `-iter 1`.

dwi2tensor: fix operation with -iter 1

---

cmd/dwiextract.cpp
cmd/mrinfo.cpp
cmd/mrtransform.cpp
core/dwi/gradient.cpp
core/dwi/gradient.h
core/dwi/shells.h
core/filter/dwi_brain_mask.h
core/header.cpp
src/dwi/sdeconv/csd.h
testing/binaries/tests/mrcalc

Closes #3015.
As part of this change, I decided that the "*b*=0 threshold" is more appropriate in `dwi/gradient.h` rather than `dwi/shells.h`, since it may be applied to individual volumes rather than shells. Here it's used to say "if two images both have a *b*=0 volume here, then their diffusion gradient tables are compatible; I don't care if their unit directions are different".
Also fixed some transitive includes in the process.
The new tests should hopefully demonstrate the fix:
-   Without this PR, the two "`dw_scheme`" entries only have to differ by one least significant digit to result in the whole diffusion gradient table being discarded.
-   But conversely, if two images undergo an operation and their diffusion gradient tables are totally incompatible, it'll still be dropped. …

Tolerance for dw_scheme differences on header merge

---

core/file/dicom/image.cpp

See discussion in #2977
Full testing underway...

DICOM: ignore image positioning tags if nested within Philips private sequence

---

python/mrtrix3/commands/dwi2mask/hdbet.py

Fixes variable name ghosting bug that arises where first attempt to run third-party command `hd-bet` using the GPU fails.

dwi2mask hdbet: Fix exception handling

---

docs/reference/commands/5ttgen.rst
python/mrtrix3/commands/5ttgen/hsvs.py

- Fix progress bar for when FSL FAST is not used for the cerebellum, and the FreeSurfer segmentations of the cerebellar hemispheres are propagated to the 5TT image.
- New option `-freesurfer_lut`, for manually specifying the location of the FreeSurfer lookup table file; this permits utilisation of the script without environment variable `FREESURFER_HOME` being set, or indeed even the FreeSurfer software being present (related to #3073).
- Add missing citations to help page documentation.

5ttgen hsvs: Multiple changes / fixes

---

cpp/CMakeLists.txt

FIX: don't build gui subdirectory with BUILD_GUI=OFF

---

src/dwi/tractography/file.h

This addresses an issue raised on the forum, and is due to our use of a write-back buffer (to prevent file segmentation) with a default size of 16MB. This is ample for regular streamlines, but clearly not enough in all cases...
Original issue:
https://community.mrtrix.org/t/tckgen-seed-point-visualization/8271/2

Fix tck writer when a single streamline exceed the buffer size

---

.github/workflows/clang-tidy.yml

We also explicitly specify the clang-tidy version wanted (currently set to 16). This should fix the failing clang-tidy checks noticed in recent PRs.

Update clang-tidy-review action to v0.20.1

---

cpp/cmd/dwi2tensor.cpp
testing/CMakeLists.txt

Restores `dev` to include the fix in #3056 that was seemingly lost during the construction of #3061. 
The mass changes happening on `dev` are going to make us increasingly prone to errors in merge resolution. When we get to the point of merging `3.1.0` we are going to have to do a manual check of all bugfixes in PRs targeting `master` and `dev` and make sure that none of them have slipped away.

dwi2tensor: Fix operation with -iter 1 (re-apply)

---

CMakeLists.txt
cmake/BuildInfo.cmake

A small addition that prints build instructions when CMake has finished configuring the project. Also add a suggestion to try to remove `CMakeCache.txt` (or use the `--fresh` flag) if reconfiguration fails (this is a less drastic measure than `rm -rf build`).

Print build information at the end of configuration

---

CMakeLists.txt
cpp/CMakeLists.txt

After #3012, the CMake modules relevant for C++ commands don't propagate to the testing subdirectory. This broke our sanitisers tests (among other things). 
This PR moves the inclusion of those modules in the root `CMakeLists.txt` to fix that.

Include CMake modules in root CMakeLists.txt

---

cpp/cmd/CMakeLists.txt
python/mrtrix3/commands/CMakeLists.txt

This PR aims to address the issue raised in #3068 . The developer can now specify an individual Python target to build (e.g. `cmake --build build --target dwicat`), just like it's already possible for C++ commands. It's also possible to build all Python commands by building the `PythonCommands` target.

Add individual targets for Python commands

---

.github/workflows/checks.yml
.github/workflows/weekly_sanitizers.yml

This PR updates the `mozilla-actions/sccache-action` used in CI workflows to version 0.0.9.
Fixes #3088.

Update sccache version to 0.0.9

---

.github/workflows/package-linux-anaconda.yml
.github/workflows/package-macos-anaconda.yml
.github/workflows/package-macos-native.yml
.github/workflows/package-windows-msys2.yml

This PR fixes all of our packaging workflows in preparation for the 3.0.5 release. Main changes:
- Windows workflow now uses the same Github Action used on `dev` to set up an MSYS2 environment (MINGW64 instead of UCRT64 for compatibility reasons). Additionally, an explicit addition of `-lopengl32` linker flag has been made (otherwise the build was failing).
- The MacOS conda workflow now uses the [conda-incubator/setup-miniconda](https://github.com/conda-incubator/setup-miniconda) to set up a `miniconda` environment.
- Qt 5.15.2 is used for the MacOS native build (we may want to discuss this further).
- Extensions of release artefacts have been changed to match the new standards used by package managers (`conda` and `pacman`).
Since GitHub Actions are painful to debug, I tested these on a …

Fix packaging workflows on master

---

.github/workflows/package-linux-anaconda.yml
.github/workflows/package-macos-anaconda.yml

Small fixes for Linux/MacOS conda workflows:
- Change extensions of build artefacts.
- Install conda-build from conda-forge channel.
We still need to update the version in `core/version.h` and then we should be ready for the release.

Final GA workflows changes for 3.0.5

---

.clang-tidy

See [misc-non-private-member-variables-in-classes](https://clang.llvm.org/extra/clang-tidy/checks/misc/non-private-member-variables-in-classes.html). 
While I understand the reasoning behind this check, I believe that in the overwhelming majority of cases the check doesn't really provide any concrete benefits and it boils down to preference. Encapsulating everything via getters and setters, while useful in some scenarios, hurts readability.
I'm proposing to remove it.

Remove misc-non-private-member-variables-in-classes check clang-tidy check

---

.github/workflows/checks.yml

It looks like newer versions of Qt require CMake 3.22 as a minimum to be used. In #3085, this caused a failure of the CI checks on MacOS where Qt is installed through `brew`. This PR upgrades the CMake version used for the MacOS CI from 3.21 to 3.22.

Upgrade CMake version to 3.22 for MacOS CI

---

Doxyfile

Some paths have changed in the dev version vs the master. Consequently several paths in Doxyfile are wrong.
This simple PR just corrects that.
And while I was there I also update Doxyfile using doxygen -u (doxygen version 1.12.0).

Correct C++ file paths for doxygen

---

src/dwi/tractography/connectome/matrix.cpp

Only prevents erroneous assertion failure; no effect to processing results in release mode.
(`mat2vec` is `nullptr` if the command is run with the `-vector` command-line option as it is not needed)

tck2connectome: Fix erroneous assertion with -vector

---

.github/workflows/clang-tidy.yml

See changelog [here](https://github.com/ZedThree/clang-tidy-review/releases/tag/v0.21.0).

Update clang-tidy-review action to 0.21.0

---

cpp/core/exception.cpp
cpp/core/exception.h

This improves interoperability with third party libraries so that any code that calls `try ... catch(std::exception& e) {...}` will automatically catch our exceptions.
This is a good [discussion](https://softwareengineering.stackexchange.com/questions/305641/should-one-derive-inherit-from-stdexception) on the idea.

Derive MR::Exception from std::exception

---

python/mrtrix3/app.py

Extension to #2840, in light of ongoing exploration of software licensing. If an *MRtrix3* Python command invokes a command from some other neuroimaging command, it's not just citation that's required, it's also making sure that the user is not in violation of the licensing requirements of that third party software just because it's being invokved through an *MRtrix3* interface.

Python API: External software usage warning includes licenses

---

cpp/core/app.cpp
cpp/core/cmdline_option.h
cpp/core/mrtrix.cpp
cpp/core/mrtrix.h
testing/data/cpp_cli/full_usage.txt
testing/data/cpp_cli/help.txt
testing/data/cpp_cli/markdown.md
testing/data/cpp_cli/restructured_text.rst
testing/unit_tests/cpp_cli
testing/unit_tests/python_cli

Fixes some regressions introduced in #2911:
-  Boolean operators for Argument and Option classes returned reversed truth values.
- Leading dashes were mistakenly being removed from arguments provided for an option.
Also added some CLI parsing tests in `cpp_cli` to prevent future regressions.
It should address issue raised #3110.

Fixes for CLI parsing

---

core/dwi/gradient.cpp
core/dwi/gradient.h
core/header.cpp
core/header.h
testing/binaries/tests/mrcat

Initially thought that this was a minor annoyance that only affected specific data, but turns out to have been more widespread. See description in 568b28eece279eae6d5bee05bd5abf9555e82127.
`3.0.5` fails the second of the three new tests. Problem introduced in #3027, so 3.0.4 unaffected.
Even if concatenating two 4D series along the volume axis, where the two gradient tables should be stacked atop one another, `mrcat` produces a warning about an inability to *merge* gradient tables. The appropriately *concatenated* gradient table would still be present in the output image, it would just be an erroneous warning at the terminal.
Involves an addition of test data (in retrospect wasn't strictly necessary, but might be of use elsewhere); so `master` branch on test_data repo should be forwarded …

Suppress erroneous warning RE merging of gradient table

---

bin/dwifslpreproc
cmd/mrconvert.cpp
cmd/mrinfo.cpp
core/metadata/phase_encoding.cpp
core/metadata/phase_encoding.h
docs/concepts/pe_scheme.rst
docs/reference/commands/dwiextract.rst
docs/reference/commands/mrconvert.rst
docs/reference/commands/mrinfo.rst

As suspected following posting of #3122 and reported in #3127, there are residual issues with the handling of phase encoding data. I am creating this PR so that I can more easily pull the data into https://github.com/Lestropie/DWI_metadata and perform more exhaustive tests.
Certainly as a first pass, with current `master` code, when I combine data with more complex phase encoding contrast than just reversal, results are OK if the NIfTI is left-handed but erroneous if right-handed.
(currently trying to run `eddy` utilising all of the data for each candidate stride list is prohibitively slow, so I will need to derive some trickery to utilise only a subset of the available data in such a way that `eddy` still works OK and can confirm that interpretation of phase encoding is correct)
(If data …

Fixes to external phase encoding table handling

---

cmake/GenPythonCommandsLists.cmake

Change absent from #3012 necessary to preserve functionality added in #2920.
Effect was that any Python command invoking an *MRtrix3* C++ command would fail to recognise it as an *MRtrix3* command, and would therefore omit changes that trigger in that instance, such as propagating `-nthreads` or setting `-force` when necessary.

Fix command list generation for Python API

---

python/mrtrix3/commands/population_template/execute.py

Errors in refactoring in cd339306dda6f992207038901518f56651116d1b as part of #2678.
Python script tests do not currently include multi-contrast registration, nor do they include the "robust mass" initial alignment option. I will need to add some; some should go with #2916, others I will need to decide whether I'm going to take on #2800.

population_template: Fix multi-contrast registration

---

python/mrtrix3/commands/dwifslpreproc.py
testing/scripts/CMakeLists.txt
testing/scripts/tests/dwifslpreproc/topup_files

Errors in completion of Python CLI changes in #2678 to support addition of -topup_files option in #2150. New tests ensure that set of intended possible user-specified paths are supported.

dwifslpreproc: Fix -topup_files option

---

cpp/cmd/mrdegibbs.cpp
cpp/core/degibbs/degibbs.h
cpp/core/degibbs/unring1d.h
cpp/core/degibbs/unring2d.h
cpp/core/degibbs/unring3d.h
docs/reference/commands/mrdegibbs.rst

In confirming whether I needed to put `mrcalc -abs` upstream or downstream of `mrdegibbs`, it looks like `3.0.x` reads the input image as real-valued, whereas `dev` permits complex-valued data for both 2D and 3D variants. This capability was however not mentioned at all in the description section of the command help page.
While resolving that I decided that the type definitions in this context were ambiguous (is "`value_type`" real or complex?).

mrdegibbs: Describe complex-valued capability, update types

---

.clang-tidy

Removes the [readability-function-cognitive-complexity](https://clang.llvm.org/extra/clang-tidy/checks/readability/function-cognitive-complexity.html).
Long functions can sometimes hurt readability, but each function needs to be assessed on a case by case basis,. I think this generic check is not so useful.

Remove readability-function-cognitive-complexity clang-tidy check

---

python/mrtrix3/run.py

The existing implementation of -continue assumed that, for a list of elements to be provided to `subprocess.run()`, each element was a string, and therefore string operations could be applied. However with the adoption of `pathlib` for handling user-specified paths in #2678, an element in this list may be a class derived from those provided in the `pathlib` module that does not provide string functions.

run.command(): Fix operation of -continue

---

core/axes.h

Oversight in #3011. Believe that at some point I changed the function from checking for a non-identity transform to checking for an identity transform, and one of the operators didn't get changed.
This should affect any NIfTI export. My best guess right now regarding how this could have survived my barrage of tests is that the metadata checks had no issue in terms of concordance with the image data, but the image data themselves were not conforming to the axis strides that were being requested, and the metadata tests in github.com/Lestropie/DWI_metadata were not doing any check for that and the CI tests in MRtrix3 don't have adequate coverage.

MR::Axes::permutations_type: Fix is_identity()

---

cmd/tcksample.cpp
docs/reference/commands/tcksample.rst

Closes #2942.
The input being a 4D SH should perhaps be a derived class, which instantiates the precomputer and has a local buffer for loading SH coefficients from the image.

tcksample: Ability to sample SH amplitudes

---

cmd/mesh2voxel.cpp
src/surface/algo/mesh2image.cpp
testing/binaries/tests/mesh2voxel

Simple change to reduce the template voxel grid image to 3D if the image provided by the user is > 3D.
Given it is not an enhancement of features, but rather precludes the throwing of an unhandled exception, I suggest that it belongs on `master`.

mesh2voxel: Accept >3D image as template voxel grid

---

testing/binaries/tests/dirrotate/default

#3014 didn't fully fix the sporadic `dirrotate` test failures.
This one will hopefully get it.
Wasn't an inadequate number of spins tested as I had hypothesized; just me not using the right Unix text manipulations.

Testing: Fix dirrotate default test

---

src/colourmap.cpp

Fix compilation error leading to `Eigen::internal::traits<double>` errors.
This is currently blocking PRs targeting `master` due to CI build failures on macOS.

Fix Eigen 3.4.1 type mismatch in `ColourMap` clamping

---

configure

Qt5 links to both OpenGL and AGL for OpenGL apps, but AGL is no longer included in MacOS Tahoe/Xcode26 (https://bugreports.qt.io/browse/QTBUG-137687). This will cause our configure script to fail on latest macOS. This issue will not be addressed in future Qt5 versions (only in Qt6), but we can work around it by explicitly linking only to OpenGL.

Update configure script for Xcode26 compatibility

---

core/mrtrix.cpp

Error in 8e3612aebac43ccd56c014d0c2ee87035f55e6c6 as part of #1929.
I expect this to be of no consequence to behaviour, so not even applying the `bug` tag; it's just preventing unnecessary recursive construction of `std::string`'s.
(This will be better addressed using `std::string_view` on dev; that's how I found it)

DICOM: Performance fix to wildcard matching

---

src/gui/mrview/mode/slice.cpp
src/gui/mrview/tool/roi_editor/item.cpp
src/gui/mrview/tool/roi_editor/roi.cpp
src/gui/mrview/tool/roi_editor/undoentry.cpp

This small change fixes #2319.
After the discussion this morning with @bjeurissen, I decided to investigate this long-standing issue in the viewer. So this wasn't really a driver issue as discussed in the relevant issue, but an error in our code.
After tinkering with OpenGL code a bit, I noticed that the undo/redo shader in [`undoentry.cpp`](https://github.com/MRtrix3/mrtrix3/blob/56fa0604486cb1dbca1c36d8526a5eddc5bc405d/cpp/gui/mrview/tool/roi_editor/undoentry.cpp#L33) was using an integer sampler to read the values from the texture.
Our texture data type is `GL_R8`, which is an 8-bit normalised fixed-point format. It needs a float sampler, because integer samplers are for *integer* formats like `GL_R8I`. 
@MRtrix3/mrtrix3-devs should we include this fix in 3.0.8?

Fix ROI edits disappearing on MacOS

---

cmd/afdconnectivity.cpp
cmd/tcksift2.cpp
docs/reference/commands/afdconnectivity.rst
docs/reference/commands/tcksift2.rst

Maybe this is why I keep seeing manuscripts cite the preprint rather than the article?

tcksift2 & afdconnectivity: Update citation
